/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.ui.debug.ControlTree");jQuery.sap.require("sap.ui.base.EventProvider");sap.ui.base.EventProvider.extend("sap.ui.debug.ControlTree",{constructor:function(c,w,p,r){sap.ui.base.EventProvider.apply(this,arguments);this.oWindow=w;this.oDocument=w.document;this.oCore=c;this.oSelectedNode=null;this.oParentDomRef=p;this.oSelectionHighlighter=new sap.ui.debug.Highlighter("sap-ui-testsuite-SelectionHighlighter");this.oHoverHighlighter=new sap.ui.debug.Highlighter("sap-ui-testsuite-HoverHighlighter",true,'#c8f',1);var t=this;jQuery(p).bind("click",function(e){t.onclick(e)}).bind("mouseover",function(e){t.onmouseover(e)}).bind("mouseout",function(e){t.onmouseout(e)});this.enableInplaceControlSelection();this.oCore.attachUIUpdated(this.renderDelayed,this);this.sSelectedNodeId="";this.sResourcePath=r?jQuery.sap.getModulePath("","/"):(window.top.testfwk.sResourceRoot||"../");this.sTestResourcePath=this.sResourcePath+"../test-resources/";this.sSpaceUrl=this.sResourcePath+"testsuite/images/space.gif";this.sMinusUrl=this.sResourcePath+"testsuite/images/minus.gif";this.sPlusUrl=this.sResourcePath+"testsuite/images/plus.gif";this.sLinkUrl=this.sResourcePath+"testsuite/images/link.gif"}});sap.ui.debug.ControlTree.M_EVENTS={SELECT:"SELECT"};
sap.ui.debug.ControlTree.prototype.exit=function(){jQuery(document).unbind();jQuery(this.oParentDomRef).unbind()};
sap.ui.debug.ControlTree.prototype.renderDelayed=function(){if(this.oTimer){this.oWindow.jQuery.sap.clearDelayedCall(this.oTimer)}this.oTimer=this.oWindow.jQuery.sap.delayedCall(0,this,"render")};
sap.ui.debug.ControlTree.prototype.render=function(){var d=this.oParentDomRef;var u=null,U=this.oCore.mUIAreas;d.innerHTML="";for(var i in U){var u=U[i],D=this.createTreeNodeDomRef(u.getId(),0,"UIArea",this.sTestResourcePath+"sap/ui/core/images/controls/sap.ui.core.UIArea.gif");d.appendChild(D);var r=u.getContent();for(var i=0,l=r.length;i<l;i++){this.renderNode(d,r[i],1)}}};
sap.ui.debug.ControlTree.prototype.createTreeNodeDomRef=function(i,l,t,I){var d=this.oParentDomRef.ownerDocument.createElement("DIV");d.setAttribute("id","sap-debug-controltree-"+i);var s=t.substring(t.lastIndexOf(".")>-1?t.lastIndexOf(".")+1:0);d.innerHTML="<img style='height:12px;width:12px;display:none' src='"+this.sSpaceUrl+"' align='absmiddle'/><img style='height:16px;width:16px' src='"+I+"' align='absmiddle'/>&nbsp;<span>"+s+" - "+i+"</span>";d.style.overflow="hidden";d.style.whiteSpace="nowrap";d.style.textOverflow="ellipsis";d.style.paddingLeft=(l*16)+"px";d.style.height="20px";d.style.cursor="default";d.setAttribute("sap-type",t);d.setAttribute("sap-id",i);d.setAttribute("sap-expanded","true");d.setAttribute("sap-level",""+l);d.title=t+" - "+i;return d};
sap.ui.debug.ControlTree.prototype.createLinkNode=function(p,i,l,t){var d=this.oParentDomRef.ownerDocument.createElement("DIV");d.setAttribute("id","sap-debug-controltreelink-"+i);var s=t?t.substring(t.lastIndexOf(".")>-1?t.lastIndexOf(".")+1:0):"";d.innerHTML="<img style='height:12px;width:12px;display:none' src='"+this.sSpaceUrl+"' align='absmiddle'/><img style='height:12px;width:12px' src='"+this.sLinkUrl+"' align='absmiddle'/>&nbsp;<span style='color:#888;border-bottom:1px dotted #888;'>"+(s?s+" - ":"")+i+"</span>";d.style.overflow="hidden";d.style.whiteSpace="nowrap";d.style.textOverflow="ellipsis";d.style.paddingLeft=(l*16)+"px";d.style.height="20px";d.style.cursor="default";d.setAttribute("sap-type","Link");d.setAttribute("sap-id",i);d.setAttribute("sap-expanded","true");d.setAttribute("sap-level",""+l);d.title="Association to '"+i+"'";p.appendChild(d);return d};
sap.ui.debug.ControlTree.prototype.renderNode=function(d,c,l){if(!c){return}var m=c.getMetadata();var I=this.sTestResourcePath+m.getLibraryName().replace(/\./g,"/")+"/images/controls/"+m.getName()+".gif";var D=this.createTreeNodeDomRef(c.getId(),l,m.getName(),I);d.appendChild(D);var r=false;if(c.mAggregations){for(var n in c.mAggregations){r=true;var a=c.mAggregations[n];if(a&&a.length){for(var i=0;i<a.length;i++){var o=a[i];if(o instanceof sap.ui.core.Element){this.renderNode(d,a[i],l+1)}}}else if(a instanceof sap.ui.core.Element){this.renderNode(d,a,l+1)}}}if(c.mAssociations){for(var n in c.mAssociations){r=true;var A=c.mAssociations[n];if(jQuery.isArray(A)){for(var i=0;i<A.length;i++){var o=A[i];if(typeof o==="string"){this.createLinkNode(d,o,l+1)}}}else if(typeof A==="string"){this.createLinkNode(d,A,l+1)}}}if(r){var e=D.getElementsByTagName("IMG")[0];e.src=this.sMinusUrl;e.style.display=""}};
sap.ui.debug.ControlTree.prototype.onclick=function(e){var s=e.target;if(s.tagName=="IMG"){var p=s.parentNode,l=parseInt(p.getAttribute("sap-level"),10),n=p.nextSibling,E=p.getAttribute("sap-expanded")=="true";s=p.firstChild;if(n){var N=parseInt(n.getAttribute("sap-level"),10);while(n&&N>l){var o=n.getElementsByTagName("IMG")[0];if(E){n.style.display="none";n.setAttribute("sap-expanded","false");if(o&&o.src!==this.sSpaceUrl){o.src=this.sPlusUrl}}else{n.style.display="block";n.setAttribute("sap-expanded","true");if(o&&o.src!==this.sSpaceUrl){o.src=this.sMinusUrl}}n=n.nextSibling;if(n){N=parseInt(n.getAttribute("sap-level"),10)}}}if(E){s.src=this.sPlusUrl;p.setAttribute("sap-expanded","false")}else{s.src=this.sMinusUrl;p.setAttribute("sap-expanded","true")}}else if(s.getAttribute("sap-type")=="UIArea"){}else{if(s.tagName!="SPAN"){s=s.getElementsByTagName("SPAN")[0]}var p=s.parentNode,i=p.getAttribute("sap-id"),a=this.oCore.getElementById(i),b=p.getAttribute("sap-type")==="Link"?"sap-debug-controltree-"+i:p.id;this.oSelectionHighlighter.hide();if(a&&a instanceof sap.ui.core.Element){this.oSelectionHighlighter.highlight(a.getDomRef());this.oHoverHighlighter.hide()}this.deselectNode(this.sSelectedNodeId);this.selectNode(b)}};
sap.ui.debug.ControlTree.prototype.onmouseover=function(e){var s=e.target;if(s.tagName=="SPAN"){this.oHoverHighlighter.highlight(this.getTargetDomRef(s.parentNode))}};
sap.ui.debug.ControlTree.prototype.onmouseout=function(e){var s=e.target;if(s.tagName=="SPAN"){if(this.getTargetDomRef(s.parentNode)){this.oHoverHighlighter.hide()}}};
sap.ui.debug.ControlTree.prototype.selectNode=function(i){if(!i){return}var d=jQuery.sap.domById(i,jQuery.sap.ownerWindow(this.oParentDomRef));if(!d){jQuery.sap.log.warning("Control with Id '"+i.substring(22)+"' not found in tree");return}var c=d.getAttribute("sap-id");var s=d.getElementsByTagName("SPAN")[0];s.style.backgroundColor="#000066";s.style.color="#FFFFFF";this.sSelectedNodeId=i;this.fireEvent(sap.ui.debug.ControlTree.M_EVENTS.SELECT,{id:i,controlId:c})};
sap.ui.debug.ControlTree.prototype.deselectNode=function(i){if(!i){return}var d=jQuery.sap.domById(i,jQuery.sap.ownerWindow(this.oParentDomRef));var s=d.getElementsByTagName("SPAN")[0];s.style.backgroundColor="transparent";s.style.color="#000000";this.sSelectedNodeId=i};
sap.ui.debug.ControlTree.prototype.getTargetDomRef=function(t){var T=t.getAttribute("sap-type"),i=t.getAttribute("sap-id"),s=T==="UIArea"?this.oCore.getUIArea(i):this.oCore.getElementById(i);while(s&&s instanceof sap.ui.core.Element){var d=s.getDomRef();if(d){return d}s=s.getParent()}if(s instanceof sap.ui.core.UIArea){return s.getRootNode()}};
sap.ui.debug.ControlTree.prototype.enableInplaceControlSelection=function(){var t=this;jQuery(document).bind("mouseover",function(e){t.selectControlInTree(e)})};
sap.ui.debug.ControlTree.prototype.selectControlInTree=function(e){if(e){if(e.ctrlKey&&e.shiftKey&&!e.altKey){var c=e.srcElement||e.target;while(c&&(!c.id||!this.oCore.getControl(c.id))){c=c.parentNode}if(c&&c.id&&this.oCore.getControl(c.id)){this.oHoverHighlighter.highlight(c)}else{this.oHoverHighlighter.hide()}}else{this.oHoverHighlighter.hide()}}};
