/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.ui.commons.Carousel");jQuery.sap.require("sap.ui.commons.library");jQuery.sap.require("sap.ui.core.Control");sap.ui.core.Control.extend("sap.ui.commons.Carousel",{metadata:{publicMethods:["showNext","showPrevious","showElementWithId"],library:"sap.ui.commons",properties:{"orientation":{type:"sap.ui.commons.enums.Orientation",group:"Misc",defaultValue:sap.ui.commons.enums.Orientation.horizontal},"width":{type:"sap.ui.core.CSSSize",group:"Misc",defaultValue:null},"height":{type:"sap.ui.core.CSSSize",group:"Misc",defaultValue:null},"defaultItemHeight":{type:"int",group:"Misc",defaultValue:150},"defaultItemWidth":{type:"int",group:"Misc",defaultValue:150},"animationDuration":{type:"int",group:"Misc",defaultValue:500},"visibleItems":{type:"int",group:"Misc",defaultValue:null},"handleSize":{type:"int",group:"Misc",defaultValue:22}},defaultAggregation:"content",aggregations:{"content":{type:"sap.ui.core.Control",multiple:true,singularName:"content",bindable:"bindable"}}}});jQuery.sap.require("sap.ui.core.ResizeHandler");
sap.ui.commons.Carousel.prototype.init=function(){var m=this;m.startTouchX=undefined;m.startTouchY=undefined;m.scrollDelta=undefined;m._visibleItems=0;m._bTouchNotMoved=true;if(jQuery.sap.touchEventMode!="OFF"){var t=function(e){e.preventDefault();m.startTouchX=e.touches[0].pageX;m.startTouchY=e.touches[0].pageY;m._bTouchNotMoved=true};var T=function(e){e.preventDefault();var d=e.touches[0].pageX-m.startTouchX;var a=e.touches[0].pageY-m.startTouchY;if(m.getOrientation()=="horizontal"){m.scrollDelta=-d}else{m.scrollDelta=-a}m._bTouchNotMoved=false};var f=function(e){e.preventDefault();if(!m._bTouchNotMoved){if(m.scrollDelta>0){m.showNext()}else{m.showPrevious()}m.startTouchX=undefined;m.startTouchY=undefined;m.scrollDelta=undefined}};this.ontouchstart=t;this.ontouchend=f;this.ontouchmove=T}};
sap.ui.commons.Carousel.prototype.exit=function(){if(this.sResizeListenerId){sap.ui.core.ResizeHandler.deregister(this.sResizeListenerId);this.sResizeListenerId=null}};
sap.ui.commons.Carousel.prototype.onclick=function(e){var c=this.getId();switch(e.target){case jQuery.sap.byId(c+'-prevbutton')[0]:this.showPrevious();break;case jQuery.sap.byId(c+'-nextbutton')[0]:this.showNext();break;default:return}jQuery.sap.byId(c+'-contentarea').focus()};
sap.ui.commons.Carousel.prototype.onBeforeRendering=function(){if(this.sResizeListenerId){sap.ui.core.ResizeHandler.deregister(this.sResizeListenerId);this.sResizeListenerId=null}};
sap.ui.commons.Carousel.prototype.onAfterRendering=function(){if(this.getOrientation()=="vertical"){this._sAnimationAttribute='margin-top'}else{if(sap.ui.getCore().getConfiguration().getRTL()){this._sAnimationAttribute='margin-right'}else{this._sAnimationAttribute='margin-left'}}this.calculateAndSetSize();if(this._firstItem){this.showElementWithId(this._firstItem)}this.oDomRef=this.getDomRef();this.sResizeListenerId=sap.ui.core.ResizeHandler.register(this.oDomRef,jQuery.proxy(this.onresize,this))};
sap.ui.commons.Carousel.prototype.onsapnext=function(e){this.showNext()};
sap.ui.commons.Carousel.prototype.onsapprevious=function(e){this.showPrevious()};
sap.ui.commons.Carousel.prototype.onresize=function(e){if(!this.getDomRef()){if(this.sResizeListenerId){sap.ui.core.ResizeHandler.deregister(this.sResizeListenerId);this.sResizeListenerId=null}return}this.calculateAndSetSize()};
sap.ui.commons.Carousel.prototype.showPrevious=function(){var a={};a[this._sAnimationAttribute]=0;var s=jQuery.sap.byId(this.getId()+'-scrolllist');var c=jQuery.sap.byId(this.getId()+'-contentarea');if(s.find('li').length<2){return}c.focus();s.css(this._sAnimationAttribute,-this._iMaxWidth);var $=s.find('li:last');var b=s.find('li:first');this._showAllItems();$.insertBefore(b);var m=this;s.stop(true,true).animate(a,this.getAnimationDuration(),function(){m._firstItem=b.attr('id');m._hideInvisibleItems()})};
sap.ui.commons.Carousel.prototype.showNext=function(){var a={};a[this._sAnimationAttribute]=-this._iMaxWidth;var s=jQuery.sap.byId(this.getId()+'-scrolllist');var c=jQuery.sap.byId(this.getId()+'-contentarea');if(s.find('li').length<2){return}c.focus();this._showAllItems();var A=this._sAnimationAttribute;var m=this;s.stop(true,true).animate(a,this.getAnimationDuration(),function(){s.find('li:first').appendTo(s);jQuery(this).css(A,'0px');m._firstItem=s.find('li:first').attr('id');m._hideInvisibleItems()})};
sap.ui.commons.Carousel.prototype.showElementWithId=function(e){var s=jQuery.sap.byId(this.getId()+'-scrolllist');var i=s.find('li').index(jQuery.sap.byId(e));s.find('li:lt('+i+')').appendTo(s)};
sap.ui.commons.Carousel.prototype.calculateAndSetSize=function(){var c=this.getContent();var C=this.getId();this._showAllItems();if(c.length>0){var m=0;var a=0;for(var i=0;i<c.length;i++){var b,d;try{b=c[i].getWidth();if(b.substr(-1)=="%"){b=this.getDefaultItemWidth()}}catch(e){b=this.getDefaultItemWidth()}try{d=c[i].getHeight();if(d.substr(-1)=="%"){d=this.getDefaultItemHeight()}}catch(e){d=this.getDefaultItemHeight()}m=Math.max(m,parseInt(b,10));a=Math.max(a,parseInt(d,10))}if(m==0||isNaN(m)){m=this.getDefaultItemWidth()}if(a==0||isNaN(a)){a=this.getDefaultItemHeight()}var f;var v=this.getVisibleItems();var M=jQuery.sap.byId(C);var n=jQuery.sap.byId(C+'-nextbutton');var p=jQuery.sap.byId(C+'-prevbutton');var $=jQuery.sap.byId(C+'-contentarea');if(this.getWidth()&&this.getOrientation()=="vertical"){m=M.width()}if(this.getHeight()&&this.getOrientation()=="horizontal"){a=M.height()}jQuery.sap.byId(this.getId()).addClass('sapUiCrsl'+jQuery.sap.charToUpperCase(this.getOrientation(),0));if(this.getOrientation()=="horizontal"){f=M.width()-this.getHandleSize()*2-1;if(v==0){v=Math.floor(f/(m+10))}m=(f/v)-10;this._iMaxWidth=m;$.find('.sapUiCrslItm').width(m).height(a);var g=a+"px";p.css("height",a).css("line-height",g);n.css("height",a).css("line-height",g);$.width(f).height(a)}else{f=M.height()-this.getHandleSize()*2-1;if(v==0){v=Math.floor(f/(a+10))}a=(f/v)-10;this._iMaxWidth=a;$.find('.sapUiCrslItm').width(m).height(a);p.width(m).after($);n.width(m);$.width(m).height(f)}this._visibleItems=v;this._hideInvisibleItems()}};
sap.ui.commons.Carousel.prototype.getFocusDomRef=function(){return this.oContentArea};
sap.ui.commons.Carousel.prototype._showAllItems=function(){var c=jQuery.sap.byId(this.getId()+'-contentarea');c.find('.sapUiCrslItm').show()};
sap.ui.commons.Carousel.prototype._hideInvisibleItems=function(){var c=jQuery.sap.byId(this.getId()+'-contentarea');c.find('.sapUiCrslItm:gt('+(this._visibleItems-1)+')').hide()};
