/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.ui.commons.TextField");jQuery.sap.require("sap.ui.commons.library");jQuery.sap.require("sap.ui.core.Control");sap.ui.core.Control.extend("sap.ui.commons.TextField",{metadata:{interfaces:["sap.ui.commons.ToolbarItem"],publicMethods:["focus","getLiveValue"],library:"sap.ui.commons",properties:{"value":{type:"string",group:"Data",defaultValue:'',bindable:"bindable"},"textDirection":{type:"sap.ui.core.TextDirection",group:"Appearance",defaultValue:sap.ui.core.TextDirection.Inherit},"enabled":{type:"boolean",group:"Behavior",defaultValue:true},"editable":{type:"boolean",group:"Behavior",defaultValue:true},"visible":{type:"boolean",group:"Behavior",defaultValue:true},"required":{type:"boolean",group:"Appearance",defaultValue:false},"width":{type:"sap.ui.core.CSSSize",group:"Dimension",defaultValue:null},"maxLength":{type:"int",group:"Behavior",defaultValue:0},"valueState":{type:"sap.ui.core.ValueState",group:"Data",defaultValue:sap.ui.core.ValueState.None},"textAlign":{type:"sap.ui.core.TextAlign",group:"Appearance",defaultValue:sap.ui.core.TextAlign.Begin},"imeMode":{type:"sap.ui.core.ImeMode",group:"Behavior",defaultValue:sap.ui.core.ImeMode.Auto},"design":{type:"sap.ui.core.Design",group:"Appearance",defaultValue:sap.ui.core.Design.Standard},"helpId":{type:"string",group:"Behavior",defaultValue:''},"accessibleRole":{type:"sap.ui.core.AccessibleRole",group:"Accessibility",defaultValue:sap.ui.core.AccessibleRole.Textbox},"name":{type:"string",group:"Misc",defaultValue:null}},associations:{"ariaDescribedBy":{type:"sap.ui.core.Control",multiple:true,singularName:"ariaDescribedBy"},"ariaLabelledBy":{type:"sap.ui.core.Control",multiple:true,singularName:"ariaLabelledBy"}},events:{"change":{},"liveChange":{}}}});sap.ui.commons.TextField.M_EVENTS={'change':'change','liveChange':'liveChange'};
sap.ui.commons.TextField.prototype.onfocusin=function(e){if(this.getEditable()&&this.getEnabled()&&this.getRenderer().onfocus){this.getRenderer().onfocus(this)}};
sap.ui.commons.TextField.prototype.onfocusout=function(e){this._doOnEscape();if(this.getEditable()&&this.getEnabled()&&this.getRenderer().onblur){this.getRenderer().onblur(this)}this._checkChange(e);var f=jQuery(this.getFocusDomRef());if(f.data("sap.InNavArea")===false){f.data("sap.InNavArea",true)}};
sap.ui.commons.TextField.prototype.onsapenter=function(e){this._checkChange(e)};
sap.ui.commons.TextField.prototype._checkChange=function(e){var i=this.getInputDomRef(),n=i&&i.value,o=this.getValue();if(this.getEditable()&&this.getEnabled()&&(o!=n)){this.setProperty("value",n,true);this.fireChange({newValue:n})}};
sap.ui.commons.TextField.prototype.onselectstart=function(e){if(!this.getEnabled()){e.preventDefault();e.stopPropagation()}};
sap.ui.commons.TextField.prototype._checkCursorPosForNav=function(e,f){var r=sap.ui.getCore().getConfiguration().getRTL();var b=f?r:!r;var $=jQuery(this.getInputDomRef());var p=$.cursorPos();var l=$.val().length;if(r){p=l-p}if((!b&&p!=l)||(b&&p!=0)){e.stopPropagation()}};
sap.ui.commons.TextField.prototype.onsapnext=function(e){if(e.keyCode!=jQuery.sap.KeyCodes.ARROW_DOWN){if(jQuery(this.getFocusDomRef()).data("sap.InNavArea")&&e.keyCode!=jQuery.sap.KeyCodes.END){e.preventDefault();return}this._checkCursorPosForNav(e,true)}};
sap.ui.commons.TextField.prototype.onsapprevious=function(e){if(e.keyCode!=jQuery.sap.KeyCodes.ARROW_UP){if(jQuery(this.getFocusDomRef()).data("sap.InNavArea")&&e.keyCode!=jQuery.sap.KeyCodes.HOME){e.preventDefault();return}this._checkCursorPosForNav(e,false)}};
sap.ui.commons.TextField.prototype.onsapnextmodifiers=sap.ui.commons.TextField.prototype.onsapnext;sap.ui.commons.TextField.prototype.onsappreviousmodifiers=sap.ui.commons.TextField.prototype.onsapprevious;sap.ui.commons.TextField.prototype.onsapend=sap.ui.commons.TextField.prototype.onsapnext;sap.ui.commons.TextField.prototype.onsaphome=sap.ui.commons.TextField.prototype.onsapprevious;
sap.ui.commons.TextField.prototype.onsapescape=function(e){var v=this.getProperty("value");if(!jQuery.browser.mozilla){var i=this.getInputDomRef();if(i&&i.value!==v){jQuery(i).val(v)}}else{this._bEsc=true;this._sValue=v}};
sap.ui.commons.TextField.prototype.onkeypress=function(e){this._doOnEscape();var k=e.keyCode;if(!(k>=33&&k<=44)&&!(k>=112&&k<=123)&&k!==jQuery.sap.KeyCodes.ESCAPE&&k!==jQuery.sap.KeyCodes.TAB){var f=jQuery(this.getFocusDomRef());if(f.data("sap.InNavArea")){f.data("sap.InNavArea",false)}}};
sap.ui.commons.TextField.prototype._doOnEscape=function(){if(this._bEsc){var i=this.getInputDomRef();if(i&&i.value!==this._sValue){jQuery(i).val(this._sValue)}this._bEsc=undefined;this._sValue=undefined}};
sap.ui.commons.TextField.prototype.onkeyup=function(e){if(e.keyCode==jQuery.sap.KeyCodes.F2){var f=jQuery(this.getFocusDomRef());if(f.data("sap.InNavArea")){f.data("sap.InNavArea",false)}else if(f.data("sap.InNavArea")===false){f.data("sap.InNavArea",true)}}else{this._fireLiveChange(e)}};
sap.ui.commons.TextField.prototype.onpaste=function(e){var t=this;setTimeout(function(){t._fireLiveChange(e)},10)};
sap.ui.commons.TextField.prototype._fireLiveChange=function(e){if(this.getEnabled()&&this.getEditable()){var l=jQuery(this.getInputDomRef()).val();this.fireLiveChange({liveValue:l})}};
sap.ui.commons.TextField.prototype.setValueState=function(v){var o=this.getValueState();if(o==v){return this}this.setProperty("valueState",v,true);if(!this.getDomRef()){return this}if(this.getRenderer().setValueState){this.getRenderer().setValueState(this,o,v)}if(this.delayedCallId){jQuery.sap.clearDelayedCall(this.delayedCallId);this.delayedCallId=null}if(sap.ui.core.ValueState.Success==v){this.delayedCallId=jQuery.sap.delayedCall(3000,this,"removeValidVisualization")}return this};
sap.ui.commons.TextField.prototype.removeValidVisualization=function(){if(this.getRenderer().removeValidVisualization){this.getRenderer().removeValidVisualization(this)}};
sap.ui.commons.TextField.prototype.setEditable=function(e){if(e!=this.getEditable()){this.setProperty('editable',e,true);if(this.getDomRef()&&this.getRenderer().setEditable){this.getRenderer().setEditable(this,e)}}return this};
sap.ui.commons.TextField.prototype.setEnabled=function(e){if(e!=this.getEnabled()){this.setProperty('enabled',e,true);if(this.getDomRef()&&this.getRenderer().setEnabled){this.getRenderer().setEnabled(this,e)}}return this};
sap.ui.commons.TextField.prototype.setRequired=function(r){if(r!=this.getRequired()){this.setProperty('required',r,true);if(this.getDomRef()){if(this.getRenderer().setRequired){this.getRenderer().setRequired(this,r)}}}return this};
sap.ui.commons.TextField.prototype.setDesign=function(d){if(d!=this.getDesign()){this.setProperty('design',d,true);if(this.getDomRef()){if(this.getRenderer().setDesign){this.getRenderer().setDesign(this,d)}}}return this};
sap.ui.commons.TextField.prototype.setValue=function(v){var n=v;if(n&&n.length>this.getMaxLength()&&this.getMaxLength()>0){n=n.substring(0,this.getMaxLength())}this.setProperty("value",n,true);var i=this.getInputDomRef();if(i&&i.value!==n){i.value=this.getValue()}return this};
sap.ui.commons.TextField.prototype.getInputDomRef=function(){return this.getFocusDomRef()};
sap.ui.commons.TextField.prototype.applyFocusInfo=function(f){if(jQuery.browser.msie&&jQuery.browser.version==8){var p=this.getValue().length;var t=this;setTimeout(function(){t.focus();jQuery(t.getFocusDomRef()).cursorPos(p)},0)}else{this.focus()}return this};
sap.ui.commons.TextField.prototype.getLiveValue=function(){var i=this.getInputDomRef();if(i){return jQuery(i).val()}else{return this.getValue()}};
