/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.ui.core.delegate.ItemNavigation");jQuery.sap.require("sap.ui.base.EventProvider");sap.ui.base.EventProvider.extend("sap.ui.core.delegate.ItemNavigation",{constructor:function(d,i,n){sap.ui.base.EventProvider.apply(this);this.oDomRef=null;if(d){this.setRootDomRef(d)}this.aItemDomRefs=[];if(i){this.setItemDomRefs(i)}this.iTabIndex=-1;this.iActiveTabIndex=!!n?-1:0;this.iFocusedIndex=-1;this.iSelectedIndex=-1;this.bCycling=true;this.bTableMode=false;this.iPageSize=-1;this._bMouseDownHappened=false}});sap.ui.core.delegate.ItemNavigation.Events={BeforeFocus:"BeforeFocus",AfterFocus:"AfterFocus"};
sap.ui.core.delegate.ItemNavigation.prototype.setRootDomRef=function(d){this.oDomRef=d;if(!jQuery(this.oDomRef).data("sap.INItem")){if(this.iFocusedIndex>=0){jQuery(this.oDomRef).attr("tabIndex",this.iTabIndex)}else{jQuery(this.oDomRef).attr("tabIndex",this.iActiveTabIndex)}}jQuery(this.oDomRef).data("sap.INRoot",this);return this};
sap.ui.core.delegate.ItemNavigation.prototype.getRootDomRef=function(){return this.oDomRef};
sap.ui.core.delegate.ItemNavigation.prototype.getItemDomRefs=function(){return this.aItemDomRefs};
sap.ui.core.delegate.ItemNavigation.prototype.setItemDomRefs=function(I){this.aItemDomRefs=I;for(var i=0;i<this.aItemDomRefs.length;i++){if(this.aItemDomRefs[i]){var $=jQuery(this.aItemDomRefs[i]);if(i==this.iFocusedIndex&&!$.data("sap.INRoot")){$.attr("tabIndex",this.iActiveTabIndex)}else if($.attr("tabindex")=="0"){$.attr("tabIndex",-1)}$.data("sap.INItem",true);$.data("sap.InNavArea",true);if($.data("sap.INRoot")&&i!=this.iFocusedIndex){$.data("sap.INRoot").setNestedItemsTabindex()}}}return this};
sap.ui.core.delegate.ItemNavigation.prototype.setItemsTabindex=function(){for(var i=0;i<this.aItemDomRefs.length;i++){if(this.aItemDomRefs[i]){var I=jQuery(this.aItemDomRefs[i]);if(I.is(":sapFocusable")){if(i==this.iFocusedIndex&&!I.data("sap.INRoot")){I.attr("tabIndex",this.iActiveTabIndex)}else{I.attr("tabIndex",-1)}}}}return this};
sap.ui.core.delegate.ItemNavigation.prototype.setNestedItemsTabindex=function(){if(jQuery(this.oDomRef).data("sap.INItem")){for(var i=0;i<this.aItemDomRefs.length;i++){if(this.aItemDomRefs[i]&&jQuery(this.aItemDomRefs[i]).attr("tabindex")=="0"){jQuery(this.aItemDomRefs[i]).attr("tabIndex",-1)}}}return this};
sap.ui.core.delegate.ItemNavigation.prototype.destroy=function(){if(this.oDomRef){jQuery(this.oDomRef).removeData("sap.INRoot");this.oDomRef=null}if(this.aItemDomRefs){for(var i=0;i<this.aItemDomRefs.length;i++){if(this.aItemDomRefs[i]){jQuery(this.aItemDomRefs[i]).removeData("sap.INItem");jQuery(this.aItemDomRefs[i]).removeData("sap.InNavArea")}}this.aItemDomRefs=null}this._bItemTabIndex=undefined};
sap.ui.core.delegate.ItemNavigation.prototype.setCycling=function(c){this.bCycling=c;return this};
sap.ui.core.delegate.ItemNavigation.prototype.setTableMode=function(t){this.bTableMode=t;return this};
sap.ui.core.delegate.ItemNavigation.prototype.setPageSize=function(p){this.iPageSize=p;return this};
sap.ui.core.delegate.ItemNavigation.prototype.setSelectedIndex=function(i){this.iSelectedIndex=i;return this};
sap.ui.core.delegate.ItemNavigation.prototype.setColumns=function(c){this.iColumns=c;return this};
sap.ui.core.delegate.ItemNavigation.prototype.focusItem=function(i,e){jQuery.sap.log.info('FocusItem: '+i+' iFocusedIndex: '+this.iFocusedIndex,'focusItem','ItemNavigation');if(i==this.iFocusedIndex&&this.aItemDomRefs[this.iFocusedIndex]==document.activeElement){return}if(!this.aItemDomRefs[i]||!jQuery(this.aItemDomRefs[i]).is(":sapFocusable")){return}this.fireEvent(sap.ui.core.delegate.ItemNavigation.Events.BeforeFocus,{index:i,event:e});this.setFocusedIndex(i);this.bISetFocus=true;if(jQuery(this.aItemDomRefs[this.iFocusedIndex]).data("sap.INRoot")&&e){var I=jQuery(this.aItemDomRefs[this.iFocusedIndex]).data("sap.INRoot");I._sFocusEvent=e.type}jQuery.sap.log.info('Set Focus on ID: '+this.aItemDomRefs[this.iFocusedIndex].id,'focusItem','ItemNavigation');jQuery.sap.focus(this.aItemDomRefs[this.iFocusedIndex]);this.fireEvent(sap.ui.core.delegate.ItemNavigation.Events.AfterFocus,{index:i,event:e})};
sap.ui.core.delegate.ItemNavigation.prototype.setFocusedIndex=function(i){if(i<0){i=0}if(i>this.aItemDomRefs.length-1){i=this.aItemDomRefs.length-1}var I;jQuery(this.oDomRef).attr("tabIndex",this.iTabIndex);if(this.iFocusedIndex!==-1&&this.aItemDomRefs.length>this.iFocusedIndex){jQuery(this.aItemDomRefs[this.iFocusedIndex]).attr("tabIndex",-1);I=jQuery(this.aItemDomRefs[this.iFocusedIndex]);if(I.data("sap.INRoot")&&i!=this.iFocusedIndex){jQuery(I.data("sap.INRoot").aItemDomRefs[I.data("sap.INRoot").iFocusedIndex]).attr("tabIndex",-1)}}this.iFocusedIndex=i;var f=this.aItemDomRefs[this.iFocusedIndex];I=jQuery(this.aItemDomRefs[this.iFocusedIndex]);if(!I.data("sap.INRoot")){jQuery(f).attr("tabIndex",this.iActiveTabIndex)}return this};
sap.ui.core.delegate.ItemNavigation.prototype.getFocusedDomRef=function(){return this.aItemDomRefs[this.iFocusedIndex]};
sap.ui.core.delegate.ItemNavigation.prototype.getFocusedIndex=function(){return this.iFocusedIndex};
sap.ui.core.delegate.ItemNavigation.prototype.onfocusin=function(e){var s=e.target;if(s==this.oDomRef){if(!this._bItemTabIndex){this.setItemsTabindex();this._bItemTabIndex=true}if(this._bMouseDownHappened){return}var I;if(jQuery(this.oDomRef).data("sap.INItem")&&this._sFocusEvent&&!jQuery(this.oDomRef).data("sap.InNavArea")){switch(this._sFocusEvent){case"sapnext":I=0;break;case"sapprevious":I=this.aItemDomRefs.length-1;break;default:I=this.iSelectedIndex!=-1?this.iSelectedIndex:(this.iFocusedIndex!=-1?this.iFocusedIndex:0);break}this._sFocusEvent=undefined}else{I=this.iSelectedIndex!=-1?this.iSelectedIndex:(this.iFocusedIndex!=-1?this.iFocusedIndex:0)}this.focusItem(I,e);if(this.iFocusedIndex==-1){for(var i=I+1;i<this.aItemDomRefs.length;i++){this.focusItem(i,e);if(this.iFocusedIndex==i){break}}if(this.iFocusedIndex==-1&&I>0){for(var i=I-1;i>=0;i--){this.focusItem(i,e);if(this.iFocusedIndex==i){break}}}}e.preventDefault();e.stopPropagation()}else if(!this.bISetFocus){if(this.aItemDomRefs&&e.target!=this.aItemDomRefs[this.iFocusedIndex]){for(var i=0;i<this.aItemDomRefs.length;i++){if(e.target==this.aItemDomRefs[i]){this.focusItem(i,e);break}}}else{this.fireEvent(sap.ui.core.delegate.ItemNavigation.Events.AfterFocus,{index:this.iFocusedIndex,event:e})}}this.bISetFocus=false};
sap.ui.core.delegate.ItemNavigation.prototype.onsapfocusleave=function(e){if(!e.relatedControlId||!jQuery.sap.containsOrEquals(this.oDomRef,sap.ui.getCore().byId(e.relatedControlId).getFocusDomRef())){this.setFocusedIndex(this.iSelectedIndex!=-1?this.iSelectedIndex:(this.iFocusedIndex!=-1?this.iFocusedIndex:0));if(jQuery(this.oDomRef).data("sap.INItem")){var p;var d=jQuery(this.oDomRef);while(!p){d=d.parent();if(d.data("sap.INRoot")){p=d.get(0)}}if(!e.relatedControlId||jQuery.sap.containsOrEquals(p,sap.ui.getCore().byId(e.relatedControlId).getFocusDomRef())){jQuery(this.aItemDomRefs[this.iFocusedIndex]).attr("tabIndex",-1)}}var d=jQuery(this.oDomRef);if(d.data("sap.InNavArea")===false){d.data("sap.InNavArea",true)}}};
sap.ui.core.delegate.ItemNavigation.prototype.onmousedown=function(e){var s=e.target;if(jQuery.sap.containsOrEquals(this.oDomRef,s)){for(var i=0;i<this.aItemDomRefs.length;i++){var I=this.aItemDomRefs[i];if(jQuery.sap.containsOrEquals(I,s)){if(!this.bTableMode){this.focusItem(i,e)}else{if(I===s||!jQuery(s).is(":sapFocusable")){this.focusItem(i,e)}}return}}if(s==this.oDomRef){this._bMouseDownHappened=true;var t=this;window.setTimeout(function(){t._bMouseDownHappened=false},20)}}};
sap.ui.core.delegate.ItemNavigation.prototype.onsapnext=function(e){if(!jQuery.sap.containsOrEquals(this.oDomRef,e.target)){return}if(jQuery(this.oDomRef).data("sap.InNavArea")){return}if(this.bTableMode&&jQuery.inArray(e.target,this.aItemDomRefs)===-1){return}var i=this.iFocusedIndex;var f=true;if(i>-1){if(this.bTableMode){var r=this.aItemDomRefs.length/this.iColumns;var R=Math.floor(i/this.iColumns);var c=i%this.iColumns;if(e.keyCode==jQuery.sap.KeyCodes.ARROW_DOWN){if(R<r-1){i+=this.iColumns}}else{if(c<this.iColumns-1){i+=1}}}else{do{if(this.iColumns>1&&e.keyCode==jQuery.sap.KeyCodes.ARROW_DOWN){if((i+this.iColumns)>=this.aItemDomRefs.length){if((i%this.iColumns)<(this.iColumns-1)){i=(i%this.iColumns)+1}else if(this.bCycling){i=0}}else{i=i+this.iColumns}}else{if(i==this.aItemDomRefs.length-1){if(jQuery(this.oDomRef).data("sap.INItem")){return}else if(this.bCycling){i=0}else{i=this.iFocusedIndex}}else{i++}}if(i==this.iFocusedIndex){if(f){f=false}else{throw new Error("ItemNavigation has no visible/existing items and is hence unable to select the next one")}}}while(!this.aItemDomRefs[i]||!jQuery(this.aItemDomRefs[i]).is(":visible")||jQuery(this.aItemDomRefs[i]).css('visibility')=='hidden'||!jQuery(this.aItemDomRefs[i]).is(":sapFocusable"))}this.focusItem(i,e);e.preventDefault();e.stopPropagation()}};
sap.ui.core.delegate.ItemNavigation.prototype.onsapnextmodifiers=sap.ui.core.delegate.ItemNavigation.prototype.onsapnext;
sap.ui.core.delegate.ItemNavigation.prototype.onsapprevious=function(e){if(!jQuery.sap.containsOrEquals(this.oDomRef,e.target)){return}if(jQuery(this.oDomRef).data("sap.InNavArea")){return}if(this.bTableMode&&jQuery.inArray(e.target,this.aItemDomRefs)===-1){return}var i=this.iFocusedIndex;var f=true;if(i>-1){if(this.bTableMode){var r=this.aItemDomRefs.length/this.iColumns;var R=Math.floor(i/this.iColumns);var c=i%this.iColumns;if(e.keyCode==jQuery.sap.KeyCodes.ARROW_UP){if(R>0){i-=this.iColumns}}else{if(c>0){i-=1}}}else{do{if(this.iColumns>1&&e.keyCode==jQuery.sap.KeyCodes.ARROW_UP){if((i-this.iColumns)<0){var c=0;if((i%this.iColumns)>0){c=(i%this.iColumns)-1}else if(this.bCycling){c=this.iColumns-1}if(i===0&&c===0){i=0}else{var a=Math.ceil(this.aItemDomRefs.length/this.iColumns);i=c+((a-1)*this.iColumns);if(i>=this.aItemDomRefs.length){i=i-this.iColumns}}}else{i=i-this.iColumns}}else{if(i==0){if(jQuery(this.oDomRef).data("sap.INItem")){return}else if(this.bCycling){i=this.aItemDomRefs.length-1}else{i=this.iFocusedIndex}}else{i--}}if(i==this.iFocusedIndex){if(f){f=false}else{throw new Error("ItemNavigation has no visible/existing items and is hence unable to select the previous one")}}}while(!this.aItemDomRefs[i]||!jQuery(this.aItemDomRefs[i]).is(":visible")||jQuery(this.aItemDomRefs[i]).css('visibility')=='hidden'||!jQuery(this.aItemDomRefs[i]).is(":sapFocusable"))}this.focusItem(i,e);e.preventDefault();e.stopPropagation()}};
sap.ui.core.delegate.ItemNavigation.prototype.onsappreviousmodifiers=sap.ui.core.delegate.ItemNavigation.prototype.onsapprevious;
sap.ui.core.delegate.ItemNavigation.prototype.onsappageup=function(e){if(!jQuery.sap.containsOrEquals(this.oDomRef,e.target)){return}if(this.bTableMode&&jQuery.inArray(e.target,this.aItemDomRefs)===-1){return}if(this.iPageSize>0){var i=this.iFocusedIndex;if(i>-1){i=i-this.iPageSize;while(i>0&&!jQuery(this.aItemDomRefs[i]).is(":sapFocusable")){i--}if(i<0){i=0}this.focusItem(i,e)}}else if(this.bTableMode){var i=this.iFocusedIndex%this.iColumns;this.focusItem(i,e)}e.preventDefault();e.stopPropagation()};
sap.ui.core.delegate.ItemNavigation.prototype.onsappagedown=function(e){if(!jQuery.sap.containsOrEquals(this.oDomRef,e.target)){return}if(this.bTableMode&&jQuery.inArray(e.target,this.aItemDomRefs)===-1){return}if(this.bTableMode){var r=this.aItemDomRefs.length/this.iColumns;var c=this.iFocusedIndex%this.iColumns;i=(r-1)*this.iColumns+c;this.focusItem(i,e)}else{if(this.iPageSize>0){var i=this.iFocusedIndex;if(i>-1){i=i+this.iPageSize;while(i<this.aItemDomRefs.length-1&&!jQuery(this.aItemDomRefs[i]).is(":sapFocusable")){i++}if(i>this.aItemDomRefs.length-1){i=this.aItemDomRefs.length-1}this.focusItem(i,e)}}}e.preventDefault();e.stopPropagation()};
sap.ui.core.delegate.ItemNavigation.prototype.onsaphome=function(e){if(!jQuery.sap.containsOrEquals(this.oDomRef,e.target)||e.shiftKey||e.altKey){return}if(this.bTableMode&&jQuery.inArray(e.target,this.aItemDomRefs)===-1){return}var i=0;if(this.bTableMode){if(!(e.metaKey||e.ctrlKey)){var r=this.aItemDomRefs.length/this.iColumns;var R=Math.floor(this.iFocusedIndex/this.iColumns);i=R*this.iColumns}}else{if(!!(e.metaKey||e.ctrlKey)){return}while(!this.aItemDomRefs[i]||!jQuery(this.aItemDomRefs[i]).is(":visible")||jQuery(this.aItemDomRefs[i]).css('visibility')=='hidden'||!jQuery(this.aItemDomRefs[i]).is(":sapFocusable")){i++;if(i==this.aItemDomRefs.length){return}}}this.focusItem(i,e);e.preventDefault();e.stopPropagation()};
sap.ui.core.delegate.ItemNavigation.prototype.onsaphomemodifiers=sap.ui.core.delegate.ItemNavigation.prototype.onsaphome;
sap.ui.core.delegate.ItemNavigation.prototype.onsapend=function(e){if(!jQuery.sap.containsOrEquals(this.oDomRef,e.target)||e.shiftKey||e.altKey){return}if(this.bTableMode&&jQuery.inArray(e.target,this.aItemDomRefs)===-1){return}var i=this.aItemDomRefs.length-1;if(this.bTableMode){if(!(e.metaKey||e.ctrlKey)){var r=this.aItemDomRefs.length/this.iColumns;var R=Math.floor(this.iFocusedIndex/this.iColumns);i=R*this.iColumns+this.iColumns-1}}else{if(!!(e.metaKey||e.ctrlKey)){return}while(!this.aItemDomRefs[i]||!jQuery(this.aItemDomRefs[i]).is(":visible")||jQuery(this.aItemDomRefs[i]).css('visibility')=='hidden'||!jQuery(this.aItemDomRefs[i]).is(":sapFocusable")){i--;if(i<0){return}}}this.focusItem(i,e);e.preventDefault();e.stopPropagation()};
sap.ui.core.delegate.ItemNavigation.prototype.onsapendmodifiers=sap.ui.core.delegate.ItemNavigation.prototype.onsapend;
sap.ui.core.delegate.ItemNavigation.prototype.setTabIndex0=function(){this.iTabIndex=0;this.iActiveTabIndex=0};
sap.ui.core.delegate.ItemNavigation.prototype.onkeyup=function(e){if(e.keyCode==jQuery.sap.KeyCodes.F2){var d=jQuery(this.oDomRef);if(d.data("sap.InNavArea")){d.data("sap.InNavArea",false)}else if(d.data("sap.InNavArea")===false){d.data("sap.InNavArea",true)}e.preventDefault();e.stopPropagation()}};
