/*!
 * (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.ca.ui.model.format.FormatHelper");jQuery.sap.require("sap.ui.core.format.NumberFormat");jQuery.sap.require("sap.ui.core.LocaleData");sap.ui.base.Object.extend("sap.ca.ui.model.format.FormatHelper",{});
sap.ca.ui.model.format.FormatHelper.stringToNumeric=function(s){var h=/^\s*[\+-]?0[xX]/;if(h.test(s)){return parseInt(s,16)}else{return parseFloat(s)}};
sap.ca.ui.model.format.FormatHelper.toNumeric=function(o){if((o===null)||(o===undefined)){return NaN}var t=typeof o;var r;switch(t){case"number":r=o;break;case"string":r=sap.ca.ui.model.format.FormatHelper.stringToNumeric(o);break;case"object":var v=o.valueOf();if(typeof v==="number"){r=v}else if(Array.isArray(o)){r=NaN}else{r=sap.ca.ui.model.format.FormatHelper.stringToNumeric(o.toString())}break;default:r=NaN;break}return r};
sap.ca.ui.model.format.FormatHelper.isNumeric=function(o){return isFinite(sap.ca.ui.model.format.FormatHelper.toNumeric(o))};
sap.ca.ui.model.format.FormatHelper.getFormatOptions=function(o,l){var f={};f.locale=l;var t=typeof o;switch(t){case"number":f.decimals=o;break;case"object":if(typeof o.locale==="string"){f.locale=new sap.ui.core.Locale(o.locale)}else if(o.locale){f.locale=o.locale}f.decimals=o.decimals;f.rounding=o.rounding;f.formatStyle=o.formatStyle;f.shortDecimals=o.shortDecimals;f.shortRounding=o.shortRounding;break}if(!f.locale){if(sap.ui.getCore().getConfiguration().getLanguage()=="ZH"){f.locale=new sap.ui.core.Locale("zh_CN")}else{f.locale=sap.ui.getCore().getConfiguration().getFormatSettings().getFormatLocale()}}return f};
sap.ca.ui.model.format.FormatHelper.hasRounding=function(o){var r;if(o!==undefined){if(typeof o==="number"){r=true}else{if(o.formatStyle==="short"){r=(o.shortDecimals!==undefined)||(o.shortRounding!==undefined)}else{r=(o.decimals!==undefined)||(o.rounding!==undefined)}}}else{r=false}return r};
sap.ca.ui.model.format.FormatHelper.roundNumber=function(n,o){o=o||{};var r;var R,d;if(o.formatStyle==="short"){R=o.shortRounding;d=o.shortDecimals}else{R=o.rounding;d=o.decimals}if(R){r=R(n)}else if(d!==undefined){var a;if(typeof d==="function"){a=d(n)}else{a=d}r=n.toFixed(a)}else{r=n}return r};
sap.ca.ui.model.format.FormatHelper.formatNumber=function(n,o){var a=sap.ca.ui.model.format.FormatHelper.toNumeric(n);if(!isFinite(a)){return""}var f=sap.ca.ui.model.format.FormatHelper.getFormatOptions(o);var b=sap.ui.core.format.NumberFormat.getFloatInstance({},f.locale);if(sap.ca.ui.model.format.FormatHelper.hasRounding(o)){a=sap.ca.ui.model.format.FormatHelper.roundNumber(a,f);return b.format(a)}else{return b.format(n)}};
sap.ca.ui.model.format.FormatHelper.getMagnitude=function(n){var _=[{value:1e3,suffix:"Kilo"},{value:1e6,suffix:"Mega"},{value:1e9,suffix:"Giga"},{value:1e12,suffix:"Tera"},{value:1e15,suffix:"Peta"},{value:1e18,suffix:"Exa"},{value:1e21,suffix:"Zetta"},{value:1e24,suffix:"Yotta"}];var a=(n>=0?n:-n);for(var i=_.length-1;i>=0;--i){var m=_[i];if(a>=m.value){return m}}return{value:1,suffix:""}};
