/*!
 * SAP UI development toolkit for HTML5 (SAPUI5) (c) Copyright 2009-2012 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.suite.ui.commons.FacetOverview");jQuery.sap.require("sap.suite.ui.commons.library");jQuery.sap.require("sap.ui.core.Control");sap.ui.core.Control.extend("sap.suite.ui.commons.FacetOverview",{metadata:{library:"sap.suite.ui.commons",properties:{"title":{type:"string",group:"Misc",defaultValue:null},"quantity":{type:"int",group:"Misc",defaultValue:-1},"width":{type:"sap.ui.core.CSSSize",group:"Misc",defaultValue:'auto'},"height":{type:"sap.ui.core.CSSSize",group:"Misc",defaultValue:'10rem'},"rowSpan":{type:"int",group:"Misc",defaultValue:1}},aggregations:{"content":{type:"sap.ui.core.Control",multiple:false}},events:{"press":{}}}});sap.suite.ui.commons.FacetOverview.M_EVENTS={'press':'press'};jQuery.sap.require("sap.ui.core.IconPool");
sap.suite.ui.commons.FacetOverview.prototype.init=function(){this._rb=sap.ui.getCore().getLibraryResourceBundle("sap.suite.ui.commons");if(jQuery.device.is.desktop){this._oHoverIcon=sap.ui.core.IconPool.createControlByURI({id:this.getId()+"-hover-icon-img",src:"sap-icon://slim-arrow-right"})}this._oNoDataLabel=new sap.m.Label(this.getId()+"-no-content",{text:this._rb.getText("FACETOVERVIEW_NO_CONTENT_TEXT")}).addStyleClass("sapSuiteFovNoContent")};
sap.suite.ui.commons.FacetOverview.prototype.exit=function(){if(this._oHoverIcon){this._oHoverIcon.destroy()}sap.ui.core.ResizeHandler.deregister(this._sTitleResizeHandlerId);this._oNoDataLabel.destroy()};
sap.suite.ui.commons.FacetOverview.prototype._handleTitleResize=function(){var t=jQuery.sap.byId(this.getId()+"-title").width();if(this._iTitleWidth!=t){var T=t-jQuery.sap.byId(this.getId()+"-qty").outerWidth()-jQuery.sap.byId(this.getId()+"-hover-icon").outerWidth();jQuery.sap.byId(this.getId()+"-title-text").css("max-width",T);this._iTitleWidth=t}};
sap.suite.ui.commons.FacetOverview.prototype.onAfterRendering=function(){if(this._sTitleResizeHandlerId){sap.ui.core.ResizeHandler.deregister(this._sTitleResizeHandlerId)}var t=jQuery.sap.domById(this.getId()+"-title");this._sTitleResizeHandlerId=sap.ui.core.ResizeHandler.register(t,jQuery.proxy(this._handleTitleResize,this));this._handleTitleResize()};
sap.suite.ui.commons.FacetOverview.prototype.onclick=function(e){if(e.srcControl.getMetadata().getName()!="sap.m.Link"){this.firePress({id:this.getId()})}};
sap.suite.ui.commons.FacetOverview.prototype.onkeydown=function(e){if(e.which==jQuery.sap.KeyCodes.ENTER){this.onclick(e)}};
sap.suite.ui.commons.FacetOverview.prototype.onsaptouchstart=function(e){if(this.hasListeners("press")){if(e.srcControl.getMetadata().getName()!="sap.m.Link"){this.addStyleClass("sapSuiteFovSelected")}}};
sap.suite.ui.commons.FacetOverview.prototype.onsaptouchend=function(e){if(this.hasListeners("press")){this.removeStyleClass("sapSuiteFovSelected")}};
sap.suite.ui.commons.FacetOverview.prototype.ontouchstart=function(e){if(this.hasListeners("press")){if(e.srcControl.getMetadata().getName()!="sap.m.Link"){this.addStyleClass("sapSuiteFovSelected")}}};
sap.suite.ui.commons.FacetOverview.prototype.ontouchend=function(e){if(this.hasListeners("press")){this.removeStyleClass("sapSuiteFovSelected")}};
