/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.ui.model.json.JSONListBinding");jQuery.sap.require("sap.ui.model.ListBinding");sap.ui.model.ListBinding.extend("sap.ui.model.json.JSONListBinding",{constructor:function(m,p,c,s,f,P){sap.ui.model.ListBinding.apply(this,arguments);this.update()},metadata:{publicMethods:["getLength"]}});
sap.ui.model.json.JSONListBinding.prototype.getContexts=function(s,l){if(!s){s=0}if(!l){l=Math.min(this.iLength,this.oModel.iSizeLimit)}var e=Math.min(s+l,this.aIndices.length),c,C=[],p=this.oModel.resolve(this.sPath,this.oContext)+"/";for(var i=s;i<e;i++){c=this.oModel.getContext(p+this.aIndices[i]);C.push(c)}return C};
sap.ui.model.json.JSONListBinding.prototype.setContext=function(c){if(this.oContext!=c){this.oContext=c;this.update();this._fireChange()}};
sap.ui.model.json.JSONListBinding.prototype.getLength=function(){return this.iLength};
sap.ui.model.json.JSONListBinding.prototype._getLength=function(){return this.aIndices.length};
sap.ui.model.json.JSONListBinding.prototype.update=function(){var l=this.oModel._getObject(this.sPath,this.oContext);if(l&&jQuery.isArray(l)){this.oList=l.slice(0);this.updateIndices();this.applyFilter();this.applySort();this.iLength=this._getLength()}else{this.oList=null;this.aIndices=[];this.iLength=0}};
sap.ui.model.json.JSONListBinding.prototype.checkUpdate=function(f){var l=this.oModel._getObject(this.sPath,this.oContext);if(!jQuery.sap.equal(this.oList,l)||f){this.update();this._fireChange()}};
sap.ui.model.json.JSONListBinding.prototype.updateIndices=function(){this.aIndices=[];for(var i=0;i<this.oList.length;i++){this.aIndices.push(i)}};
sap.ui.model.json.JSONListBinding.prototype.sort=function(s){if(!s){this.oSorter=null;this.updateIndices();this.applyFilter()}else{this.oSorter=s;this.applySort()}this._fireChange();this._fireSort({sorter:s})};
sap.ui.model.json.JSONListBinding.prototype.applySort=function(){if(!this.oSorter){return}var t=this,s=[],v,c=this.oSorter.fnCompare;if(!c){c=function(a,b){if(b==null){return-1}if(a==null){return 1}if(typeof a=="string"&&typeof b=="string"){return a.localeCompare(b)}if(a<b){return-1}if(a>b){return 1}return 0}}jQuery.each(this.aIndices,function(i,I){v=t.oModel._getObject(t.oSorter.sPath,t.oList[I]);if(typeof v=="string"){v=v.toLocaleUpperCase()}s[I]=v});this.aIndices.sort(function(a,b){var d=s[a],e=s[b],r=c(d,e);if(t.oSorter.bDescending){r=-r}return r})};
sap.ui.model.json.JSONListBinding.prototype.filter=function(f){this.updateIndices();if(!f||!jQuery.isArray(f)||f.length==0){this.aFilters=null;this.iLength=this._getLength()}else{this.aFilters=f;this.applyFilter()}this.applySort();this._fireChange();this._fireFilter({filters:f})};
sap.ui.model.json.JSONListBinding.prototype.applyFilter=function(){if(!this.aFilters){return}var t=this,f={},F,a=[],g=false,b=true;jQuery.each(this.aIndices,function(i,I){b=true;jQuery.each(t.aFilters,function(j,o){F=f[o.sPath];if(!F){F=f[o.sPath]=[]}F.push(o)});jQuery.each(f,function(p,F){var v=t.oModel._getObject(p,t.oList[I]);if(typeof v=="string"){v=v.toUpperCase()}g=false;jQuery.each(F,function(j,o){var T=t.getFilterFunction(o);if(v!=undefined&&T(v)){g=true;return false}});if(!g){b=false;return false}});if(b){a.push(I)}});this.aIndices=a;this.iLength=a.length};
sap.ui.model.json.JSONListBinding.prototype.getFilterFunction=function(f){if(f.fnTest){return f.fnTest}var v=f.oValue1,V=f.oValue2;if(typeof v=="string"){v=v.toUpperCase()}if(typeof V=="string"){V=V.toUpperCase()}switch(f.sOperator){case"EQ":f.fnTest=function(a){return a==v};break;case"NE":f.fnTest=function(a){return a!=v};break;case"LT":f.fnTest=function(a){return a<v};break;case"LE":f.fnTest=function(a){return a<=v};break;case"GT":f.fnTest=function(a){return a>v};break;case"GE":f.fnTest=function(a){return a>=v};break;case"BT":f.fnTest=function(a){return(a>v)&&(a<V)};break;case"Contains":f.fnTest=function(a){if(typeof a!="string"){throw new Error("Only \"String\" values are supported for the FilterOperator: \"Contains\".")}return a.indexOf(v)!=-1};break;case"StartsWith":f.fnTest=function(a){if(typeof a!="string"){throw new Error("Only \"String\" values are supported for the FilterOperator: \"StartsWith\".")}return a.indexOf(v)==0};break;case"EndsWith":f.fnTest=function(a){if(typeof a!="string"){throw new Error("Only \"String\" values are supported for the FilterOperator: \"EndsWith\".")}var p=a.indexOf(v);if(p==-1){return false}return p==a.length-new String(f.oValue1).length};break;default:f.fnTest=function(a){return true}}return f.fnTest};
sap.ui.model.json.JSONListBinding.prototype.getDistinctValues=function(p){var r=[],m={},v,t=this;jQuery.each(this.oList,function(i,c){v=t.oModel.getProperty(p,c);if(!m[v]){m[v]=true;r.push(v)}});return r};
