/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.ui.core.RenderManager");jQuery.sap.require("jquery.sap.encoder");jQuery.sap.require("sap.ui.base.Object");jQuery.sap.require("sap.ui.base.Interface");(function(){var c=["renderControl","write","writeEscaped","translate","writeAcceleratorKey","writeControlData","writeElementData","writeAttribute","writeAttributeEscaped","addClass","writeClasses","addStyle","writeStyles","writeAccessibilityState","writeIcon","getConfiguration","getHTML"];var n=["render","flush","destroy"];sap.ui.base.Object.extend("sap.ui.core.RenderManager",{constructor:function(){sap.ui.base.Object.apply(this,arguments);this.aBuffer=[];this.aRenderedControls=[];this.aStyleStack=[{}]},metadata:{publicMethods:c.concat(n)}});sap.ui.core.RenderManager.prototype.getRendererInterface=function(){var i=new sap.ui.base.Interface(this,c);this.getRendererInterface=jQuery.sap.getter(i);return i}}());
sap.ui.core.RenderManager.prototype.destroy=function(){this.aBuffer=[];this.aRenderedControls=[];this.aStyleStack=[{}]};
sap.ui.core.RenderManager.prototype.getConfiguration=function(){return sap.ui.getCore().getConfiguration()};
sap.ui.core.RenderManager.prototype.getRenderer=function(c){return sap.ui.core.RenderManager.getRenderer(c)};
sap.ui.core.RenderManager.prototype.renderControl=function(c){if(!c){return}if(!this.aRenderStack){this.aRenderStack=new Array()}if(this.aRenderStack&&this.aRenderStack.length>0){jQuery.sap.measure.pause(this.aRenderStack[0]+"---renderControl")}else if(c.getParent()&&c.getParent().getMetadata().getName()=="sap.ui.core.UIArea"){jQuery.sap.measure.pause(c.getParent().getId()+"---rerender")}this.aRenderStack.unshift(c.getId());jQuery.sap.measure.start(c.getId()+"---renderControl","Rendering of "+c.getMetadata().getName());var b=this.aBuffer.length;var C={};if(c.aCustomStyleClasses&&c.aCustomStyleClasses.length>0){C.aCustomStyleClasses=c.aCustomStyleClasses}this.aStyleStack.push(C);jQuery.sap.measure.pause(c.getId()+"---renderControl");var r=this.getRenderer(c);jQuery.sap.measure.resume(c.getId()+"---renderControl");this._bLocked=true;try{var e=jQuery.Event("BeforeRendering");e.srcControl=c;c._handleEvent(e)}finally{this._bLocked=false}var B=c.aBindParameters;if(B&&B.length>0){var d=jQuery(c.getDomRef());if(d&&d[0]){for(var i=0;i<B.length;i++){var p=B[i];d.unbind(p.sEventType,p.fnProxy)}}}r.render(this.getRendererInterface(),c);this.aStyleStack.pop();this.aRenderedControls.push(c);c.bOutput=this.aBuffer.length!=b;jQuery.sap.measure.end(c.getId()+"---renderControl");this.aRenderStack.shift();if(this.aRenderStack&&this.aRenderStack.length>0){jQuery.sap.measure.resume(this.aRenderStack[0]+"---renderControl")}else if(c.getParent()&&c.getParent().getMetadata().getName()=="sap.ui.core.UIArea"){jQuery.sap.measure.resume(c.getParent().getId()+"---rerender")}};
sap.ui.core.RenderManager.prototype.getHTML=function(c){var t=this.aBuffer;var r=this.aBuffer=[];this.renderControl(c);this.aBuffer=t;return r.join("")};
(function(){var s=function(){var c=sap.ui.getCore();var F=c.getCurrentFocusedControlId(),o=null,a=null;if(F){var b=c.getElementById(F);if(b){o=b.getFocusInfo();a=b.getFocusDomRef()}}return{focusedControlId:F,focusInfo:o,focusDomRef:a}};var f=function(r,R,S){for(var i=0,a=R.length;i<a;i++){var c=R[i];if(c.bOutput){r._bLocked=true;try{var E=jQuery.Event("AfterRendering");E.srcControl=c;jQuery.sap.measure.start(c.getId()+"---AfterRendering","AfterRendering of "+c.getMetadata().getName());c._handleEvent(E);jQuery.sap.measure.end(c.getId()+"---AfterRendering")}finally{r._bLocked=false}}}try{if(S&&S.focusedControlId){var F=sap.ui.getCore().getElementById(S.focusedControlId);if(F&&F.getFocusDomRef()!=S.focusDomRef){F.applyFocusInfo(S.focusInfo)}}}catch(e){jQuery.sap.log.warning("Problems while restore focus after rendering: "+e,null,r)}for(var i=0,a=R.length;i<a;i++){var c=R[i],b=c.aBindParameters;if(b&&b.length>0){var d=jQuery(c.getDomRef());if(d&&d[0]){for(var j=0;j<b.length;j++){var p=b[j];d.bind(p.sEventType,p.fnProxy)}}}}};sap.ui.core.RenderManager.prototype.flush=function(t,d,I){if(this.bRendererMode){jQuery.sap.log.info("Flush must not be called from control renderers. Call ignored.",null,this);return}var R=sap.ui.core.RenderManager;if(!d&&(typeof I!=="number")&&!I){R.preserveContent(t)}var S=s();var h=R.prepareHTML5(this.aBuffer.join(""));if(this._fPutIntoDom){this._fPutIntoDom(t,h)}else{for(var i=0;i<this.aRenderedControls.length;i++){var o=this.aRenderedControls[i].getDomRef();if(o&&!R.isPreservedContent(o)){if(R.isInlineTemplate(o)){jQuery(o).empty()}else{jQuery(o).remove()}}}if(typeof I==="number"){if(I<=0){jQuery(t).prepend(h)}else{var $=jQuery(t).children().eq(I-1);if($.length===1){$.after(h)}else{jQuery(t).append(h)}}}else if(!I){jQuery(t).html(h)}else{jQuery(t).append(h)}}f(this,this.aRenderedControls,S);this.aRenderedControls=[];this.aBuffer=[];this.aStyleStack=[{}]};sap.ui.core.RenderManager.prototype.render=function(c,t){if(this.bRendererMode){jQuery.sap.log.info("Render must not be called from control renderers. Call ignored.",null,this);return}if(this._bLocked){jQuery.sap.log.error("Render must not be called within Before or After Rendering Phase. Call ignored.",null,this);return}this.aBuffer=[];this.renderControl(c);this._fPutIntoDom=function(T,h){var R=sap.ui.core.RenderManager;if(c&&t){var o=c.getDomRef();if(R.isPreservedContent(o)){o=jQuery.sap.byId("sap-ui-dummy-"+c.getId())[0]||o}var n=o&&o.parentNode!=t;var a=function(){var j=jQuery(t);if(t.innerHTML==""){j.html(h)}else{j.append(h)}};if(n){if(!R.isPreservedContent(o)){if(R.isInlineTemplate(o)){jQuery(o).empty()}else{jQuery(o).remove()}}if(h){a()}}else{if(h){if(o){if(R.isInlineTemplate(o)){jQuery(o).html(h)}else{jQuery(o).replaceWith(h)}}else{a()}}else{if(R.isInlineTemplate(o)){jQuery(o).empty()}else{jQuery(o).remove()}}}}};this.flush(t,true);this._fPutIntoDom=null}}());
sap.ui.core.RenderManager.getRenderer=function(c){return c.getMetadata().getRenderer()};
sap.ui.core.RenderManager.initHTML5Support=function(){if(!!sap.ui.Device.browser.internet_explorer&&(sap.ui.Device.browser.version===8||sap.ui.Device.browser.version===7)){var t=["article","aside","audio","canvas","command","datalist","details","figcaption","figure","footer","header","hgroup","keygen","mark","meter","nav","output","progress","rp","rt","ruby","section","source","summary","template","time","video","wbr"];for(var i=0;i<t.length;i++){document.createElement(t[i])}var r=new RegExp("<("+t.join("|")+")(\\s|>)","i");var d=null;sap.ui.core.RenderManager.prepareHTML5=function(h){if(h&&h.match(r)){if(!d){d=document.createElement('div');d.style.display='none'}var e=d.cloneNode(true);document.body.appendChild(e);e.innerHTML=h.replace(/^\s\s*/,'').replace(/\s\s*$/,'');document.body.removeChild(e);return e.childNodes}return h};jQuery.sap.log.info("IE8 HTML5 support activated")}else{jQuery.sap.log.info("no IE8 HTML5 support required");sap.ui.core.RenderManager.prepareHTML5=function(h){return h}}};
sap.ui.core.RenderManager.forceRepaint=function(d){var D=typeof d=="string"?jQuery.sap.domById(d):d;if(D){jQuery.sap.log.debug("forcing a repaint for "+(D.id||String(D)));var o=D.style.display;var a=document.activeElement;D.style.display="none";D.offsetHeight;D.style.display=o;if(document.activeElement!==a){jQuery.sap.focus(a)}}};
(function(){var I="sap-ui-preserve";var A="data-sap-ui-preserve";function g(){var $=jQuery("#"+I);if($.length===0){$=jQuery("<DIV/>",{role:"application",id:I}).addClass("sapUiHidden").css("width","0").css("height","0").css("overflow","hidden").appendTo(document.body)}return $}sap.ui.core.RenderManager.preserveContent=function(r,p,P){sap.ui.getCore().getEventBus().publish("sap.ui","__preserveContent",{domNode:r});var $=g();function c(b){b.each(function(i,d){if(d.id===I||sap.ui.getCore().isStaticAreaRef(d)){return}var e=jQuery(d);if(e.attr(A)){if(d===r){var f=jQuery("<DIV/>",{id:"sap-ui-dummy-"+d.id}).addClass("sapUiHidden");f.insertBefore(e)}$.append(e)}else if(P&&d.id){sap.ui.core.RenderManager.markPreservableContent(e,d.id);$.append(e);return}if(!e.attr("data-sap-ui-area")){c(e.children())}})}jQuery.sap.measure.start(r.id+"---preserveContent","preserveContent for "+r.id);c(p?jQuery(r):jQuery(r).children());jQuery.sap.measure.end(r.id+"---preserveContent")};sap.ui.core.RenderManager.findPreservedContent=function(i){var $=g(),b=$.children("["+A+"='"+i.replace(/(:|\.)/g,'\\$1')+"']");return b};sap.ui.core.RenderManager.markPreservableContent=function($,i){$.attr(A,i)};sap.ui.core.RenderManager.isPreservedContent=function(d){return(d&&d.getAttribute(A)&&d.parentNode&&d.parentNode.id==I)};sap.ui.core.RenderManager.getPreserveAreaRef=function(){return g()[0]};var a="data-sap-ui-template";sap.ui.core.RenderManager.markInlineTemplate=function($){$.attr(a,"")};sap.ui.core.RenderManager.isInlineTemplate=function(d){return(d&&d.hasAttribute(a))}}());
sap.ui.core.RenderManager.prototype.write=function(t){this.aBuffer.push.apply(this.aBuffer,arguments);return this};
sap.ui.core.RenderManager.prototype.writeEscaped=function(t,l){if(l){var L=t.split("\n");for(var i=0;i<L.length;i++){L[i]=jQuery.sap.encodeHTML(L[i])}t=L.join("<br>")}else{t=jQuery.sap.encodeHTML(t)}this.aBuffer.push(t);return this};
sap.ui.core.RenderManager.prototype.translate=function(k){};
sap.ui.core.RenderManager.prototype.writeAcceleratorKey=function(){return this};
sap.ui.core.RenderManager.prototype.addStyle=function(n,v){if(v!==undefined&&v!==null){var s=this.aStyleStack[this.aStyleStack.length-1];if(!s.aStyle){s.aStyle=[]}s.aStyle.push(n+":"+v)}return this};
sap.ui.core.RenderManager.prototype.writeStyles=function(){var s=this.aStyleStack[this.aStyleStack.length-1];if(s.aStyle){this.write(" style=\""+s.aStyle.join(";")+"\" ")}s.aStyle=null;return this};
sap.ui.core.RenderManager.prototype.addClass=function(n){if(n){var s=this.aStyleStack[this.aStyleStack.length-1];if(!s.aClasses){s.aClasses=[]}s.aClasses.push(n)}return this};
sap.ui.core.RenderManager.prototype.writeClasses=function(e){var s=this.aStyleStack[this.aStyleStack.length-1];var c=e?e.aCustomStyleClasses:((e===false)?[]:s.aCustomStyleClasses);if(s.aClasses||c){var C=[].concat(s.aClasses||[],c||[]);C.sort();C=jQuery.map(C,function(n,i){return(i==0||n!=C[i-1])?n:null});this.write(" class=\"",C.join(" "),"\" ")}if(!e){s.aCustomStyleClasses=null}s.aClasses=null;return this};
sap.ui.core.RenderManager.prototype.writeControlData=function(c){this.writeElementData(c);return this};
sap.ui.core.RenderManager.prototype.writeElementData=function(e){var I=e.getId();if(I){this.writeAttribute("id",I).writeAttribute("data-sap-ui",I)}var d=e.getCustomData();var l=d.length;for(var i=0;i<l;i++){var D=d[i];if(D.getWriteToDom()){var k=D.getKey();if(typeof D.getValue()==="string"){if((sap.ui.core.ID.isValid(k))&&(k.indexOf(":")==-1)&&(k.indexOf("sap-ui")!==0)){this.writeAttributeEscaped("data-"+k,D.getValue())}else{jQuery.sap.log.error("CustomData with key "+k+" should be written to HTML of "+this+" but the key is not valid (must be a valid sap.ui.core.ID without any colon and may not start with 'sap-ui').")}}else{jQuery.sap.log.error("CustomData with key "+k+" should be written to HTML of "+this+" but the value is not a string.")}}}return this};
sap.ui.core.RenderManager.prototype.writeAttribute=function(n,v){this.write(" ",n,"=\"",v,"\"");return this};
sap.ui.core.RenderManager.prototype.writeAttributeEscaped=function(n,v){this.writeAttribute(n,jQuery.sap.escapeHTML(v));return this};
sap.ui.core.RenderManager.prototype.writeAccessibilityState=function(e,P){if(!sap.ui.getCore().getConfiguration().getAccessibility()){return this}if(arguments.length==1&&!(e instanceof sap.ui.core.Element)){P=e;e=null}var a={};if(e!=null){var m=e.getMetadata();m._enrichChildInfos();var b=function(E,A,v){var o=m.getAllProperties()[E];if(o&&e[o._sGetter]()===v){a[A]="true"}};var c=function(E,A){var o=m.getAllAssociations()[E];if(o&&o.multiple){var i=e[o._sGetter]();if(i.length>0){a[A]=i.join(" ")}}};b("editable","readonly",false);b("enabled","disabled",false);b("visible","hidden",false);b("required","required",true);b("selected","selected",true);b("checked","checked",true);c("ariaDescribedBy","describedby");c("ariaLabelledBy","labelledby")}if(P){var d=function(v){var t=typeof(v);return v===null||v===""||t==="number"||t==="string"||t==="boolean"};var f={};var x,g,t,h;for(x in P){g=P[x];if(d(g)){f[x]=g}else if(typeof(g)==="object"&&d(g.value)){h="";if(g.append&&(x==="describedby"||x==="labelledby")){h=a[x]?a[x]+" ":""}f[x]=h+g.value}}jQuery.extend(a,f)}if(e instanceof sap.ui.core.Element&&e.getParent()&&e.getParent().enhanceAccessibilityState){e.getParent().enhanceAccessibilityState(e,a)}for(var p in a){if(a[p]!=null&&a[p]!==""){this.writeAttribute(p==="role"?p:"aria-"+p,a[p])}}return this};
sap.ui.core.RenderManager.prototype.writeIcon=function(u,c,a){jQuery.sap.require("sap.ui.core.IconPool");var i=sap.ui.core.IconPool.isIconURI(u),s=i?"<span ":"<img ",C="",p,I;if(typeof c==="string"){c=[c]}if(i){if(!c){c=[]}c.push("sapUiIcon")}if(jQuery.isArray(c)){C=c.join(" ")}this.write(s+"class=\""+C+"\" ");if(i){if(!a){a={}}I=sap.ui.core.IconPool.getIconInfo(u);a["data-sap-ui-icon-content"]=I.content;this.write("style=\"font-family: "+I.fontFamily+";\" ")}else{this.writeAttribute("src",u)}if(typeof a==="object"){for(p in a){if(a.hasOwnProperty(p)){this.writeAttributeEscaped(p,a[p])}}}return this.write(i?"></span>":"/>")};
