/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.ui.core.util.LibraryInfo");jQuery.sap.require("sap.ui.base.Object");jQuery.sap.require("jquery.sap.script");sap.ui.base.Object.extend("sap.ui.core.util.LibraryInfo",{constructor:function(){sap.ui.base.Object.apply(this);this._oLibInfos={}},destroy:function(){sap.ui.base.Object.prototype.destroy.apply(this,arguments);this._oLibInfos={}},getInterface:function(){return this}});
sap.ui.core.util.LibraryInfo.prototype._getLibraryInfo=function(l,c){l=l.replace(/\//g,".");if(this._oLibInfos[l]){jQuery.sap.delayedCall(0,window,c,[this._oLibInfos[l]]);return}var u=jQuery.sap.getModulePath(l,'/'),t=this;jQuery.ajax({url:u+".library",dataType:"xml",error:function(x,s,e){jQuery.sap.log.error("failed to load library details from '"+u+".library': "+s+", "+e);t._oLibInfos[l]={name:l,data:null,url:u};c(t._oLibInfos[l])},success:function(d,s,x){t._oLibInfos[l]={name:l,data:d,url:u};c(t._oLibInfos[l])}})};
sap.ui.core.util.LibraryInfo.prototype._getThirdPartyInfo=function(l,c){this._getLibraryInfo(l,function(d){var r={libs:[],library:d.name,libraryUrl:d.url};if(d.data){var L=jQuery(d.data).find("appData").find("thirdparty").children();L.each(function(i,o){if(o.nodeName==="lib"){var $=jQuery(o);var a=$.children("license");r.libs.push({displayName:$.attr("displayName"),homepage:$.attr("homepage"),license:{url:a.attr("url"),type:a.attr("type"),file:d.url+a.attr("file")}})}})}c(r)})};
sap.ui.core.util.LibraryInfo.prototype._getDocuIndex=function(l,c){this._getLibraryInfo(l,function(d){var a=d.name,b=d.url,r={"docu":{},library:a,libraryUrl:b};if(!d.data){c(r);return}var D=jQuery(d.data).find("appData").find("documentation");var u=D.attr("indexUrl");if(!u){c(r);return}if(D.attr("resolve")=="lib"){u=d.url+u}jQuery.ajax({url:u,dataType:"json",error:function(x,s,e){jQuery.sap.log.error("failed to load library docu from '"+u+"': "+s+", "+e);c(r)},success:function(d,s,x){d.library=a;d.libraryUrl=b;c(d)}})})};
