/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.ui.core.tmpl.Template");jQuery.sap.require("sap.ui.base.ManagedObject");sap.ui.base.ManagedObject.extend("sap.ui.core.tmpl.Template",{constructor:function(i,s){sap.ui.base.ManagedObject.apply(this,arguments)},metadata:{stereotype:"template","abstract":true,properties:{"content":{type:"string",group:"Data",defaultValue:null}},publicMethods:["declareControl","createControl","placeAt","createMetadata","createRenderer"],library:"sap.ui.core"}});
sap.ui.core.tmpl.Template.prototype.getInterface=function(){return this};
sap.ui.core.tmpl.Template._mSupportedTypes={};
sap.ui.core.tmpl.Template.registerType=function(t,c){sap.ui.core.tmpl.Template._mSupportedTypes[t]=c};
sap.ui.core.tmpl.Template.unregisterType=function(t){delete sap.ui.core.tmpl.Template._mSupportedTypes[t]};
sap.ui.core.tmpl.Template.parsePath=function(p){var m=undefined,s=p.indexOf(">");if(s>0){m=p.substr(0,s);p=p.substr(s+1)}return{path:p,model:m}};
sap.ui.core.tmpl.Template.prototype.init=function(s,S){if(this.getMetadata().getName()==="sap.ui.core.tmpl.Template"){throw new Error("The class 'sap.ui.core.tmpl.Template' is abstract and must not be instantiated!")}if(sap.ui.base.ManagedObject.bindingParser===sap.ui.base.BindingParser.complexParser){sap.ui.core.tmpl.Template.prototype.extractBindingInfo=function(v,i,S){sap.ui.base.ManagedObject.bindingParser=sap.ui.base.BindingParser.simpleParser;var r=sap.ui.core.Control.prototype.extractBindingInfo.apply(this,arguments);sap.ui.base.ManagedObject.bindingParser=sap.ui.base.BindingParser.complexParser;return r}}};
sap.ui.core.tmpl.Template.prototype.declareControl=function(c){if(c){var m=this.createMetadata(),r=this.createRenderer(),t=this;jQuery.sap.require("sap.ui.core.tmpl.TemplateControl");sap.ui.core.tmpl.TemplateControl.extend(c,{metadata:m,init:function(){sap.ui.core.tmpl.TemplateControl.prototype.init.apply(this,arguments);this.setTemplate(t)},renderer:{renderTemplate:r}});return jQuery.sap.getObject(c)}};
sap.ui.core.tmpl.Template.prototype.createControl=function(i,c,v){jQuery.sap.require("sap.ui.core.tmpl.TemplateControl");var C=new sap.ui.core.tmpl.TemplateControl({id:i,template:this,context:c});C.setTemplateRenderer(this.createRenderer(v));return C};
sap.ui.core.tmpl.Template.prototype.placeAt=function(r,c,p,i){if(typeof c==="string"||typeof c==="number"){p=c;c=undefined}var I;if(!(r instanceof sap.ui.core.Control)&&i){var $=typeof r==="string"?jQuery.sap.byId(r):jQuery(r);if($.length>0){I=$.attr("id");r=$.get(0);var C=$.attr("data-context");c=c||C&&jQuery.parseJSON(C);sap.ui.core.RenderManager.markInlineTemplate($)}}var o=this.createControl(I,c);o.placeAt(r,p);return o};
sap.ui.core.tmpl.Template.prototype.createMetadata=function(){jQuery.sap.log.error("The function createMetadata is an abstract function which needs to be implemented by subclasses.")};
sap.ui.core.tmpl.Template.prototype.createRenderer=function(){jQuery.sap.log.error("The function createRenderer is an abstract function which needs to be implemented by subclasses.")};
sap.ui.template=function(t){if(!t){var T=[];jQuery.each(sap.ui.core.tmpl.Template._mSupportedTypes,function(s,h){jQuery("script[type='"+s+"'], [data-type='"+s+"']").each(function(k,e){T.push(sap.ui.template({id:e.id,domref:e,type:s,_class:h}))})});return T}else{if(typeof t==="string"){return sap.ui.template({id:t})}else if(t&&t.tagName&&t.nodeName&&t.ownerDocument&&t.nodeType===1){return sap.ui.template({id:t.id,domref:t})}t=jQuery.extend({type:sap.ui.core.tmpl.Template.DEFAULT_TEMPLATE},t);var i,s,c,C,r,a=false,l=typeof t.src==="string";if(l){var R=jQuery.sap.sjax({url:t.src,dataType:"text"});if(R.success){i=t.id,s=t.type,c=t.control,C=R.data;var b=/^<!--\sUI5:Template\stype=([a-z\/\-]*)\s(?:controller=([A-Za-z.]*)\s)?-->/,d=C.match(b);if(d){s=d[1];if(d.length==3){a=d[2]}C=C.substr(d[0].length)}}else{throw new Error("The template could not be loaded from "+t.src+"!")}}else{var e=t.domref||jQuery.sap.domById(t.id),$=jQuery(e),I=false;i=t.id||e&&e.id;s=$.attr("type")||t.type,c=$.attr("data-control")||t.control;if(i){var f=sap.ui.getCore().getTemplate(i);if(!f instanceof sap.ui.core.tmpl.Template){throw new Error("Object for id \""+i+"\" is no sap.ui.core.tmpl.Template!")}else{if(f){return f}}}if($.length===0){throw new Error("DOM element for the Template with the id \""+i+"\" not found!")}C=$.html();var g=e.tagName.toLowerCase();if(g!=="script"){I=$.parents("body").length===1}}var h=t._class;if(!h){h=sap.ui.core.tmpl.Template._mSupportedTypes[s];if(!h){throw new Error("The type \""+s+"\" is not supported.")}}jQuery.sap.require(h);var o=jQuery.sap.getObject(h);var j=new o({id:i,content:C});if(c){j.declareControl(c)}if(a){j._sControllerName=a}if(I){j.placeAt(i,t.context,undefined,true)}return j}};
sap.ui.core.tmpl.Template.DEFAULT_TEMPLATE="text/x-handlebars-template";sap.ui.core.tmpl.Template.registerType(sap.ui.core.tmpl.Template.DEFAULT_TEMPLATE,"sap.ui.core.tmpl.HandlebarsTemplate");
