/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.ui.model.ClientTreeBinding");jQuery.sap.require("sap.ui.model.TreeBinding");sap.ui.model.TreeBinding.extend("sap.ui.model.ClientTreeBinding",{constructor:function(m,p,c,f,P){sap.ui.model.TreeBinding.apply(this,arguments);if(!this.oContext){this.oContext=""}this.filterInfo={};this.filterInfo.aFilteredContexts=[];this.filterInfo.oParentContext={};if(this.aFilters){if(this.oModel._getObject(this.sPath,this.oContext)){this.filter(f)}}}});
sap.ui.model.ClientTreeBinding.prototype.getRootContexts=function(){var c=this.oModel.getContext(this.sPath);return this.getNodeContexts(c)};
sap.ui.model.ClientTreeBinding.prototype.getNodeContexts=function(c){var C=c.getPath();if(!jQuery.sap.endsWith(C,"/")){C=C+"/"}if(!jQuery.sap.startsWith(C,"/")){C="/"+C}var a=[],t=this,n=this.oModel._getObject(C),o,A=this.mParameters&&this.mParameters.arrayNames,b;if(A&&jQuery.isArray(A)){jQuery.each(A,function(i,s){b=n[s];if(b){jQuery.each(b,function(S,d){t._saveSubContext(d,a,C,s+"/"+S)})}})}else{if(n){jQuery.sap.each(n,function(N,o){if(jQuery.isArray(o)){jQuery.each(o,function(s,S){t._saveSubContext(S,a,C,N+"/"+s)})}else if(typeof o=="object"){t._saveSubContext(o,a,C,N)}})}}return a};
sap.ui.model.ClientTreeBinding.prototype._saveSubContext=function(n,c,C,N){if(typeof n=="object"){var o=this.oModel.getContext(C+N);if(this.aFilters&&!this.bIsFiltering){if(jQuery.inArray(o,this.filterInfo.aFilteredContexts)!=-1){c.push(o)}}else{c.push(o)}}};
sap.ui.model.ClientTreeBinding.prototype.filter=function(f){this.filterInfo.aFilteredContexts=[];this.filterInfo.oParentContext={};if(!f||!jQuery.isArray(f)||f.length==0){this.aFilters=null}else{this.aFilters=f;var c=new sap.ui.model.Context(this.oModel,this.sPath);this.filterRecursive(c)}this._fireChange({reason:"filter"});this._fireFilter({filters:f})};
sap.ui.model.ClientTreeBinding.prototype.filterRecursive=function(p){this.bIsFiltering=true;var c=this.getNodeContexts(p);this.bIsFiltering=false;if(c.length>0){var t=this;jQuery.each(c,function(i,C){t.filterRecursive(C)});this.applyFilter(p)}};
sap.ui.model.ClientTreeBinding.prototype.applyFilter=function(p){if(!this.aFilters){return}var t=this,f={},F,a=[],g=false,b=true;this.bIsFiltering=true;var u=this.getNodeContexts(p);this.bIsFiltering=false;jQuery.each(t.aFilters,function(j,o){if(o.sPath){F=f[o.sPath];if(!F){F=f[o.sPath]=[]}}else{F=f["__multiFilter"];if(!F){F=f["__multiFilter"]=[]}}F.push(o)});jQuery.each(u,function(i,U){b=true;jQuery.each(f,function(P,F){if(P!=="__multiFilter"){var v=t.oModel._getObject(P,U);if(typeof v=="string"){v=v.toUpperCase()}g=false;jQuery.each(F,function(j,o){var T=t.getFilterFunction(o);if(v&&T(v)){g=true;return false}})}else{g=false;jQuery.each(F,function(j,o){g=t._resolveMultiFilter(o,U);if(g){return false}})}if(!g){b=false;return false}});if(b){a.push(U)}});if(a.length>0){jQuery.merge(this.filterInfo.aFilteredContexts,a);this.filterInfo.aFilteredContexts.push(p);this.filterInfo.oParentContext=p}if(jQuery.inArray(this.filterInfo.oParentContext,u)!=-1){this.filterInfo.aFilteredContexts.push(p);this.filterInfo.oParentContext=p}};
sap.ui.model.ClientTreeBinding.prototype._resolveMultiFilter=function(m,u){var t=this,M=false,f=m.aFilters;if(f){jQuery.each(f,function(i,F){var l=false;if(F._bMultiFilter){l=t._resolveMultiFilter(F,u)}else if(F.sPath){var v=t.oModel.getProperty(F.sPath,u);if(typeof v=="string"){v=v.toUpperCase()}var T=t.getFilterFunction(F);if(v!=undefined&&T(v)){l=true}}if(l&&m.bAnd){M=true}else if(!l&&m.bAnd){M=false;return false}else if(l){M=true;return false}})}return M};
sap.ui.model.ClientTreeBinding.prototype.getFilterFunction=function(f){if(f.fnTest){return f.fnTest}var v=f.oValue1,V=f.oValue2;if(typeof v=="string"){v=v.toUpperCase()}if(typeof V=="string"){V=V.toUpperCase()}switch(f.sOperator){case"EQ":f.fnTest=function(a){return a==v};break;case"NE":f.fnTest=function(a){return a!=v};break;case"LT":f.fnTest=function(a){return a<v};break;case"LE":f.fnTest=function(a){return a<=v};break;case"GT":f.fnTest=function(a){return a>v};break;case"GE":f.fnTest=function(a){return a>=v};break;case"BT":f.fnTest=function(a){return(a>v)&&(a<V)};break;case"Contains":f.fnTest=function(a){return a.indexOf(v)!=-1};break;case"StartsWith":f.fnTest=function(a){return a.indexOf(v)==0};break;case"EndsWith":f.fnTest=function(a){return a.indexOf(v)==a.length-new String(f.oValue1).length};break;default:f.fnTest=function(a){return true}}return f.fnTest};
sap.ui.model.ClientTreeBinding.prototype.checkUpdate=function(f){this._fireChange()};
