/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.ui.model.ClientListBinding");jQuery.sap.require("sap.ui.model.ListBinding");jQuery.sap.require("sap.ui.model.FilterType");sap.ui.model.ListBinding.extend("sap.ui.model.ClientListBinding",{constructor:function(m,p,c,s,f,P){sap.ui.model.ListBinding.apply(this,arguments);this.update()},metadata:{publicMethods:["getLength"]}});
sap.ui.model.ClientListBinding.prototype._getContexts=function(s,l){if(!s){s=0}if(!l){l=Math.min(this.iLength,this.oModel.iSizeLimit)}var e=Math.min(s+l,this.aIndices.length),c,C=[],p=this.oModel.resolve(this.sPath,this.oContext);if(p&&!jQuery.sap.endsWith(p,"/")){p+="/"}for(var i=s;i<e;i++){c=this.oModel.getContext(p+this.aIndices[i]);C.push(c)}return C};
sap.ui.model.ClientListBinding.prototype.setContext=function(c){if(this.oContext!=c){this.oContext=c;if(this.isRelative()){this.update();this._fireChange({reason:sap.ui.model.ChangeReason.Context})}}};
sap.ui.model.ClientListBinding.prototype.getLength=function(){return this.iLength};
sap.ui.model.ClientListBinding.prototype._getLength=function(){return this.aIndices.length};
sap.ui.model.ClientListBinding.prototype.updateIndices=function(){this.aIndices=[];for(var i=0;i<this.oList.length;i++){this.aIndices.push(i)}};
sap.ui.model.ClientListBinding.prototype.sort=function(s){if(!s){this.aSorters=null;this.updateIndices();this.applyFilter()}else{if(s instanceof sap.ui.model.Sorter){s=[s]}this.aSorters=s;this.applySort()}this._fireChange({reason:sap.ui.model.ChangeReason.Sort});this._fireSort({sorter:s});return this};
sap.ui.model.ClientListBinding.prototype.applySort=function(){var t=this,s=[],c=[],v,S;if(!this.aSorters||this.aSorters.length==0){return}for(var j=0;j<this.aSorters.length;j++){S=this.aSorters[j];c[j]=S.fnCompare;if(!c[j]){c[j]=function(a,b){if(b==null){return-1}if(a==null){return 1}if(typeof a=="string"&&typeof b=="string"){return a.localeCompare(b)}if(a<b){return-1}if(a>b){return 1}return 0}}jQuery.each(this.aIndices,function(i,I){v=t.oModel.getProperty(S.sPath,t.oList[I]);if(typeof v=="string"){v=v.toLocaleUpperCase()}if(!s[j]){s[j]=[]}s[j][I]=v})}this.aIndices.sort(function(a,b){var d=s[0][a],e=s[0][b];return t._applySortCompare(a,b,d,e,s,c,0)})};
sap.ui.model.ClientListBinding.prototype._applySortCompare=function(a,b,v,c,s,C,d){var S=this.aSorters[d],f=C[d],r;r=f(v,c);if(S.bDescending){r=-r}if(r==0&&this.aSorters[d+1]){v=s[d+1][a],c=s[d+1][b];r=this._applySortCompare(a,b,v,c,s,C,d+1)}return r};
sap.ui.model.ClientListBinding.prototype.filter=function(f,F){this.updateIndices();if(f instanceof sap.ui.model.Filter){f=[f]}if(F==sap.ui.model.FilterType.Application){this.aApplicationFilters=f||[]}else if(F==sap.ui.model.FilterType.Control){this.aFilters=f||[]}else{this.aFilters=f||[];this.aApplicationFilters=[]}f=this.aFilters.concat(this.aApplicationFilters);if(f.length==0){this.aFilters=[];this.aApplicationFilters=[];this.iLength=this._getLength()}else{this.applyFilter()}this.applySort();this._fireChange({reason:sap.ui.model.ChangeReason.Filter});if(F==sap.ui.model.FilterType.Application){this._fireFilter({filters:this.aApplicationFilters})}else{this._fireFilter({filters:this.aFilters})}return this};
sap.ui.model.ClientListBinding.prototype.applyFilter=function(){if(!this.aFilters){return}var t=this,f={},F,a=[],g=false,b=true,c=this.aFilters.concat(this.aApplicationFilters);jQuery.each(c,function(j,o){if(o.sPath){F=f[o.sPath];if(!F){F=f[o.sPath]=[]}}else{F=f["__multiFilter"];if(!F){F=f["__multiFilter"]=[]}}F.push(o)});jQuery.each(this.aIndices,function(i,I){b=true;jQuery.each(f,function(p,F){if(p!=="__multiFilter"){var v=t.oModel.getProperty(p,t.oList[I]);if(typeof v=="string"){v=v.toUpperCase()}g=false;jQuery.each(F,function(j,o){var T=t.getFilterFunction(o);if(v!=undefined&&T(v)){g=true;return false}})}else{g=false;jQuery.each(F,function(j,o){g=t._resolveMultiFilter(o,I);if(g){return false}})}if(!g){b=false;return false}});if(b){a.push(I)}});this.aIndices=a;this.iLength=a.length};
sap.ui.model.ClientListBinding.prototype._resolveMultiFilter=function(m,I){var t=this,M=false,f=m.aFilters;if(f){jQuery.each(f,function(i,F){var l=false;if(F._bMultiFilter){l=t._resolveMultiFilter(F,I)}else if(F.sPath){var v=t.oModel.getProperty(F.sPath,t.oList[I]);if(typeof v=="string"){v=v.toUpperCase()}var T=t.getFilterFunction(F);if(v!=undefined&&T(v)){l=true}}if(l&&m.bAnd){M=true}else if(!l&&m.bAnd){M=false;return false}else if(l){M=true;return false}})}return M};
sap.ui.model.ClientListBinding.prototype.getFilterFunction=function(f){if(f.fnTest){return f.fnTest}var v=f.oValue1,V=f.oValue2;if(typeof v=="string"){v=v.toUpperCase()}if(typeof V=="string"){V=V.toUpperCase()}switch(f.sOperator){case"EQ":f.fnTest=function(a){return a==v};break;case"NE":f.fnTest=function(a){return a!=v};break;case"LT":f.fnTest=function(a){return a<v};break;case"LE":f.fnTest=function(a){return a<=v};break;case"GT":f.fnTest=function(a){return a>v};break;case"GE":f.fnTest=function(a){return a>=v};break;case"BT":f.fnTest=function(a){return(a>=v)&&(a<=V)};break;case"Contains":f.fnTest=function(a){if(typeof a!="string"){throw new Error("Only \"String\" values are supported for the FilterOperator: \"Contains\".")}return a.indexOf(v)!=-1};break;case"StartsWith":f.fnTest=function(a){if(typeof a!="string"){throw new Error("Only \"String\" values are supported for the FilterOperator: \"StartsWith\".")}return a.indexOf(v)==0};break;case"EndsWith":f.fnTest=function(a){if(typeof a!="string"){throw new Error("Only \"String\" values are supported for the FilterOperator: \"EndsWith\".")}var p=a.indexOf(v);if(p==-1){return false}return p==a.length-new String(f.oValue1).length};break;default:f.fnTest=function(a){return true}}return f.fnTest};
sap.ui.model.ClientListBinding.prototype.getDistinctValues=function(p){var r=[],m={},v,t=this;jQuery.each(this.oList,function(i,c){v=t.oModel.getProperty(p,c);if(!m[v]){m[v]=true;r.push(v)}});return r};
