/*
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.ui.core.util.serializer.ViewSerializer");jQuery.sap.require("sap.ui.core.util.serializer.Serializer");jQuery.sap.require("sap.ui.core.util.serializer.HTMLViewSerializer");jQuery.sap.require("sap.ui.core.util.serializer.XMLViewSerializer");jQuery.sap.require("sap.ui.base.EventProvider");sap.ui.base.EventProvider.extend("sap.ui.core.util.serializer.ViewSerializer",{constructor:function(r,w,d){sap.ui.base.EventProvider.apply(this);this._oRootControl=r;this._oWindow=w||window;this._mViews={};this._sDefaultXmlNamespace=d}});
sap.ui.core.util.serializer.ViewSerializer.prototype.serializeToXML=function(){return this.serialize("XML")};
sap.ui.core.util.serializer.ViewSerializer.prototype.serializeToHTML=function(){return this.serialize("HTML")};
sap.ui.core.util.serializer.ViewSerializer.prototype.serialize=function(c){this._mViews={};this._sConvertToViewType=c||undefined;return this._serializeRecursive(this._oRootControl)};
sap.ui.core.util.serializer.ViewSerializer.prototype._getViewType=function(v){if(!this._sConvertToViewType){if(v instanceof this._oWindow.sap.ui.core.mvc.HTMLView){return"HTML"}else if(v instanceof this._oWindow.sap.ui.core.mvc.XMLView){return"XML"}}return this._sConvertToViewType};
sap.ui.core.util.serializer.ViewSerializer.prototype._serializeRecursive=function(c){if(c instanceof this._oWindow.sap.ui.core.mvc.View){var v=this._getViewSerializer(c,this._getViewType(c));if(v){var V=c.getControllerName();if(!this._mViews[V]){this._mViews[V]=v.serialize(this._getViewType(c))}}}if(c.getMetadata().getClass()===this._oWindow.sap.ui.core.UIArea){var C=c.getContent();for(var i=0;i<C.length;i++){this._serializeRecursive(C[i])}}else if(c.getMetadata().getClass()===this._oWindow.sap.ui.core.ComponentContainer){this._serializeRecursive(c.getComponentInstance().getAggregation("rootControl"))}else{var a=c.getMetadata().getAllAggregations();if(a){for(var n in a){var A=a[n];var o=c[A._sGetter]();if(o&&o.length){for(var i=0;i<o.length;i++){var O=o[i];if(O instanceof this._oWindow.sap.ui.core.Element){this._serializeRecursive(O)}}}else if(o instanceof this._oWindow.sap.ui.core.Element){this._serializeRecursive(o)}}}}return this._mViews};
sap.ui.core.util.serializer.ViewSerializer.prototype._getViewSerializer=function(v,t){var g=function(e){if(e.fFunction&&e.fFunction._sapui_handlerName){var h=e.fFunction._sapui_handlerName;var c=v.getController();if(c[h]){return h}}};var G=function(c){if(c._sapui_controlId){return c._sapui_controlId}return c.getId().replace(v.createId(""),"")};if(t==="HTML"){return new sap.ui.core.util.serializer.HTMLViewSerializer(v,this._oWindow,G,g)}else if(t==="XML"){return new sap.ui.core.util.serializer.XMLViewSerializer(v,this._oWindow,this._sDefaultXmlNamespace,G,g)}else{var t=(v)?v.constructor:"?";throw Error("View type '"+t+"' is not supported for conversion. Only HTML and XML is supported")}};
