/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.ui.ux3.ThingViewerRenderer");sap.ui.ux3.ThingViewerRenderer={};
sap.ui.ux3.ThingViewerRenderer.render=function(r,c){var a=r;a.write("<div");a.writeControlData(c);a.writeAttributeEscaped("style","width:"+c.getWidth()+"; height:"+c.getHeight());a.addClass('sapUiUx3TV');a.writeClasses();a.write(">");this.renderContent(a,c);a.write("</div>")};
sap.ui.ux3.ThingViewerRenderer.renderContent=function(r,c){var a=r;a.write("<div role='Main' class='sapUiUx3TVContent' id='"+c.getId()+"-content'>");a.write("<div class='sapUiUx3TVHeader sapUiUx3TVNoActionBar'>");a.write("<div class='sapUiUx3TVHeaderContainerIdentifier'>");a.write("<span role='heading' aria-level='1' class='sapUiUx3TVIdentifier'");a.writeAttributeEscaped("title",c.getType());a.write(">");a.writeEscaped(c.getType());a.write("</span>");a.write("</div>");a.write("<div class='sapUiUx3TVHeaderGroupScrollContainer'>");a.write("<div id='"+c.getId()+"-header' class='sapUiUx3TVHeaderContainer'>");this.renderHeader(a,c);a.write("</div>");a.write("<div id='"+c.getId()+"-headerContent'>");this.renderHeaderContent(a,c);a.write("</div>");a.write("</div>");a.write("</div>");a.write("<div class='sapUiUx3TVFacets sapUiUx3TVNoActionBar'>");a.write("<div role='Navigation' class='sapUiUx3TVFacetBar'>");a.renderControl(c._getNavBar());a.write("</div>");a.write("<div id='"+c.getId()+"-facetContent' class='sapUiUx3TVFacetContent'>");this.renderFacetContent(a,c);a.write("</div>");a.write("</div>");this.renderToolbar(a,c);a.write("</div>")};
sap.ui.ux3.ThingViewerRenderer.addRootClasses=function(r,c){var a=r;a.addClass("sapUiUx3TV")};
sap.ui.ux3.ThingViewerRenderer.addOverlayClasses=function(r,c){var a=r;a.addClass("sapUiUx3TVOverlay")};
sap.ui.ux3.ThingViewerRenderer.renderHeader=function(r,c){var a=r;a.write("<div class='sapUiUx3TVIconBar'>");a.write("<div class='sapUiUx3TVIcon'><img alt='' role='presentation' src='");a.writeEscaped(c.getIcon());a.write("' id='"+c.getId()+"-swatch'></div>");a.write("<div class='sapUiUx3TVTitle'>");a.write("<span role='heading' aria-level='2' class='sapUiUx3TVTitleFirst'");a.writeAttributeEscaped("title",c.getTitle());a.write(">");a.writeEscaped(c.getTitle());a.write("</span><br/>");a.write("<span role='heading' aria-level='3' class='sapUiUx3TVTitleSecond'");a.writeAttributeEscaped("title",c.getSubtitle());a.write(">");a.writeEscaped(c.getSubtitle());a.write("</span>");a.write("</div>");a.write("</div>")};
sap.ui.ux3.ThingViewerRenderer.renderToolbar=function(r,c){if(c.getActionBar()){r.write("<div id='"+c.getId()+"-toolbar' class='sapUiUx3TVToolbar'>");r.renderControl(c.getActionBar());r.write("</div>")}};
sap.ui.ux3.ThingViewerRenderer.renderHeaderContent=function(r,c){var h=c.getHeaderContent();for(var i=0;i<h.length;i++){var a=h[i];r.write("<hr class='sapUiUx3TVHRWhite'>");r.write("<div class='sapUiUx3TVHeaderContainer' role='form'>");r.write("<div class='sapUiUx3TVHeaderGroupTitle'");r.writeAttributeEscaped("title",a.getTitle());r.write("><span>");r.writeEscaped(a.getTitle());r.write("</span></div>");r.write("<div class='sapUiUx3TVHeaderGroupContent'>");var b=a.getContent();for(var j=0;j<b.length;j++){var d=b[j];r.renderControl(d)}r.write("</div>");r.write("</div>")}};
sap.ui.ux3.ThingViewerRenderer.renderFacetContent=function(r,c){var f=c.getFacetContent();var t=true;if(f.length==1){t=false}for(var i=0;i<f.length;i++){var g=f[i];if(g.getColspan()){r.write("<div class='sapUiUx3TVFacetThingGroupSpan' role='form'>")}else{r.write("<div class='sapUiUx3TVFacetThingGroup' role='form'>")}if(t){r.write("<div class='sapUiUx3TVFacetThingGroupContentTitle'");r.writeAttributeEscaped("title",g.getTitle());r.write("><span>");r.writeEscaped(g.getTitle());r.write("</span></div>")}r.write("<div class='sapUiUx3TVFacetThingGroupContent'>");var a=g.getContent();for(var j=0;j<a.length;j++){r.renderControl(a[j])}r.write("</div></div>")}};
