/**
 * Range.js
 *
 * Copyright, Moxiecode Systems AB
 * Released under LGPL License.
 *
 * License: http://www.tinymce.com/license
 * Contributing: http://www.tinymce.com/contributing
 */
(function(t){t.dom.RangeUtils=function(d){var I='\uFEFF';this.walk=function(r,c){var s=r.startContainer,a=r.startOffset,e=r.endContainer,b=r.endOffset,f,g,h,n,p,i,j;j=d.select('td.mceSelected,th.mceSelected');if(j.length>0){t.each(j,function(n){c([n])});return}function k(j){var n;n=j[0];if(n.nodeType===3&&n===s&&a>=n.nodeValue.length){j.splice(0,1)}n=j[j.length-1];if(b===0&&j.length>0&&n===e&&n.nodeType===3){j.splice(j.length-1,1)}return j};function l(n,o,q){var i=[];for(;n&&n!=q;n=n[o])i.push(n);return i};function m(n,o){do{if(n.parentNode==o)return n;n=n.parentNode}while(n)};function w(o,q,u){var v=u?'nextSibling':'previousSibling';for(n=o,p=n.parentNode;n&&n!=q;n=p){p=n.parentNode;i=l(n==o?n:n[v],v);if(i.length){if(!u)i.reverse();c(k(i))}}};if(s.nodeType==1&&s.hasChildNodes())s=s.childNodes[a];if(e.nodeType==1&&e.hasChildNodes())e=e.childNodes[Math.min(b-1,e.childNodes.length-1)];if(s==e)return c(k([s]));f=d.findCommonAncestor(s,e);for(n=s;n;n=n.parentNode){if(n===e)return w(s,f,true);if(n===f)break}for(n=e;n;n=n.parentNode){if(n===s)return w(e,f);if(n===f)break}g=m(s,f)||s;h=m(e,f)||e;w(s,g,true);i=l(g==s?g:g.nextSibling,'nextSibling',h==e?h.nextSibling:h);if(i.length)c(k(i));w(e,h)};this.split=function(r){var s=r.startContainer,a=r.startOffset,e=r.endContainer,b=r.endOffset;function c(n,o){return n.splitText(o)};if(s==e&&s.nodeType==3){if(a>0&&a<s.nodeValue.length){e=c(s,a);s=e.previousSibling;if(b>a){b=b-a;s=e=c(e,b).previousSibling;b=e.nodeValue.length;a=0}else{b=0}}}else{if(s.nodeType==3&&a>0&&a<s.nodeValue.length){s=c(s,a);a=0}if(e.nodeType==3&&b>0&&b<e.nodeValue.length){e=c(e,b).previousSibling;b=e.nodeValue.length}}return{startContainer:s,startOffset:a,endContainer:e,endOffset:b}}};t.dom.RangeUtils.compareRanges=function(r,a){if(r&&a){if(r.item||r.duplicate){if(r.item&&a.item&&r.item(0)===a.item(0))return true;if(r.isEqual&&a.isEqual&&a.isEqual(r))return true}else{return r.startContainer==a.startContainer&&r.startOffset==a.startOffset}}return false}})(tinymce);
