/**
 * SplitButton.js
 *
 * Copyright, Moxiecode Systems AB
 * Released under LGPL License.
 *
 * License: http://www.tinymce.com/license
 * Contributing: http://www.tinymce.com/contributing
 */
(function(a){var D=a.DOM,E=a.dom.Event,e=a.each;a.create('tinymce.ui.SplitButton:tinymce.ui.MenuButton',{SplitButton:function(i,s,b){this.parent(i,s,b);this.classPrefix='mceSplitButton'},renderHTML:function(){var h,t=this,s=t.settings,b;h='<tbody><tr>';if(s.image)b=D.createHTML('img ',{src:s.image,role:'presentation','class':'mceAction '+s['class']});else b=D.createHTML('span',{'class':'mceAction '+s['class']},'');b+=D.createHTML('span',{'class':'mceVoiceLabel mceIconOnly',id:t.id+'_voice',style:'display:none;'},s.title);h+='<td >'+D.createHTML('a',{role:'button',id:t.id+'_action',tabindex:'-1',href:'javascript:;','class':'mceAction '+s['class'],onclick:"return false;",onmousedown:'return false;',title:s.title},b)+'</td>';b=D.createHTML('span',{'class':'mceOpen '+s['class']},'<span style="display:none;" class="mceIconOnly" aria-hidden="true">\u25BC</span>');h+='<td >'+D.createHTML('a',{role:'button',id:t.id+'_open',tabindex:'-1',href:'javascript:;','class':'mceOpen '+s['class'],onclick:"return false;",onmousedown:'return false;',title:s.title},b)+'</td>';h+='</tr></tbody>';h=D.createHTML('table',{role:'presentation','class':'mceSplitButton mceSplitButtonEnabled '+s['class'],cellpadding:'0',cellspacing:'0',title:s.title},h);return D.createHTML('div',{id:t.id,role:'button',tabindex:'0','aria-labelledby':t.id+'_voice','aria-haspopup':'true'},h)},postRender:function(){var t=this,s=t.settings,b;if(s.onclick){b=function(c){if(!t.isDisabled()){s.onclick(t.value);E.cancel(c)}};E.add(t.id+'_action','click',b);E.add(t.id,['click','keydown'],function(c){var d=32,f=14,g=13,h=38,i=40;if((c.keyCode===32||c.keyCode===13||c.keyCode===14)&&!c.altKey&&!c.ctrlKey&&!c.metaKey){b();E.cancel(c)}else if(c.type==='click'||c.keyCode===i){t.showMenu();E.cancel(c)}})}E.add(t.id+'_open','click',function(c){t.showMenu();E.cancel(c)});E.add([t.id,t.id+'_open'],'focus',function(){t._focused=1});E.add([t.id,t.id+'_open'],'blur',function(){t._focused=0});if(a.isIE6||!D.boxModel){E.add(t.id,'mouseover',function(){if(!D.hasClass(t.id,'mceSplitButtonDisabled'))D.addClass(t.id,'mceSplitButtonHover')});E.add(t.id,'mouseout',function(){if(!D.hasClass(t.id,'mceSplitButtonDisabled'))D.removeClass(t.id,'mceSplitButtonHover')})}},destroy:function(){this.parent();E.clear(this.id+'_action');E.clear(this.id+'_open');E.clear(this.id)}})})(tinymce);
