/**
 * editor_template_src.js
 *
 * Copyright 2009, Moxiecode Systems AB
 * Released under LGPL License.
 *
 * License: http://tinymce.moxiecode.com/license
 * Contributing: http://tinymce.moxiecode.com/contributing
 */
(function(){var D=tinymce.DOM;tinymce.ThemeManager.requireLangPack('simple');tinymce.create('tinymce.themes.SimpleTheme',{init:function(e,u){var t=this,a=['Bold','Italic','Underline','Strikethrough','InsertUnorderedList','InsertOrderedList'],s=e.settings;t.editor=e;e.contentCSS.push(u+"/skins/"+s.skin+"/content.css");e.onInit.add(function(){e.onNodeChange.add(function(e,b){tinymce.each(a,function(c){b.get(c.toLowerCase()).setActive(e.queryCommandState(c))})})});D.loadCSS((s.editor_css?e.documentBaseURI.toAbsolute(s.editor_css):'')||u+"/skins/"+s.skin+"/ui.css")},renderUI:function(o){var t=this,n=o.targetNode,i,a,e=t.editor,c=e.controlManager,s;n=D.insertAfter(D.create('span',{id:e.id+'_container','class':'mceEditor '+e.settings.skin+'SimpleSkin'}),n);n=s=D.add(n,'table',{cellPadding:0,cellSpacing:0,'class':'mceLayout'});n=a=D.add(n,'tbody');n=D.add(a,'tr');n=i=D.add(D.add(n,'td'),'div',{'class':'mceIframeContainer'});n=D.add(D.add(a,'tr',{'class':'last'}),'td',{'class':'mceToolbar mceLast',align:'center'});a=t.toolbar=c.createToolbar("tools1");a.add(c.createButton('bold',{title:'simple.bold_desc',cmd:'Bold'}));a.add(c.createButton('italic',{title:'simple.italic_desc',cmd:'Italic'}));a.add(c.createButton('underline',{title:'simple.underline_desc',cmd:'Underline'}));a.add(c.createButton('strikethrough',{title:'simple.striketrough_desc',cmd:'Strikethrough'}));a.add(c.createSeparator());a.add(c.createButton('undo',{title:'simple.undo_desc',cmd:'Undo'}));a.add(c.createButton('redo',{title:'simple.redo_desc',cmd:'Redo'}));a.add(c.createSeparator());a.add(c.createButton('cleanup',{title:'simple.cleanup_desc',cmd:'mceCleanup'}));a.add(c.createSeparator());a.add(c.createButton('insertunorderedlist',{title:'simple.bullist_desc',cmd:'InsertUnorderedList'}));a.add(c.createButton('insertorderedlist',{title:'simple.numlist_desc',cmd:'InsertOrderedList'}));a.renderTo(n);return{iframeContainer:i,editorContainer:e.id+'_container',sizeContainer:s,deltaHeight:-20}},getInfo:function(){return{longname:'Simple theme',author:'Moxiecode Systems AB',authorurl:'http://tinymce.moxiecode.com',version:tinymce.majorVersion+"."+tinymce.minorVersion}}});tinymce.ThemeManager.add('simple',tinymce.themes.SimpleTheme)})();
