/*!
 * SAP UI development toolkit for HTML5 (SAPUI5) (c) Copyright
 * 		2009-2012 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.ca.ui.TabContainerOverflow");jQuery.sap.require("sap.ca.ui.library");jQuery.sap.require("sap.ui.core.Control");sap.ui.core.Control.extend("sap.ca.ui.TabContainerOverflow",{metadata:{library:"sap.ca.ui",properties:{"showSelection":{type:"boolean",group:"Misc",defaultValue:true,deprecated:true},"expandable":{type:"boolean",group:"Misc",defaultValue:true},"expanded":{type:"boolean",group:"Misc",defaultValue:true},"fullyExpanded":{type:"boolean",group:"Misc",defaultValue:false},"selectedKey":{type:"string",group:"Data",defaultValue:'null'},"visible":{type:"boolean",group:"Behavior",defaultValue:true},"overflowHeight":{type:"string",group:"Misc",defaultValue:"50px"}},aggregations:{"items":{type:"sap.m.IconTab",multiple:true,singularName:"item"},"content":{type:"sap.ui.core.Control",multiple:true,singularName:"content"}},events:{"select":{},"expand":{}}}});sap.ca.ui.TabContainerOverflow.M_EVENTS={'select':'select','expand':'expand'};jQuery.sap.declare("sap.ca.ui.TabContainerOverflow");jQuery.sap.require("sap.m.library");jQuery.sap.require("sap.ui.core.Control");
sap.ca.ui.TabContainerOverflow.prototype.init=function(){this.moreLessButton=new sap.m.Button({id:this.getId()+"-overlayButton",icon:"sap-icon://slim-arrow-down",type:sap.m.ButtonType.Unstyled,press:jQuery.proxy(this.partialToggleExpandCollapse,this)})};
sap.ca.ui.TabContainerOverflow.prototype.exit=function(){};
sap.ca.ui.TabContainerOverflow.prototype.onBeforeRendering=function(){if(this.getItems().length>0){if(!this.oSelectedItem){this.oSelectedItem=this.getItems()[0]}this.setProperty("selectedKey",this.oSelectedItem.getKey(),true)}};
sap.ca.ui.TabContainerOverflow.prototype.setSelectedItem=function(i){if(!i.getEnabled()){return}var $=jQuery.sap.byId(this.getId()+"-content");this.oSelectedItem.$().removeClass("sapMITSelected");if(this.oSelectedItem===i&&this.getExpandable()){this.toggleExpandCollapse()}else{this.setFullyExpanded(false);this.moreLessButton.setIcon("sap-icon://slim-arrow-down");if($.length>0){$.empty()}this.oSelectedItem=i;var s=this.oSelectedItem.getContent();this.oSelectedItem.$().addClass("sapMITSelected");if(s.length>0){this._rerenderContent(s)}else{this._rerenderContent(this.getContent())}if(this.getExpanded()===false){this.toggleExpandCollapse()}this.adjustArrow();this.moreLessButton.rerender();this.onTransitionEnded()}this.setProperty("selectedKey",this.oSelectedItem.getKey(),true);this.fireSelect({selectedItem:this.oSelectedItem,selectedKey:this.oSelectedItem.getKey(),item:this.oSelectedItem,key:this.oSelectedItem.getKey()})};
sap.ca.ui.TabContainerOverflow.prototype._rerenderContent=function(c){var $=jQuery.sap.byId(this.getId()+"-content");if(c.length>0){var r=sap.ui.getCore().createRenderManager();for(var i=0;i<c.length;i++){r.renderControl(c[i])}r.flush($[0]);r.destroy()}};
sap.ca.ui.TabContainerOverflow.prototype.adjustArrow=function(){var $=jQuery.sap.byId(this.getId()+"-arrow"),a;if(this.oSelectedItem){a=this.oSelectedItem.$();if(a.length>0){a.siblings().removeClass("sapMITSelected");a.addClass("sapMITSelected");var l=a[0].offsetLeft+a.outerWidth()/2-$.width()/2;$.css("left",l+"px")}}};
sap.ca.ui.TabContainerOverflow.prototype.renderButtonVisibility=function(){var $=jQuery.sap.byId(this.getId()+"-content");var a=jQuery.sap.byId(this.getId()+"-overlay");var b=jQuery.sap.byId(this.getId()+"-overlayButton");var o=$.height();$.css({height:"auto"});var c=$.height();$.css({height:this.getOverflowHeight()});var d=$.height();$.css({height:o});if(c>d){a.show();b.show()}else{a.hide();b.hide()}};
sap.ca.ui.TabContainerOverflow.prototype.onAfterRendering=function(){this.adjustArrow();this.onTransitionEnded();var $=jQuery.sap.byId(this.getId()+"-content");$.css({overflow:"hidden"});this.renderButtonVisibility()};
sap.ca.ui.TabContainerOverflow.prototype.destroyItems=function(){this.oSelectedItem=null;this.destroyAggregation("items")};
sap.ca.ui.TabContainerOverflow.prototype.onThemeChanged=function(e){this.adjustArrow()};
sap.ca.ui.TabContainerOverflow.prototype.onTransitionEnded=function(){var $=jQuery.sap.byId(this.getId()+"-content");var a=jQuery.sap.byId(this.getId()+"-containerContent");var b=jQuery.sap.byId(this.getId()+"-overlay");var c=jQuery.sap.byId(this.getId()+"-overlayButton");var e=this.getExpanded();var f=this.getFullyExpanded();if(e){this.renderButtonVisibility();jQuery.sap.byId(this.getId()+"-arrow").show();$.css("display","block");if(f){$.css({height:"auto"})}else{$.css({height:this.getOverflowHeight()})}}else{$.css("display","none")}b.css("bottom","0px");c.css("bottom","0px");a.toggleClass("sapMITBContentClosed",!e)};
sap.ca.ui.TabContainerOverflow.prototype.toggleExpandCollapse=function(){var e=!this.getExpanded();var f=this.getFullyExpanded();var $=jQuery.sap.byId(this.getId()+"-content");var a=jQuery.sap.byId(this.getId()+"-overlay");var b=jQuery.sap.byId(this.getId()+"-overlayButton");var c=jQuery.sap.byId(this.getId()+"-arrow");var d=jQuery.sap.byId(this._getItemByKey(this.getItems(),this.getSelectedKey()).getId());d.toggleClass("sapMITBContentTabSelected",e);d.toggleClass("sapMITSelected",e);if(e){if(!f){$.show();$.animate({height:this.getOverflowHeight()},400);this.renderButtonVisibility()}else{$.slideDown('400',jQuery.proxy(this.onTransitionEnded,this))}c.show()}else{c.hide();b.hide();a.hide();$.slideUp('400',jQuery.proxy(this.onTransitionEnded,this))}this.setProperty("expanded",e,true);this.fireExpand({expand:e,collapse:!e})};
sap.ca.ui.TabContainerOverflow.prototype._getItemByKey=function(I,k){for(var i=0;i<I.length;i++){if(I[i]instanceof sap.m.IconTabFilter){if(I[i].getKey()===k){return I[i]}}}};
sap.ca.ui.TabContainerOverflow.prototype._checkTextOnly=function(I){if(I.length>0){for(var i=0;i<I.length;i++){if(I[i]instanceof sap.m.IconTabFilter){if(I[i].getIcon()){return false}}}}return true};
sap.ca.ui.TabContainerOverflow.prototype._checkNoText=function(I){if(I.length>0){for(var i=0;i<I.length;i++){if(I[i]instanceof sap.m.IconTabFilter){if(I[i].getText().length>0){return false}}}}return true};
sap.ca.ui.TabContainerOverflow.prototype.partialToggleExpandCollapse=function(){var $=jQuery.sap.byId(this.getId()+"-content");var f=this.getFullyExpanded();if(!f){this.moreLessButton.setIcon("sap-icon://slim-arrow-up");$.css({height:"auto"});var o=$.height();$.css({height:this.getOverflowHeight()});$.animate({height:o},400);this.moreLessButton.rerender();this.setProperty("fullyExpanded",true,true)}else{this.moreLessButton.setIcon("sap-icon://slim-arrow-down");$.animate({height:this.getOverflowHeight()},400);this.moreLessButton.rerender();this.setProperty("fullyExpanded",false,true)}};
