/*!
 * CVOM HTML5 charts
 * 
 * 	(c) Copyright 2009-2012 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.service.visualization.ChartOption");jQuery.sap.require("sap.service.visualization.library");jQuery.sap.require("sap.ui.core.Element");sap.ui.core.Element.extend("sap.service.visualization.ChartOption",{metadata:{deprecated:true,library:"sap.service.visualization"}});
/*!
 * @copyright@
 */

sap.service.visualization.ChartOption.prototype.getXYChartOption=function(c,a){var l=c.getLegendDirection();var b=c.getLegendVerticalOffset();var d=c.getLegendHorizontalOffset();var e=c.getLegendFirst();var s=c.getShowLegend();var m=c.getMeasures();var t=c.getTitle();var f=c.getTitleHorizontalAlign();var g=c.getSubTitle();var h=c.getSubTitleHorizontalAlign();var j=c.getShowTitle();var k=c.getLegendFormatString();var n=c.getTitleFormatString();var o=c.getSubTitleFormatString();var y=c.getYAxis();var x=c.getXAxis();var p=c.getDeselectEnabled();var q=c.getDefaultSelectedItems();var r=c.getSelectionMode();var u;var v;switch(a){case'Bar':c.bar=null;v=c.getBarMarker();if(v==null){v=undefined};break;case'Line':c.line=null;u=c.getLineMarkerAndThickness();if(u==null){u=undefined};break;case'Column':c.column=null;v=c.getBarMarker();if(v==null){v=undefined};break;case'Combination':c.combination=null;u=c.getLineMarkerAndThickness();v=c.getBarMarker();if(v==null){v=undefined};if(u==null){u=undefined}break}var w=new sap.service.visualization.Themings().getCorrespondingThemings(a);var z=function(P){var Q=/^(0|-?[1-9]\d*)$|^(0|-?[1-9]\d*)\.(\d+)$/;return Q.exec(P)};var A=w.chartPadding;var B={};B.legendFirst=e;B.chartPadding=A;var C={};C.color=w.bgColor;var D={};D.visible=s;D.position=l;D.verticalOffset=b;D.horizontalOffset=d;D.formatString=k;var E=w.legendTitleFont;D.titleFont=E;D.titleColor=w.legendTitleFontColor;var F=w.legendFont;D.labelFont=F;D.labelColor=w.legendColor;var G={};G.text=t;G.visible=j;G.font=w.mainTitleFont;G.color=w.mainTitleColor;G.horizontalAlign=f;G.formatString=n;var H={};H.text=g;H.visible=j;H.font=w.subTitleFont;H.color=w.subTitleColor;H.horizontalAlign=h;H.formatString=o;var I={};I.main=G;I.sub=H;var J={};J.mainValue={};J.mainValue.font=w.toolTipMainValueFont;J.mainValue.color=w.toolTipMainValueColor;J.subValue={};J.subValue.font=w.toolTipSubValueFont;J.subValue.color=w.toolTipSubValueColor;J.text={};J.text.font=w.toolTipTextFont;J.text.color=w.toolTipTextColor;var K=w.axisLineColor;var L=w.axisLabelColor;var M=w.axisTitleColor;var N=w.axisGridLineColor;if(typeof x=='undefined'){x=[{}]}for(var i=0;i<x.length;i++){x[i].lineColor=K;x[i].labelColor=L;x[i].titleColor=M;if(typeof x[i].gridLine!=='undefined'){x[i].gridLine.majorColor=N;x[i].gridLine.minorColor=N;x[i].gridLine.subColor=N}};if(typeof y=='undefined'){y=[{}]}for(var i=0;i<y.length;i++){y[i].lineColor=K;y[i].labelColor=L;y[i].titleColor=M;if(typeof y[i].gridLine!=='undefined'){y[i].gridLine.majorColor=N;y[i].gridLine.minorColor=N;y[i].gridLine.subColor=N}};var O={layout:B,background:C,legend:D,title:I,measures:m,xAxis:x,yAxis:y,line:u,bar:v,selectability:{mode:r,deSelectable:p,defaultSelectedItems:q}};return O};
