/*!
 * CVOM HTML5 charts
 * 
 * 	(c) Copyright 2009-2012 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.service.visualization.Themings");jQuery.sap.require("sap.service.visualization.library");jQuery.sap.require("sap.ui.core.Element");sap.ui.core.Element.extend("sap.service.visualization.Themings",{metadata:{deprecated:true,library:"sap.service.visualization"}});
/*!
 * @copyright@
 */

sap.service.visualization.Themings.prototype.getCorrespondingThemings=function(c){var a=function(){};var b="sap.service.visualization."+c+":";a.bgColor=sap.ui.core.theming.Parameters.get(b+"bgColor");var f=sap.ui.core.theming.Parameters.get(b+"fontFamily");var p=sap.ui.core.theming.Parameters.get(b+"chartPadding").split(',');var d=[];for(var i=0;i<p.length;i++){d[i]=parseInt(p[i])};a.chartPadding=d;var l=sap.ui.core.theming.Parameters.get(b+"legendTitleFontSize");l=this.mapFontSize(l);a.legendTitleFont="bold "+l+" "+f;a.legendTitleFontColor=sap.ui.core.theming.Parameters.get(b+"legendTitleFontColor");var e=sap.ui.core.theming.Parameters.get(b+"legendFontSize");e=this.mapFontSize(e);a.legendFont="normal "+e+" "+f;a.legendColor=sap.ui.core.theming.Parameters.get(b+"legendColor");var m=sap.ui.core.theming.Parameters.get(b+"mainTitleFontSize");m=this.mapFontSize(m);a.mainTitleFont="normal "+m+" "+f;a.mainTitleColor=sap.ui.core.theming.Parameters.get(b+"mainTitleColor");var s=sap.ui.core.theming.Parameters.get(b+"subTitleFontSize");s=this.mapFontSize(s);a.subTitleFont="normal "+s+" "+f;a.subTitleColor=sap.ui.core.theming.Parameters.get(b+"subTitleColor");var t=sap.ui.core.theming.Parameters.get(b+"toolTipMainValueFontSize");t=this.mapFontSize(t);a.toolTipMainValueFont="normal "+t+" "+f;a.toolTipMainValueColor=sap.ui.core.theming.Parameters.get(b+"toolTipMainValueColor");var g=sap.ui.core.theming.Parameters.get(b+"toolTipSubValueFontSize");g=this.mapFontSize(g);a.toolTipSubValueFont="normal "+g+" "+f;a.toolTipSubValueColor=sap.ui.core.theming.Parameters.get(b+"toolTipSubValueColor");var h=sap.ui.core.theming.Parameters.get(b+"toolTipTextFontSize");h=this.mapFontSize(h);a.toolTipTextFont="normal "+h+" "+f;a.toolTipTextColor=sap.ui.core.theming.Parameters.get(b+"toolTipTextColor");a.axisLineColor=sap.ui.core.theming.Parameters.get(b+"axisLineColor");a.axisLabelColor=sap.ui.core.theming.Parameters.get(b+"axisLabelColor");a.axisTitleColor=sap.ui.core.theming.Parameters.get(b+"axisTitleColor");a.axisGridLineColor=sap.ui.core.theming.Parameters.get(b+"axisGridLineColor");for(prop in a){if(prop.indexOf("Color")!=-1||prop.indexOf('color')!=-1){a[prop]=this.mapColor(a[prop])}}return a};
sap.service.visualization.Themings.prototype.mapFontSize=function(f){var a=/(x{1,2}-)?(small|medium|large)/i;var s={"xx-small":'9px',"x-small":'10px',"small":'13px',"medium":'16px',"large":'18px',"x-large":'24px',"xx-large":'32px'};var m=a.exec(f);if(m==null){return f}else{return f=s[m[0].toLowerCase()]}};
sap.service.visualization.Themings.prototype.mapColor=function(h){var f=/(aqua|black|blue|fuchsia|gray|grey|green|lime|maroon|navy|olive|purple|red|silver|teal|white|yellow)/i;var c={"aqua":'#00FFFF',"black":'#000000',"blue":'#0000FF',"fuchsia":'#FF00FF',"gray":'#808080',"grey":'#808080',"green":'#008000',"lime":'#00FF00',"maroon":'#800000',"navy":'#000080',"olive":'#808000',"purple":'#800080',"red":'#FF0000',"silver":'#C0C0C0',"teal":'#008080',"white":'#FFFFFF',"yellow":'#FFFF00',"transparent":'rgba(0,0,0,0)'};var m=f.exec(h);if(m==null){return h}else{return h=c[m[0].toLowerCase()]}};
sap.service.visualization.Themings.prototype.applyCurrentThemeToXYChart=function(c,a){var t=new sap.service.visualization.Themings().getCorrespondingThemings(a);var b=t.chartPadding;var d=t.bgColor;var e=t.toolTipMainValueFont;var f=t.toolTipMainValueColor;var g=t.toolTipSubValueFont;var h=t.toolTipSubValueColor;var j=t.toolTipTextFont;var k=t.toolTipTextColor;var l=t.legendFont;var m=t.legendColor;var n=t.legendTitleFont;var o=t.legendTitleFontColor;var p=t.mainTitleColor;var q=t.mainTitleFont;var s=t.subTitleColor;var r=t.subTitleFont;var u=t.axisLineColor;var v=t.axisLabelColor;var w=t.axisTitleColor;var x=t.axisGridLineColor;var y=c.getXAxis();var z=c.getYAxis();for(var i=0;i<y.length;i++){y[i].lineColor=u;y[i].labelColor=v;y[i].titleColor=w;if(typeof y[i].gridLine!=='undefined'){y[i].gridLine.majorColor=x;y[i].gridLine.minorColor=x;y[i].gridLine.subColor=x}};for(var i=0;i<z.length;i++){z[i].lineColor=u;z[i].labelColor=v;z[i].titleColor=w;if(typeof z[i].gridLine!=='undefined'){z[i].gridLine.majorColor=x;z[i].gridLine.minorColor=x;z[i].gridLine.subColor=x}};var A={layout:{chartPadding:b},background:{color:d},tooltip:{text:{font:j,color:k},mainValue:{font:e,color:f},subValue:{font:g,color:h}},legend:{labelFont:l,labelColor:m,titleFont:n,titleFontColor:o},xAxis:y,yAxis:z,title:{main:{color:p,font:q},sub:{color:s,font:r}}};var B;switch(a){case'Bar':B=c.bar;break;case'Line':B=c.line;break;case'Column':B=c.column;break;case'Combination':B=c.combination;break}B.updateProperties(A)};
