/*!
 * SAP UI development toolkit for HTML5 (SAPUI5) (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.ushell.ui.launchpad.CatalogListItem");jQuery.sap.require("sap.ushell.library");jQuery.sap.require("sap.m.ListItemBase");sap.m.ListItemBase.extend("sap.ushell.ui.launchpad.CatalogListItem",{metadata:{library:"sap.ushell",properties:{"title":{type:"string",group:"Misc",defaultValue:null},"description":{type:"string",group:"Misc",defaultValue:null},"info":{type:"string",group:"Misc",defaultValue:null},"groupId":{type:"string",group:"Misc",defaultValue:null},"infoState":{type:"sap.ui.core.ValueState",group:"Misc",defaultValue:sap.ui.core.ValueState.None},"icon":{type:"sap.ui.core.URI",group:"Misc",defaultValue:null},"activeIcon":{type:"sap.ui.core.URI",group:"Misc",defaultValue:null},"iconInset":{type:"boolean",group:"Misc",defaultValue:true},"iconDensityAware":{type:"boolean",group:"Misc",defaultValue:true},"headerLevel":{type:"sap.m.HeaderLevel",group:"Misc",defaultValue:sap.m.HeaderLevel.H6},"editMode":{type:"boolean",group:"Misc",defaultValue:false},"allowEditMode":{type:"boolean",group:"Misc",defaultValue:true},"markChange":{type:"int",group:"Misc",defaultValue:0}},events:{"drop":{},"afterRendering":{},"press":{},"dblPress":{},"sapEnter":{},"sapEscape":{},"focusOut":{}}}});sap.ushell.ui.launchpad.CatalogListItem.M_EVENTS={'drop':'drop','afterRendering':'afterRendering','press':'press','dblPress':'dblPress','sapEnter':'sapEnter','sapEscape':'sapEscape','focusOut':'focusOut'};
// Copyright (c) 2013 SAP AG, All Rights Reserved
jQuery.sap.require("sap.ui.core.EnabledPropagator");jQuery.sap.require("sap.ui.core.IconPool");jQuery.sap.require('sap.ui.thirdparty.jqueryui.jquery-ui-core');jQuery.sap.require('sap.ui.thirdparty.jqueryui.jquery-ui-widget');jQuery.sap.require('sap.ui.thirdparty.jqueryui.jquery-ui-mouse');jQuery.sap.require('sap.ui.thirdparty.jqueryui.jquery-ui-droppable');
sap.ushell.ui.launchpad.CatalogListItem.prototype.init=function(){this.oEditInputField=new sap.m.Input();this.oEditInputField.setPlaceholder(sap.ushell.resources.i18n.getText("new_group_name"))};
sap.ushell.ui.launchpad.CatalogListItem.prototype.getEditInputField=function(){return this.oEditInputField};
sap.ushell.ui.launchpad.CatalogListItem.prototype.onAfterRendering=function(){this.$().droppable({hoverClass:"sapUshellCatalogLIHover",tolerance:"pointer",}).bind("drop",jQuery.proxy(this._handleDrop,this));this.fireAfterRendering()};
sap.ushell.ui.launchpad.CatalogListItem.prototype.onBeforeRendering=function(){this.$().unbind("drop",this._handleDrop).droppable("destroy");this.oEditInputField.setValue(this.getTitle())};
sap.ushell.ui.launchpad.CatalogListItem.prototype.exit=function(){this.$().unbind("drop",this._handleDrop).droppable("destroy");if(this._image){this._image.destroy()}sap.m.ListItemBase.prototype.exit.apply(this,arguments)};
sap.ushell.ui.launchpad.CatalogListItem.prototype._handleDrop=function(e,u){this.fireDrop({control:u&&u.draggable&&(u.draggable.length>0)&&sap.ui.getCore().byId(u.draggable[0].id)||undefined})};
sap.ushell.ui.launchpad.CatalogListItem.prototype._getImage=function(i,I,s,b){var o=this._image;if(o){o.setSrc(s);if(o instanceof sap.m.Image)o.setDensityAware(b)}else{o=sap.ui.core.IconPool.createControlByURI({id:i,src:s,densityAware:b},sap.m.Image).setParent(this,null,true)}if(o instanceof sap.m.Image){o.addStyleClass(I,true)}else{o.addStyleClass(I+"Icon",true)}return this._image=o};
sap.ushell.ui.launchpad.CatalogListItem.prototype._activeHandlingInheritor=function(){var i=sap.ui.getCore().byId(this.getId()+"-img");if(i instanceof sap.ui.core.Icon){i.$().toggleClass('sapMSLIIconActive',this._active);return}if(i&&this.getActiveIcon()){i.setSrc(this.getActiveIcon())}};
sap.ushell.ui.launchpad.CatalogListItem.prototype._inactiveHandlingInheritor=function(){var i=sap.ui.getCore().byId(this.getId()+"-img");if(i instanceof sap.ui.core.Icon){i.$().toggleClass('sapMSLIIconActive',this._active);return}if(i){i.setSrc(this.getIcon())}};
sap.ushell.ui.launchpad.CatalogListItem.prototype.onclick=function(b){this.firePress({id:this.getId()})};
sap.ushell.ui.launchpad.CatalogListItem.prototype.ondblclick=function(b){this.fireDblPress({id:this.getId()})};
sap.ushell.ui.launchpad.CatalogListItem.prototype.onsapenter=function(b){this.fireSapEnter({id:this.getId()})};
sap.ushell.ui.launchpad.CatalogListItem.prototype.onsapescape=function(b){this.fireSapEscape({id:this.getId()})};
sap.ushell.ui.launchpad.CatalogListItem.prototype.onfocusout=function(){this.fireFocusOut()};
sap.ushell.ui.launchpad.CatalogListItem.prototype.setDescription=function(d){var D=this.$().find('.sapUshellCatalogLIDescription');this.setProperty("description",d,true);if(this.getMarkChange()&&D.text()){this.addStyleClass("sapUshellCatalogLIRecentChange");window.clearTimeout(this.markChangeTimer);this.markChangeTimer=window.setTimeout($.proxy(this.removeStyleClass,this,"sapUshellCatalogLIRecentChange"),this.getMarkChange())}D.text(d);return this};
