/**
 * Node.js
 *
 * Copyright, Moxiecode Systems AB
 * Released under LGPL License.
 *
 * License: http://www.tinymce.com/license
 * Contributing: http://www.tinymce.com/contributing
 */
(function(t){var w=/^[ \t\r\n]*$/,a={'#text':3,'#comment':8,'#cdata':4,'#pi':7,'#doctype':10,'#document-fragment':11};function b(n,r,p){var s,c,d=p?'lastChild':'firstChild',e=p?'prev':'next';if(n[d])return n[d];if(n!==r){s=n[e];if(s)return s;for(c=n.parent;c&&c!==r;c=c.parent){s=c[e];if(s)return s}}};function N(n,c){this.name=n;this.type=c;if(c===1){this.attributes=[];this.attributes.map={}}}t.extend(N.prototype,{replace:function(n){var s=this;if(n.parent)n.remove();s.insert(n,s);s.remove();return s},attr:function(n,v){var s=this,c,i,u;if(typeof n!=="string"){for(i in n)s.attr(i,n[i]);return s}if(c=s.attributes){if(v!==u){if(v===null){if(n in c.map){delete c.map[n];i=c.length;while(i--){if(c[i].name===n){c=c.splice(i,1);return s}}}return s}if(n in c.map){i=c.length;while(i--){if(c[i].name===n){c[i].value=v;break}}}else c.push({name:n,value:v});c.map[n]=v;return s}else{return c.map[n]}}},clone:function(){var s=this,c=new N(s.name,s.type),i,l,d,e,f;if(d=s.attributes){f=[];f.map={};for(i=0,l=d.length;i<l;i++){e=d[i];if(e.name!=='id'){f[f.length]={name:e.name,value:e.value};f.map[e.name]=e.value}}c.attributes=f}c.value=s.value;c.shortEnded=s.shortEnded;return c},wrap:function(c){var s=this;s.parent.insert(c,s);c.append(s);return s},unwrap:function(){var s=this,n,c;for(n=s.firstChild;n;){c=n.next;s.insert(n,s,true);n=c}s.remove()},remove:function(){var s=this,p=s.parent,n=s.next,c=s.prev;if(p){if(p.firstChild===s){p.firstChild=n;if(n)n.prev=null}else{c.next=n}if(p.lastChild===s){p.lastChild=c;if(c)c.next=null}else{n.prev=c}s.parent=s.next=s.prev=null}return s},append:function(n){var s=this,l;if(n.parent)n.remove();l=s.lastChild;if(l){l.next=n;n.prev=l;s.lastChild=n}else s.lastChild=s.firstChild=n;n.parent=s;return n},insert:function(n,r,c){var p;if(n.parent)n.remove();p=r.parent||this;if(c){if(r===p.firstChild)p.firstChild=n;else r.prev.next=n;n.prev=r.prev;n.next=r;r.prev=n}else{if(r===p.lastChild)p.lastChild=n;else r.next.prev=n;n.next=r.next;n.prev=r;r.next=n}n.parent=p;return n},getAll:function(n){var s=this,c,d=[];for(c=s.firstChild;c;c=b(c,s)){if(c.name===n)d.push(c)}return d},empty:function(){var s=this,n,i,c;if(s.firstChild){n=[];for(c=s.firstChild;c;c=b(c,s))n.push(c);i=n.length;while(i--){c=n[i];c.parent=c.firstChild=c.lastChild=c.next=c.prev=null}}s.firstChild=s.lastChild=null;return s},isEmpty:function(e){var s=this,n=s.firstChild,i,c;if(n){do{if(n.type===1){if(n.attributes.map['data-mce-bogus'])continue;if(e[n.name])return false;i=n.attributes.length;while(i--){c=n.attributes[i].name;if(c==="name"||c.indexOf('data-mce-')===0)return false}}if(n.type===8)return false;if((n.type===3&&!w.test(n.value)))return false}while(n=b(n,s))}return true},walk:function(p){return b(this,null,p)}});t.extend(N,{create:function(n,c){var d,e;d=new N(n,a[n]||1);if(c){for(e in c)d.attr(e,c[e])}return d}});t.html.Node=N})(tinymce);
