/**
 * Styles.js
 *
 * Copyright, Moxiecode Systems AB
 * Released under LGPL License.
 *
 * License: http://www.tinymce.com/license
 * Contributing: http://www.tinymce.com/contributing
 */
tinymce.html.Styles=
function(s,d){var e=/rgb\s*\(\s*([0-9]+)\s*,\s*([0-9]+)\s*,\s*([0-9]+)\s*\)/gi,u=/(?:url(?:(?:\(\s*\"([^\"]+)\"\s*\))|(?:\(\s*\'([^\']+)\'\s*\))|(?:\(\s*([^)\s]+)\s*\))))|(?:\'([^\']+)\')|(?:\"([^\"]+)\")/gi,f=/\s*([^:]+):\s*([^;]+);?/g,t=/\s+$/,h=/rgb/,j,i,k={},m;s=s||{};m='\\" \\\' \\; \\: ; : \uFEFF'.split(' ');for(i=0;i<m.length;i++){k[m[i]]='\uFEFF'+i;k['\uFEFF'+i]=m[i]}function n(a,r,g,b){function c(v){v=parseInt(v).toString(16);return v.length>1?v:'0'+v};return'#'+c(r)+c(g)+c(b)};return{toHex:function(c){return c.replace(e,n)},parse:function(g){var l={},o,p,v,q,r=s.url_converter,w=s.url_converter_scope||this;function x(a,b){var c,D,E,F;c=l[a+'-top'+b];if(!c)return;D=l[a+'-right'+b];if(c!=D)return;E=l[a+'-bottom'+b];if(D!=E)return;F=l[a+'-left'+b];if(E!=F)return;l[a+b]=F;delete l[a+'-top'+b];delete l[a+'-right'+b];delete l[a+'-bottom'+b];delete l[a+'-left'+b]};function y(a){var v=l[a],i;if(!v||v.indexOf(' ')<0)return;v=v.split(' ');i=v.length;while(i--){if(v[i]!==v[0])return false}l[a]=v[0];return true};function z(D,a,b,c){if(!y(a))return;if(!y(b))return;if(!y(c))return;l[D]=l[a]+' '+l[b]+' '+l[c];delete l[a];delete l[b];delete l[c]};function A(a){q=true;return k[a]};function B(a,b){if(q){a=a.replace(/\uFEFF[0-9]/g,function(a){return k[a]})}if(!b)a=a.replace(/\\([\'\";:])/g,"$1");return a};function C(a,b,c,D,E,F){E=E||F;if(E){E=B(E);return"'"+E.replace(/\'/g,"\\'")+"'"}b=B(b||c||D);if(r)b=r.call(w,b,'style');return"url('"+b.replace(/\'/g,"\\'")+"')"};if(g){g=g.replace(/\\[\"\';:\uFEFF]/g,A).replace(/\"[^\"]+\"|\'[^\']+\'/g,function(a){return a.replace(/[;:]/g,A)});while(o=f.exec(g)){p=o[1].replace(t,'').toLowerCase();v=o[2].replace(t,'');if(p&&v.length>0){if(p==='font-weight'&&v==='700')v='bold';else if(p==='color'||p==='background-color')v=v.toLowerCase();v=v.replace(e,n);v=v.replace(u,C);l[p]=q?B(v,true):v}f.lastIndex=o.index+o[0].length}x("border","");x("border","-width");x("border","-color");x("border","-style");x("padding","");x("margin","");z('border','border-width','border-style','border-color');if(l.border==='medium none')delete l.border}return l},serialize:function(a,b){var c='',g,v;function o(g){var p,i,l,v;p=d.styles[g];if(p){for(i=0,l=p.length;i<l;i++){g=p[i];v=a[g];if(v!==j&&v.length>0)c+=(c.length>0?' ':'')+g+': '+v+';'}}};if(b&&d&&d.styles){o('*');o(b)}else{for(g in a){v=a[g];if(v!==j&&v.length>0)c+=(c.length>0?' ':'')+g+': '+v+';'}}return c}}}
;
