/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.ui.commons.RadioButtonRenderer");jQuery.sap.require("sap.ui.core.ValueStateSupport");sap.ui.commons.RadioButtonRenderer={};
sap.ui.commons.RadioButtonRenderer.render=function(r,R){var a=r;if(!R.getVisible()){return}var i=R.getId();var t=R.getTooltip_AsString();a.addClass("sapUiRb");a.write("<span");a.writeControlData(R);a.writeAccessibilityState(R,{role:"radio",checked:R.getSelected()===true,invalid:R.getValueState()==sap.ui.core.ValueState.Error,disabled:!R.getEditable(),labelledby:i+"-label",describedby:t?i+"-Descr":undefined});var e=R.getEnabled()!=null&&R.getEnabled();var b=R.getEditable()!=null&&R.getEditable();var c=false;var d=false;if(R.getValueState()!=null){c=sap.ui.core.ValueState.Error==R.getValueState();d=sap.ui.core.ValueState.Warning==R.getValueState()}if(R.getSelected()){a.addClass("sapUiRbSel")}var m=0;var f=false;if(!e){m=-1;f=true;a.addClass("sapUiRbDis")}if(!b){f=true;a.addClass("sapUiRbRo")}if(c){a.addClass("sapUiRbErr")}else if(d){a.addClass("sapUiRbWarn")}if(e&&b&&!c&&!d){a.addClass("sapUiRbStd")}if(e&&b){a.addClass("sapUiRbInteractive")}a.writeClasses();if(R.getWidth()&&R.getWidth()!=''){a.writeAttribute("style","width:"+R.getWidth()+";")}a.writeAttribute("tabIndex",m);var g=sap.ui.core.ValueStateSupport.enrichTooltip(R,t?t:R.getText());if(g){a.writeAttributeEscaped("title",g)}a.write(">");a.write("<input type='radio' tabindex='-1' id='");a.write(i);a.write("-RB' name=\"");a.writeEscaped(R.getGroupName());a.write("\" ");if(R.getSelected()){a.write(" checked='checked'")}if(!e){a.write(" disabled='disabled'")}if(f){a.write(" readonly='readonly'");a.write(" disabled='disabled'")}if(R.getKey()){a.writeAttributeEscaped("value",R.getKey())}a.write(" />");a.write("<label id=\""+i+"-label\"");a.writeAttribute("for",i+"-RB");if(!R.getText()){a.write(" class=\"sapUiRbNoText\"")}a.write(">");if(R.getText()){this.renderText(a,R.getText(),R.getTextDirection())}a.write("</label>");if(t){a.write("<span id=\""+i+"-Descr\" style=\"visibility: hidden; display: none;\">");a.writeEscaped(t);a.write("</span>")}a.write("</span>")};
sap.ui.commons.RadioButtonRenderer.renderText=function(r,t,e){var a=r;if(!e||e==sap.ui.core.TextDirection.Inherit){a.writeEscaped(t)}else{a.write("<span dir=\""+e+"\">");a.writeEscaped(t);a.write("</span>")}};
sap.ui.commons.RadioButtonRenderer.setSelected=function(r,s){var i=r.getId();jQuery.sap.byId(i).toggleClass('sapUiRbSel',s).attr('aria-checked',s);var d=jQuery.sap.domById(i+'-RB');if(s){d.checked=true;d.setAttribute('checked','checked')}else{d.checked=false;d.removeAttribute('checked')}};
