/*!
 * SAP UI development toolkit for HTML5 (SAPUI5) (c) Copyright
 * 		2009-2012 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.ca.ui.charts.ClusterListItemRenderer");jQuery.sap.require("sap.ui.core.Renderer");jQuery.sap.require("sap.m.ListItemBaseRenderer");sap.ca.ui.charts.ClusterListItemRenderer=sap.ui.core.Renderer.extend(sap.m.ListItemBaseRenderer);
sap.ca.ui.charts.ClusterListItemRenderer.renderLIAttributes=function(r,l){r.addClass("sapMCLI")};
sap.ca.ui.charts.ClusterListItemRenderer.renderLIContent=function(r,l){var t=l.getTitle();if(t){r.write("<div");r.writeAttributeEscaped("for",l.getId()+"-title");r.writeAttributeEscaped("class","sapMCLITitle");r.write(">");r.writeEscaped(t);r.write("</div>")}this.renderLIItems(r,l,l.getItems())};
sap.ca.ui.charts.ClusterListItemRenderer.renderLIItems=function(r,l,i){if(typeof i==="undefined"){return}for(var n in i){var I=i[n];var s=I["items"];var L=typeof s==="undefined";if(L){var a=I["label"];var v=I["value"];var c=I["color"];r.write("<div");r.writeAttributeEscaped("id",l.getId()+"-item");r.writeAttributeEscaped("class","sapMCLIItem");r.write(">");r.write("<div");r.writeAttributeEscaped("id",l.getId()+"-icon");r.writeAttributeEscaped("class","sapMCLIIcon");r.write(">");r.write("<div");r.writeAttributeEscaped("id",l.getId()+"-colorBox");r.writeAttributeEscaped("class","sapMCLIColorBox");r.writeAttributeEscaped("style","background: "+sap.ca.ui.charts.ClusterListItemRenderer.formatColor(c));r.write(">");r.write("</div>");r.write("</div>");if(a){r.write("<label");r.writeAttributeEscaped("for",l.getId()+"-label");r.writeAttributeEscaped("class","sapMCLIGroup");r.write(">");r.writeEscaped(a);r.write("</label>")}if(v){r.write("<div");r.writeAttributeEscaped("for",l.getId()+"-value");r.writeAttributeEscaped("class","sapMCLIValue");r.write(">");r.writeEscaped(v);r.write("</div>")}r.write("</div>")}else{var t=I["title"];if(t){r.write("<div");r.writeAttributeEscaped("for",l.getId()+"-title");r.writeAttributeEscaped("class","sapMCLITitle");r.write(">");r.writeEscaped(t);r.write("</div>")}this.renderLIItems(r,l,s)}}};
sap.ca.ui.charts.ClusterListItemRenderer.formatColor=function(c){if(typeof c==="string"){return c}if(typeof c!=="number"){return"#ffffff"}var C=c.toString(16);while(C.length<6){C="0"+C}return"#"+C};
