/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.m.Bar");jQuery.sap.require("sap.m.library");jQuery.sap.require("sap.ui.core.Control");sap.ui.core.Control.extend("sap.m.Bar",{metadata:{library:"sap.m",properties:{"enableFlexBox":{type:"boolean",group:"Misc",defaultValue:false,deprecated:true},"translucent":{type:"boolean",group:"Appearance",defaultValue:false}},aggregations:{"contentLeft":{type:"sap.ui.core.Control",multiple:true,singularName:"contentLeft"},"contentMiddle":{type:"sap.ui.core.Control",multiple:true,singularName:"contentMiddle"},"contentRight":{type:"sap.ui.core.Control",multiple:true,singularName:"contentRight"}}}});
sap.m.Bar.prototype.init=function(){};
sap.m.Bar.prototype.onBeforeRendering=function(){this._removeAllListeners()};
sap.m.Bar.prototype.onAfterRendering=function(){this._updatePosition()};
sap.m.Bar.prototype.exit=function(){this._removeAllListeners()};
sap.m.Bar._aResizeHandlers=["_sResizeListenerId","_sResizeListenerIdMid","_sResizeListenerIdRight","_sResizeListenerIdLeft"];
sap.m.Bar.prototype._removeAllListeners=function(){var t=this;sap.m.Bar._aResizeHandlers.forEach(function(i){t._removeListenerFailsave(i)})};
sap.m.Bar.prototype._removeListenerFailsave=function(l){if(this[l]){sap.ui.core.ResizeHandler.deregister(this[l]);this[l]=null}};
sap.m.Bar.prototype._updatePosition=function(){this._removeAllListeners();var $=this.$();if(!this.getDomRef()){return}var b=$.outerWidth(true);var a=jQuery.sap.byId(this.getId()+"-BarLeft");var c=jQuery.sap.byId(this.getId()+"-BarRight");var d=jQuery.sap.byId(this.getId()+"-BarPH");var C=!!this.getContentLeft().length,e=!!d.children().length,f=!!this.getContentRight().length;if(!C&&!f){d.css({'width':'100%'})}else if(C&&!e&!f){a.css({'width':'100%'})}else if(!C&&!e&f){c.css({'width':'100%'})}else{a.css({'width':'auto'});var l=a.children();var L=0;var g=0;if(sap.ui.Device.browser.webkit){for(var i=0;i<l.length;i++){L+=jQuery(l[i]).outerWidth(true)}g=a.outerWidth(true)}else{var o=null;for(var i=0;i<l.length;i++){o=window.getComputedStyle(l[i]);if(o.width=="auto"){L+=jQuery(l[i]).width()+1}else{L+=parseFloat(o.width)}L+=parseFloat(o.marginLeft);L+=parseFloat(o.marginRight);L+=parseFloat(o.paddingLeft);L+=parseFloat(o.paddingRight)}var h=window.getComputedStyle(jQuery.sap.domById(this.getId()+"-BarLeft"));g+=parseFloat(h.width);g+=parseFloat(h.marginLeft);g+=parseFloat(h.marginRight);g+=parseFloat(h.paddingLeft);g+=parseFloat(h.paddingRight)}if(g<L){g=L;a.css({'width':g})}var j=jQuery.sap.byId(this.getId()+"-BarMiddle");var m=j.outerWidth(true);d.css({'position':'static','width':'auto','visibility':'hidden'});var M=d.outerWidth(true);var k=d.position();c.css({'width':'auto'});var r=c.outerWidth(true);var R=c.position();var n=a.position();if(this.getEnableFlexBox()){d.css({'position':'absolute','left':g});d.width(b-g-r-parseInt(d.css('margin-left'),10)-parseInt(d.css('margin-right'),10))}else{var p=sap.ui.getCore().getConfiguration().getRTL();if(p?(Math.round(n.left)+g>=b):(Math.round(R.left)+r>=b)){if(b<(g+r)){if(r>b){c.width(b);a.width(0)}else{a.width(b-r)}}if(!p&&k.left<g){d.css({'position':'absolute','left':g});k=d.position()}else if(p&&k.left<=r){d.css({'position':'absolute','left':r});k=d.position()}if(!p){if((k.left+M)>R.left){if(R.left<k.left){d.width(0)}else{d.width(R.left-k.left)}}}else{if((k.left+M)>n.left){if(n.left<k.left){d.width(0)}else{d.width(n.left-k.left)}}}if(d.outerWidth()>m){d.width(m)}}}d.css({'visibility':'inherit'})}this._sResizeListenerId=sap.ui.core.ResizeHandler.register(this.getDomRef(),jQuery.proxy(this._updatePosition,this));if(this.getEnableFlexBox()){return}if(C){this._sResizeListenerIdLeft=sap.ui.core.ResizeHandler.register(a[0],jQuery.proxy(this._updatePosition,this))}if(e){this._sResizeListenerIdMid=sap.ui.core.ResizeHandler.register(d[0],jQuery.proxy(this._updatePosition,this))}if(f){this._sResizeListenerIdRight=sap.ui.core.ResizeHandler.register(c[0],jQuery.proxy(this._updatePosition,this))}};
