/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.m.SegmentedButton");jQuery.sap.require("sap.m.library");jQuery.sap.require("sap.ui.core.Control");sap.ui.core.Control.extend("sap.m.SegmentedButton",{metadata:{publicMethods:["createButton"],library:"sap.m",properties:{"width":{type:"sap.ui.core.CSSSize",group:"Misc",defaultValue:null},"visible":{type:"boolean",group:"Appearance",defaultValue:true}},defaultAggregation:"buttons",aggregations:{"buttons":{type:"sap.m.Button",multiple:true,singularName:"button"}},associations:{"selectedButton":{type:"sap.m.Button",multiple:false}},events:{"select":{}}}});sap.m.SegmentedButton.M_EVENTS={'select':'select'};jQuery.sap.require("sap.ui.core.delegate.ItemNavigation");
sap.m.SegmentedButton.prototype.init=function(){if(jQuery.os.android||jQuery.os.blackberry){sap.m.SegmentedButton.prototype.ontouchstart=this._ontouchstart;sap.m.SegmentedButton.prototype.ontouchend=this._ontouchend}if(jQuery.browser.msie&&jQuery.browser.fVersion<=10){this._isMie=true}this._aButtonWidth=[];var s;this._oGhostButton;var a=this;if(jQuery("#segMtBtn_calc").length==0){this._oGhostButton=document.createElement("Button");var b=document.createElement("span");jQuery(b).addClass("sapMBtnContent");this._oGhostButton.appendChild(b);this._oGhostButton.setAttribute("id","segMtBtn_calc");jQuery(this._oGhostButton).addClass("sapMBtn sapMBtnDefault sapMBtnPaddingLeft");this._oGhostButton=jQuery(this._oGhostButton)}else{this._oGhostButton=jQuery("#segMtBtn_calc")}this._oItemNavigation=new sap.ui.core.delegate.ItemNavigation();this._oItemNavigation.setCycling(true);this.addDelegate(this._oItemNavigation)};
sap.m.SegmentedButton.prototype.onBeforeRendering=function(){var s=sap.ui.getCore().getStaticAreaRef();if(this._sResizeListenerId){sap.ui.core.ResizeHandler.deregister(this._sResizeListenerId);this._sResizeListenerId=null}if(jQuery("#segMtBtn_calc").length==0){s.appendChild(this._oGhostButton[0])}var b=this.getButtons();var a=this;if(a._oGhostButton.length==0){return}else{for(var i=0;i<b.length;i++){a._setGhostButtonText(b[i])}}};
sap.m.SegmentedButton.prototype._setGhostButtonText=function(b){var t=b.getText();var g=jQuery("#segMtBtn_calc");if(b.getIcon()===""){g.find("span").text(t);this._aButtonWidth.push(g.width())}else{this._aButtonWidth.push(0)}};
sap.m.SegmentedButton.prototype.onAfterRendering=function(){if(!this._sResizeListenerId){var p=this.getParent(),P;if(p instanceof sap.ui.core.Control){P=p.getDomRef()}else if(p instanceof sap.ui.core.UIArea){P=p.getRootNode()}if(P){this._sResizeListenerId=sap.ui.core.ResizeHandler.register(P,jQuery.proxy(this._fHandleResize,this))}}this._bInsideBar=(this.$().closest('.sapMBar').length>0)?true:false;var b=this.getButtons();var a=true;var s=this;for(var i=0;i<b.length;i++){if(b[i].getIcon()==""){a=false}}if(a){this.$().toggleClass("sapMSegBIcons",true)}if(this._isMie){setTimeout(function(){s._fCalcBtnWidth()},0)}else{s._fCalcBtnWidth()}this.$().removeClass("sapMSegBHide");this._setItemNavigation()};
sap.m.SegmentedButton.prototype.onThemeChanged=function(e){};
sap.m.SegmentedButton.prototype._fCalcBtnWidth=function(){var I=this.getButtons().length;if(I===0||!this.$().is(":visible")){return}var m=5,$=this.$(),p=0,c=$.outerWidth(true)-$.width(),a=$.children('#'+this.getButtons()[0].getId()).outerWidth(true)-$.children('#'+this.getButtons()[0].getId()).width();p=(jQuery(window).width()<$.parent().outerWidth())?jQuery(window).width():$.parent().width();if(this.getWidth()&&this.getWidth().indexOf("%")===-1){m=parseInt(this.getWidth())/I;var M=Math.max.apply(null,this._aButtonWidth);m=m-M}else{m=Math.max.apply(null,this._aButtonWidth);if(((p-c)>m*I||this._bInsideBar)&&this.getWidth().indexOf("%")===-1){m=m}else{m=(p-c)/I;m=m-a}}for(var i=0;i<I;i++){if(!isNaN(m)&&m>0){m=this._isMie?m+2:m;$.children('#'+this.getButtons()[i].getId()).width(m)}}};
sap.m.SegmentedButton.prototype._fHandleResize=function(){this._fCalcBtnWidth()};
sap.m.SegmentedButton.prototype.exit=function(){if(this._sResizeListenerId){sap.ui.core.ResizeHandler.deregister(this._sResizeListenerId);this._sResizeListenerId=null}if(this._oGhostButton){jQuery("#segMtBtn_calc").remove();this._oGhostButton=null}if(this._oItemNavigation){this.removeDelegate(this._oItemNavigation);this._oItemNavigation.destroy();delete this._oItemNavigation}};
sap.m.SegmentedButton.prototype._setItemNavigation=function(){var b,d=this.getDomRef();if(d){this._oItemNavigation.setRootDomRef(d);b=d.getElementsByTagName("li");this._oItemNavigation.setItemDomRefs(b);this._focusSelectedButton()}};
sap.m.SegmentedButton.prototype.createButton=function(t,u,e){var b=new sap.m.Button();if(u===null&&t!==null){b.setText(t)}else if(u!==null&&t===null){b.setIcon(u)}else throw new Error("in control: "+this.toString()+": method createButton() just accepts text or icon");if(e||e===undefined){b.setEnabled(true)}else{b.setEnabled(false)}this.addButton(b);return b};
sap.m.SegmentedButton.prototype.addButton=function(b){var t=this;b.attachPress(function(e){t.$().children().removeClass('sapMSegBBtnSel');e.getSource().$().addClass('sapMSegBBtnSel');if(t.getSelectedButton()!==e.getSource().getId()){t.setAssociation('selectedButton',e.getSource(),true);t.fireSelect({button:e.getSource(),id:e.getSource().getId()})}});this.addAggregation('buttons',b);return this};
sap.m.SegmentedButton.prototype.insertButton=function(b){var t=this;b.attachPress(function(e){t.$().children().removeClass('sapMSegBBtnSel');e.getSource().$().addClass('sapMSegBBtnSel');if(t.getSelectedButton()!==e.getSource().getId()){t.setAssociation('selectedButton',e.getSource(),true);t.fireSelect({button:e.getSource(),id:e.getSource().getId()})}});this.insertAggregation('buttons',b);return this};
sap.m.SegmentedButton.prototype.setSelectedButton=function(b){this.setAssociation("selectedButton",b,true);this._focusSelectedButton()};
sap.m.SegmentedButton.prototype._focusSelectedButton=function(){var b=this.getButtons();var s=this.getSelectedButton();for(var i=0;i<b.length;i++){if(b[i]&&b[i].getId()===s){this._oItemNavigation.setFocusedIndex(i);break}}};
sap.m.SegmentedButton.prototype._ontouchstart=function(e){if(e.srcControl.getEnabled())jQuery(e.target).toggleClass('sapMSegBBtnTouched',true)};
sap.m.SegmentedButton.prototype._ontouchend=function(e){if(e.srcControl.getEnabled())jQuery(e.target).toggleClass('sapMSegBBtnTouched',false)};
