/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.m.TableSelectDialog");jQuery.sap.require("sap.m.library");jQuery.sap.require("sap.ui.core.Control");sap.ui.core.Control.extend("sap.m.TableSelectDialog",{metadata:{publicMethods:["open"],library:"sap.m",properties:{"title":{type:"string",group:"Appearance",defaultValue:null},"noDataText":{type:"string",group:"Appearance",defaultValue:null},"multiSelect":{type:"boolean",group:"Dimension",defaultValue:false},"growingThreshold":{type:"int",group:"Misc",defaultValue:null}},defaultAggregation:"items",aggregations:{"items":{type:"sap.m.ColumnListItem",multiple:true,singularName:"item",bindable:"bindable"},"_dialog":{type:"sap.ui.core.Control",multiple:false,visibility:"hidden"},"columns":{type:"sap.m.Column",multiple:true,singularName:"column",bindable:"bindable"}},events:{"confirm":{},"search":{},"liveChange":{},"cancel":{}}}});sap.m.TableSelectDialog.M_EVENTS={'confirm':'confirm','search':'search','liveChange':'liveChange','cancel':'cancel'};
/*!
 * @copyright@
 */
jQuery.sap.require("sap.m.Button");jQuery.sap.require("sap.m.Dialog");jQuery.sap.require("sap.m.Table");jQuery.sap.require("sap.m.SearchField");
sap.m.TableSelectDialog.prototype.init=function(){var t=this,l=0;var r=function(){t._selectedItem=t._table.getSelectedItem();t._dialog.detachAfterClose(r);t.fireConfirm({selectedItem:t._selectedItem,selectedItems:t._selectedItems})};this._bAppendedToUIArea=false;this._oRb=sap.ui.getCore().getLibraryResourceBundle("sap.m");this._table=new sap.m.Table(this.getId()+"-table",{growing:true,growingScrollToLoad:true,noDataText:this.getNoDataText(),mode:sap.m.ListMode.SingleSelectMaster,selectionChange:function(e){var s=e.getParameter("listItem");if(t._dialog){if(!t.getMultiSelect()){t._dialog.attachAfterClose(r);t._dialog.close()}}}});this._busyIndicator=new sap.m.BusyIndicator(this.getId()+"-busyIndicator").addStyleClass("sapMTableSelectDialogBusyIndicator",true);this._searchField=new sap.m.SearchField(this.getId()+"-searchField",{width:"100%",liveChange:function(e){var v=e.getSource().getValue(),d=(v?300:0);clearTimeout(l);if(d){l=setTimeout(function(){t._executeSearch(v,"liveChange")},d)}else{t._executeSearch(v,"liveChange")}},search:function(e){t._executeSearch(e.getSource().getValue(),"search")}});this._subHeader=new sap.m.Bar(this.getId()+"-subHeader",{contentMiddle:[this._searchField]});this._dialog=new sap.m.Dialog(this.getId()+"-dialog",{stretch:jQuery.device.is.phone,contentHeight:"2000px",subHeader:this._subHeader,content:[this._busyIndicator,this._table],leftButton:this.getCancelButton()});this._dialog._iVMargin=8*parseInt(sap.ui.core.theming.Parameters.get("sapUiFontSize")||16,10);this._searchFieldValue="";this._searchFieldLastEventType="";this._firstRequest=true;this._tableUpdateRequested=0};
sap.m.TableSelectDialog.prototype.exit=function(){this._table=null;this._searchField=null;this._subHeader=null;this._busyIndicator=null;this._firstRequest=null;this._tableUpdateRequested=null;this._searchFieldValue=null;this._searchFieldLastEventType=null;if(this._dialog){this._dialog.destroy();this._dialog=null}if(this._okButton){this._okButton.destroy();this._okButton=null}};
sap.m.TableSelectDialog.prototype.open=function(s){if(!this._bAppendedToUIArea){var S=sap.ui.getCore().getStaticAreaRef();S=sap.ui.getCore().getUIArea(S);S.addContent(this,true);this._bAppendedToUIArea=true}this._table.removeSelections();delete this._selectedItem;delete this._selectedItems;this._searchFieldLastEventType="";this._firstRequest=true;this._tableUpdateRequested=0;this._searchField.setValue(s);this._dialog.open();return this};
sap.m.TableSelectDialog.prototype.setGrowingThreshold=function(v){this._table.setGrowingThreshold(v);this.setProperty("growingThreshold",v,true);return this};
sap.m.TableSelectDialog.prototype.getOkButton=function(){var t=this;var o=function(){t._selectedItem=t._table.getSelectedItem();t._selectedItems=t._table.getSelectedItems();t._dialog.detachAfterClose(o);t.fireConfirm({selectedItem:t._selectedItem,selectedItems:t._selectedItems})};if(!this._okButton){this._okButton=new sap.m.Button(this.getId()+"-ok",{text:this._oRb.getText("MSGBOX_OK"),press:function(){t._dialog.attachAfterClose(o);t._dialog.close()}})}return this._okButton};
sap.m.TableSelectDialog.prototype.getCancelButton=function(){var t=this;var c=function(){t._selectedItem=null;t._selectedItems=new Array();t._searchFieldValue=null;t._dialog.detachAfterClose(c);t.fireCancel()};if(!this._cancelButton){this._cancelButton=new sap.m.Button(this.getId()+"-cancel",{text:this._oRb.getText("MSGBOX_CANCEL"),press:function(){t._dialog.attachAfterClose(c);t._dialog.close()}})}return this._cancelButton};
sap.m.TableSelectDialog.prototype.setMultiSelect=function(m){this.setProperty("multiSelect",m,true);if(m){this._table.setMode(sap.m.ListMode.MultiSelect);this._table.setIncludeItemInSelection(true);this._dialog.setRightButton(this.getCancelButton());this._dialog.setLeftButton(this.getOkButton())}else{this._table.setMode(sap.m.ListMode.SingleSelectMaster);this._dialog.setLeftButton(this.getCancelButton())}};
sap.m.TableSelectDialog.prototype.setTitle=function(t){this.setProperty("title",t,true);this._dialog.setTitle(t)};
sap.m.TableSelectDialog.prototype.setNoDataText=function(n){this.setProperty("noDataText",n,true);this._table.setNoDataText(n)};
sap.m.TableSelectDialog.prototype._setModel=sap.m.TableSelectDialog.prototype.setModel;
sap.m.TableSelectDialog.prototype.setModel=function(m,n){var a=Array.prototype.slice.call(arguments),r;r=this._table.setModel(m,n);this._tableUpdateRequested+=1;m.attachRequestSent(this._requestSent,this);m.attachRequestCompleted(this._requestCompleted,this);return r&&sap.m.TableSelectDialog.prototype._setModel.apply(this,a)};
sap.m.TableSelectDialog.prototype._callMethodInManagedObject=function(f,a){var b=Array.prototype.slice.call(arguments);if(a==="items"){return this._table[f].apply(this._table,b.slice(1))}else if(a==="columns"){return this._table[f].apply(this._table,b.slice(1))}else{return sap.ui.base.ManagedObject.prototype[f].apply(this,b.slice(1))}};
sap.m.TableSelectDialog.prototype.bindAggregation=function(n,b){var a=Array.prototype.slice.call(arguments);this._callMethodInManagedObject.apply(this,["bindAggregation"].concat(a));return this};
sap.m.TableSelectDialog.prototype.validateAggregation=function(a,o,m){return this._callMethodInManagedObject("validateAggregation",a,o,m)};
sap.m.TableSelectDialog.prototype.setAggregation=function(a,o,s){this._callMethodInManagedObject("setAggregation",a,o,s);return this};
sap.m.TableSelectDialog.prototype.getAggregation=function(a,d){return this._callMethodInManagedObject("getAggregation",a,d)};
sap.m.TableSelectDialog.prototype.indexOfAggregation=function(a,o){return this._callMethodInManagedObject("indexOfAggregation",a,o)};
sap.m.TableSelectDialog.prototype.insertAggregation=function(a,o,i,s){this._callMethodInManagedObject("insertAggregation",a,o,i,s);return this};
sap.m.TableSelectDialog.prototype.addAggregation=function(a,o,s){this._callMethodInManagedObject("addAggregation",a,o,s);return this};
sap.m.TableSelectDialog.prototype.removeAggregation=function(a,o,s){return this._callMethodInManagedObject("removeAggregation",a,o,s)};
sap.m.TableSelectDialog.prototype.removeAllAggregation=function(a,s){return this._callMethodInManagedObject("removeAllAggregation",a,s)};
sap.m.TableSelectDialog.prototype.destroyAggregation=function(a,s){this._callMethodInManagedObject("destroyAggregation",a,s);return this};
sap.m.TableSelectDialog.prototype.getBinding=function(n){return this._callMethodInManagedObject("getBinding",n)};
sap.m.TableSelectDialog.prototype.getBindingContext=function(n){return this._callMethodInManagedObject("getBindingContext",n)};
sap.m.TableSelectDialog.prototype.getBindingInfo=function(n){return this._callMethodInManagedObject("getBindingInfo",n)};
sap.m.TableSelectDialog.prototype.getBindingPath=function(n){return this._callMethodInManagedObject("getBindingPath",n)};
sap.m.TableSelectDialog.prototype.setBindingContext=function(c,n){this._callMethodInManagedObject("setBindingContext",c,n);return this};
sap.m.TableSelectDialog.prototype.setBindingContext=function(c,n){this._callMethodInManagedObject("setBindingContext",c,n);return this};
sap.m.TableSelectDialog.prototype._executeSearch=function(v,e){var t=this._table,a=(t?t.getBinding("items"):undefined),s=(this._searchFieldValue!==v);if(this._dialog.isOpen()&&((s&&e==="liveChange")||e==="search")){this._searchFieldValue=v;if(a){this._tableUpdateRequested+=1;if(e=="search"){this.fireSearch({value:v,itemsBinding:a})}else if(e=="liveChange"){this.fireLiveChange({value:v,itemsBinding:a})}}}this._searchFieldLastEventType=e};
sap.m.TableSelectDialog.prototype._requestSent=function(e){if(this._dialog.isOpen()&&this._tableUpdateRequested){if(this._firstRequest){this._subHeader.$().css('display','none')}this._table.addStyleClass('sapMTableSelectDialogTableHide');this._busyIndicator.$().css('display','inline-block')}};
sap.m.TableSelectDialog.prototype._requestCompleted=function(e){if(this._dialog.isOpen()&&this._tableUpdateRequested){if(this._firstRequest){this._subHeader.$().css('display','block');this._firstRequest=false}this._table.removeStyleClass('sapMTableSelectDialogTableHide');this._busyIndicator.$().css('display','none');this._tableUpdateRequested-=1}};
sap.m.TableSelectDialog.prototype.invalidate=function(){if(this._dialog){this._dialog.invalidate(arguments)}};
