/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.m.Bar");jQuery.sap.require("sap.m.library");jQuery.sap.require("sap.ui.core.Control");sap.ui.core.Control.extend("sap.m.Bar",{metadata:{library:"sap.m",properties:{"enableFlexBox":{type:"boolean",group:"Misc",defaultValue:false}},aggregations:{"contentLeft":{type:"sap.ui.core.Control",multiple:true,singularName:"contentLeft"},"contentMiddle":{type:"sap.ui.core.Control",multiple:true,singularName:"contentMiddle"},"contentRight":{type:"sap.ui.core.Control",multiple:true,singularName:"contentRight"}}}});
sap.m.Bar.prototype.init=function(){};
sap.m.Bar.prototype.onBeforeRendering=function(){if(this._sResizeListenerId){sap.ui.core.ResizeHandler.deregister(this._sResizeListenerId);this._sResizeListenerId=null}};
sap.m.Bar.prototype.onAfterRendering=function(){this._updatePosition();this._sResizeListenerId=sap.ui.core.ResizeHandler.register(this.getDomRef(),jQuery.proxy(this._updatePosition,this))};
sap.m.Bar.prototype.exit=function(){if(this._sResizeListenerId){sap.ui.core.ResizeHandler.deregister(this._sResizeListenerId);this._sResizeListenerId=null}};
sap.m.Bar.prototype._updatePosition=function(){if(this._sResizeListenerId){sap.ui.core.ResizeHandler.deregister(this._sResizeListenerId);this._sResizeListenerId=null}var $=this.$();if($.length==0||!$.is(":visible")){return}var b=$.outerWidth(true);var a=jQuery.sap.byId(this.getId()+"-BarLeft");a.css({'width':'auto'});var l=a.children();var t=0;for(var i=0;i<l.length;i++){t+=jQuery(l[i]).outerWidth(true)}var L=a.outerWidth(true);if(L<t){L=t;a.css({'width':L})}var c=jQuery.sap.byId(this.getId()+"-BarMiddle");var m=c.outerWidth(true);var d=jQuery.sap.byId(this.getId()+"-BarPH");d.css({'position':'static','width':'auto','visibility':'hidden'});var M=d.outerWidth(true);var o=d.position();var e=jQuery.sap.byId(this.getId()+"-BarRight");e.css({'width':'auto'});var r=e.outerWidth(true);var R=e.position();if(this.getEnableFlexBox()){d.css({'position':'absolute','left':L});d.width(b-L-r-parseInt(d.css('margin-left'),10)-parseInt(d.css('margin-right'),10))}else{if(R.left+r>=b){if(b<(L+r)){if(r>b){e.width(b)}if(b<r){a.width(0)}else{a.width(b-r)}}if(o.left<L){d.css({'position':'absolute','left':L});o=d.position()}else{}if((o.left+M)>R.left){if(R.left<o.left){d.width(0)}else{d.width(R.left-o.left)}}if(d.outerWidth()>m){d.width(m)}}}d.css({'visibility':'inherit'});this._sResizeListenerId=sap.ui.core.ResizeHandler.register(this.getDomRef(),jQuery.proxy(this._updatePosition,this))};
