/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.m.BusyIndicator");jQuery.sap.require("sap.m.library");jQuery.sap.require("sap.ui.core.Control");sap.ui.core.Control.extend("sap.m.BusyIndicator",{metadata:{library:"sap.m",properties:{"text":{type:"string",group:"Data",defaultValue:null},"textDirection":{type:"sap.ui.core.TextDirection",group:"Appearance",defaultValue:sap.ui.core.TextDirection.Inherit},"visible":{type:"boolean",group:"Appearance",defaultValue:true},"customIcon":{type:"sap.ui.core.URI",group:"Misc",defaultValue:null},"customIconRotationSpeed":{type:"int",group:"Appearance",defaultValue:1000},"customIconDensityAware":{type:"boolean",group:"",defaultValue:true},"customIconWidth":{type:"sap.ui.core.CSSSize",group:"Appearance",defaultValue:null},"customIconHeight":{type:"sap.ui.core.CSSSize",group:"Appearance",defaultValue:null},"size":{type:"sap.ui.core.CSSSize",group:"Misc",defaultValue:null},"design":{type:"string",group:"Appearance",defaultValue:'auto'}}}});
sap.m.BusyIndicator.prototype.onAfterRendering=function(){if(this.getCustomIconRotationSpeed()){this.$().children('img').css("-webkit-animation-duration",this.getCustomIconRotationSpeed()+"ms")}var $=this.$();var p=this.getParent()?this.getParent()._context:'';if(!jQuery.os.ios){if(!this.getCustomIcon()&&this.$().parent('.sapMBusyDialog').length===0&&p!=='header'){var f=true;while($.css('background-color')==="rgba(0, 0, 0, 0)"){$=$.parent();if($.parent().length==0){f=false;break}}var b="rgba(0, 0, 0, 0)";if(f){b=$.css('background-color')}this.$().children().children('.sapMSpinBar3').children('.sapMSpinBar4').css('background-color',b)}}};
sap.m.BusyIndicator.prototype.setCustomIconRotationSpeed=function(s){if(s){if(s!==this.getCustomIconRotationSpeed()){this.setProperty("customIconRotationSpeed",s,true)}}return this};
sap.m.BusyIndicator.prototype.setDesign=function(d){this.setProperty("design",d,true);this.$().toggleClass("sapMBusyIndicatorLight",(this.getDesign()==="light"));this.$().toggleClass("sapMBusyIndicatorDark",(this.getDesign()==="dark"))};
