/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.m.ButtonRenderer");sap.m.ButtonRenderer={};
sap.m.ButtonRenderer.render=function(r,b){if(!b.getVisible()){return}var t=b.getType();var w=b.getWidth();var e=b.getEnabled();var E=false;var a="check_icon.png";var R="delete_icon.png";var u="back_icon.png";r.write("<button type=\"button\"");r.writeControlData(b);if(t!=sap.m.ButtonType.Unstyled){r.addClass("sapMBtn")}if(!e){if(t==sap.m.ButtonType.Back||t==sap.m.ButtonType.Up){r.addClass("sapMBtn"+jQuery.sap.escapeHTML(t)+"Disabled")}else{if(t!=sap.m.ButtonType.Unstyled){r.addClass("sapMBtnDisabled")}}}else{if(t!=""&&t!=sap.m.ButtonType.Unstyled){r.addClass("sapMBtn"+jQuery.sap.escapeHTML(t))}}if(b.getIcon()&&!b.getText()&&t!=sap.m.ButtonType.Back){if(!e){r.addClass("sapMBtnIconDisabled")}else{r.addClass("sapMBtnIcon")}}if(w!=""||w.toLowerCase()=="auto"){E=false;r.writeAttribute("style","width:"+w+";")}r.writeClasses();r.write(">");if(this.renderButtonContentBefore){this.renderButtonContentBefore(r,b)}if(t==sap.m.ButtonType.Accept){E=true}if(t==sap.m.ButtonType.Reject){E=true}if(t==sap.m.ButtonType.Up){E=true}if(b.getIcon()){E=true}if(E){r.write("<div");if(t!=sap.m.ButtonType.Unstyled){r.addClass("sapMBtnContent");r.writeClasses()}r.write(">")}var i=jQuery.sap.getModulePath("sap.m",'/')+"themes/"+sap.ui.getCore().getConfiguration().getTheme()+"/img/";this.writeInternalImgHtml(r,b,t,sap.m.ButtonType.Accept,i,a);this.writeInternalImgHtml(r,b,t,sap.m.ButtonType.Reject,i,R);this.writeInternalImgHtml(r,b,t,sap.m.ButtonType.Up,i,u);if(b.getIcon()&&b.getIconFirst()){this.writeImgHtml(r,b)}this.writeTextHtml(r,b,E,t);if(b.getIcon()&&!b.getIconFirst()){this.writeImgHtml(r,b)}if(E){r.write("</div>")}if(this.renderButtonContentAfter){this.renderButtonContentAfter(r,b)}r.write("</button>")};
sap.m.ButtonRenderer.writeTextHtml=function(r,b,e,t){r.write("<span");if(!e&&t!=sap.m.ButtonType.Unstyled){r.addClass("sapMBtnContent");r.writeClasses()}if(b.getIcon()&&b.getText()){r.addClass("sapMBtnContentSpan");r.writeClasses()}r.write(">");if(b.getText()){r.writeEscaped(b.getText())}else{if(t==sap.m.ButtonType.Back){r.write("&nbsp;")}}r.write("</span>")};
sap.m.ButtonRenderer.writeImgHtml=function(r,b){r.renderControl(b._getImage((b.getId()+"-img"),b.getIcon()))};
sap.m.ButtonRenderer.writeInternalImgHtml=function(r,b,t,c,i,I){var h="2.0em";var w="2.0em";if(t===sap.m.ButtonType.Up){h="2.0em";w="1.0em"}if(t===c){if(!jQuery.os.ios){if(b._imageBtn){b._imageBtn.setSrc(i+I);b._imageBtn.setHeight(h);b._imageBtn.setWidth(w);r.renderControl(b._imageBtn)}else{r.renderControl(b._getImageBtn((b.getId()+"-imgBtn"),i+I,h,w))}}}};
