/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.m.GrowingList");jQuery.sap.require("sap.m.library");jQuery.sap.require("sap.m.List");sap.m.List.extend("sap.m.GrowingList",{metadata:{library:"sap.m",properties:{"threshold":{type:"int",group:"Misc",defaultValue:20},"triggerText":{type:"string",group:"Appearance",defaultValue:null}}}});
sap.m.GrowingList.prototype.init=function(){if(sap.m.List.prototype.init){sap.m.List.prototype.init.apply(this,arguments)}this._iCurrentNumberOfItems=0;this._bPullTriggered=false;this._iListItemCount=0;this._sLastListItemId=""};
sap.m.GrowingList.prototype.onAfterRendering=function(){if(sap.m.List.prototype.onAfterRendering){sap.m.List.prototype.onAfterRendering.apply(this,arguments)}var i=this.getId()+"-listUl";if(jQuery.sap.domById(i)!=undefined){this._loadNewItems()}};
sap.m.GrowingList.prototype.exit=function(){if(sap.m.List.prototype.exit){sap.m.List.prototype.exit.apply(this,arguments)}if(this._busyIndicator){this._busyIndicator.destroy()}if(this._trigger){this._trigger.destroy()}};
sap.m.GrowingList.prototype._getTrigger=function(i){var t=this;var T=sap.ui.getCore().getLibraryResourceBundle("sap.m").getText("LOAD_MORE_DATA");if(this.getTriggerText()){T=this.getTriggerText()}var _=this._trigger||new sap.m.CustomListItem({id:i,content:new sap.ui.core.HTML({content:{path:"dummy",formatter:function(){return"<div class='sapMSLIDiv sapMGrowingListTrigger'>"+"<div class='sapMGrowingListBusyIndicator' id='"+i+"-busyIndicator'></div>"+"<div class='sapMSLITitleDiv sapMGrowingListTitel'>"+"<h1 class='sapMSLITitle'>"+T+"</h1>"+"</div>"+"<div class='sapMGrowingListDescription'>"+"<p class='sapMSLIDescription' id='"+i+"-itemInfo'>"+t._getListItemInfo()+"</p>"+"</div>"+"</div>"}},afterRendering:function(e){var b=t._getBusyIndicator();var r=sap.ui.getCore().createRenderManager();r.render(b,this.getDomRef().firstChild);r.destroy()}}),type:sap.m.ListType.Active}).setParent(this,null,true).attachTap(this._tap);return this._trigger=_};
sap.m.GrowingList.prototype._getBusyIndicator=function(){var _=this._busyIndicator||new sap.m.BusyIndicator({size:'2.0em'});return this._busyIndicator=_};
sap.m.GrowingList.prototype._getListItemInfo=function(){return("[ "+this._iCurrentNumberOfItems+" / "+this._getListItemCount()+" ]")};
sap.m.GrowingList.prototype._tap=function(e){var t=this;jQuery.sap.byId(this.getId()+'-busyIndicator').toggleClass('sapMGrowingListBusyIndicatorVisible',true);window.setTimeout(function(){t.oParent._loadNewItems()},0)};
sap.m.List.prototype.addListItem=function(i){i._mode=this.getMode();i._includeItemInSelection=this.getIncludeItemInSelection();i._select=this._select;i._delete=this._delete;i._listId=this.getId();i._showUnread=this.getShowUnread();this.addAggregation("items",i,true);var r=sap.ui.getCore().createRenderManager();var l=this.getId()+"-listUl";r.render(i,jQuery.sap.domById(l));r.destroy();return this};
sap.m.GrowingList.prototype._getListItemCount=function(){var b=this.getBinding("items");if(b){return b.getLength()}else{return this.getItems().length}};
sap.m.GrowingList.prototype._loadNewItems=function(){var t=this;var b=this.getBindingInfo("items"),f=b.factory,B=b.binding,c=this._iCurrentNumberOfItems,L=this._getListItemCount(),n=Math.min(L,this.getThreshold()),T=this.getThreshold(),C=B?B.getContexts(c,n,T):[];console.log("---------> _loadNewItems "+C.length);if(c!==B.iLength){var s=this.getId()+"-listUl";if((C.length>0)&&(jQuery.sap.domById(s)!=undefined)){for(var i=0,l=C.length;i<l;i++){var I=this.getId()+"-id"+(c+i),o=f(I,C[i]);o.setBindingContext(C[i]);this.addListItem(o)}this._iCurrentNumberOfItems=(c+T);if(this._iCurrentNumberOfItems>L){this._iCurrentNumberOfItems=L}if((this.oParent._oScroller._scroller)&&(this._sLastListItemId)){this.oParent._oScroller._scroller.refresh();this.oParent._oScroller._scroller.scrollToElement(jQuery.sap.domById(this._sLastListItemId),1000)}this._sLastListItemId=o.sId}}window.setTimeout(function(){jQuery.sap.byId(t.getId()+'-trigger-busyIndicator').toggleClass('sapMGrowingListBusyIndicatorVisible',false);jQuery.sap.domById(t.getId()+'-trigger-itemInfo').innerHTML=t._getListItemInfo()},0);if(C.length==0){this._bPullTriggered=true}this._iListItemCount=L};
sap.m.GrowingList.prototype.updateItems=function(){var t=this;var b=this.getBindingInfo("items"),f=b.factory,B=b.binding,c=this._iCurrentNumberOfItems,L=this._getListItemCount(),n=Math.min(L,this.getThreshold()),T=this.getThreshold(),C=B?B.getContexts(c,n,T):[];console.log("---------> updateItems "+C.length);console.log("---------> calculation "+c+" / "+n+" / "+L);if(this._iListItemCount>0&&this._iListItemCount!=L){C=B?B.getContexts(0,n,T):[];jQuery.sap.byId(this.getId()+'-busyIndicator').toggleClass('sapMGrowingListBusyIndicatorVisible',true);window.setTimeout(function(){jQuery.sap.byId(t.getId()+'-trigger-busyIndicator').toggleClass('sapMGrowingListBusyIndicatorVisible',false);jQuery.sap.domById(t.getId()+'-trigger-itemInfo').innerHTML=t._getListItemInfo()},0)}if(this._bPullTriggered){if(c!==B.iLength){var s=this.getId()+"-listUl";if((C.length>0)&&(jQuery.sap.domById(s)!=undefined)){for(var i=0,l=C.length;i<l;i++){var I=this.getId()+"-id"+(c+i),o=f(I,C[i]);o.setBindingContext(C[i]);this.addListItem(o)}this._iCurrentNumberOfItems=(c+T);if(this._iCurrentNumberOfItems>L){this._iCurrentNumberOfItems=L}if((this.oParent._oScroller._scroller)&&(this._sLastListItemId)){this.oParent._oScroller._scroller.refresh();this.oParent._oScroller._scroller.scrollToElement(jQuery.sap.domById(this._sLastListItemId),1000)}this._sLastListItemId=o.sId}}window.setTimeout(function(){jQuery.sap.byId(t.getId()+'-trigger-busyIndicator').toggleClass('sapMGrowingListBusyIndicatorVisible',false);jQuery.sap.domById(t.getId()+'-trigger-itemInfo').innerHTML=t._getListItemInfo()},0)}this._bPullTriggered=false;this._iListItemCount=L}
