/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.m.Popover");jQuery.sap.require("sap.m.library");jQuery.sap.require("sap.ui.core.Control");sap.ui.core.Control.extend("sap.m.Popover",{metadata:{publicMethods:["close","openBy","isOpen"],library:"sap.m",properties:{"placement":{type:"sap.m.PlacementType",group:"Behavior",defaultValue:sap.m.PlacementType.Right},"showHeader":{type:"boolean",group:"Appearance",defaultValue:true},"title":{type:"string",group:"Appearance",defaultValue:null},"modal":{type:"boolean",group:"Behavior",defaultValue:false},"offsetX":{type:"int",group:"Appearance",defaultValue:0},"offsetY":{type:"int",group:"Appearance",defaultValue:0},"contentWidth":{type:"sap.ui.core.CSSSize",group:"Dimension",defaultValue:null},"contentHeight":{type:"sap.ui.core.CSSSize",group:"Dimension",defaultValue:null},"enableScrolling":{type:"boolean",group:"Misc",defaultValue:true}},defaultAggregation:"content",aggregations:{"content":{type:"sap.ui.core.Control",multiple:true,singularName:"content"},"customHeader":{type:"sap.ui.core.Control",multiple:false},"footer":{type:"sap.ui.core.Control",multiple:false}},associations:{"leftButton":{type:"sap.m.Button",multiple:false},"rightButton":{type:"sap.m.Button",multiple:false}},events:{"afterOpen":{},"afterClose":{},"beforeOpen":{},"beforeClose":{}}}});sap.m.Popover.M_EVENTS={'afterOpen':'afterOpen','afterClose':'afterClose','beforeOpen':'beforeOpen','beforeClose':'beforeClose'};jQuery.sap.require("sap.ui.core.Popup");jQuery.sap.require("sap.m.Bar");jQuery.sap.require("sap.ui.core.delegate.ScrollEnablement");jQuery.sap.require("sap.m.InstanceManager");
sap.m.Popover.prototype.init=function(){this._firstOpen=true;this._arrowOffsetThreshold=15;this._marginTopInit=false;this._marginTop=jQuery.os.ios?44:48;this._marginLeft=10;this._marginRight=10;this._marginBottom=10;this._$window=jQuery(window);this.oPopup=new sap.ui.core.Popup();this.oPopup.setShadow(true);this.oPopup.setAutoClose(true);this.oPopup.setAnimations(this._openAnimation,this._closeAnimation);this._placements=[sap.m.PlacementType.Top,sap.m.PlacementType.Right,sap.m.PlacementType.Bottom,sap.m.PlacementType.Left];this._myPositions=["center bottom","begin center","center top","end center"];this._atPositions=["center top","end center","center bottom","begin center"];this._offsets=["0 -18","18 0","0 18","-18 0"];this._arrowOffset=18;this._scrollContentList=[sap.m.NavContainer,sap.m.Page,sap.m.ScrollContainer];this._fSetArrowPosition=jQuery.proxy(this._setArrowPosition,this);this._fOrientationChange=jQuery.proxy(this._onOrientationChange,this);var t=this;this.oPopup._applyPosition=function(p){if(t._sResizeListenerId){sap.ui.core.ResizeHandler.deregister(t._sResizeListenerId);t._sResizeListenerId=null}t._clearCSSStyles();p.of=(t._oOpenBy instanceof sap.ui.core.Control)?t._oOpenBy.getDomRef():t._oOpenBy;sap.ui.core.Popup.prototype._applyPosition.call(this,p);t._fSetArrowPosition();t._sResizeListenerId=sap.ui.core.ResizeHandler.register(t.getDomRef(),t._fOrientationChange)}};
sap.m.Popover.prototype.onBeforeRendering=function(){if(this._sResizeListenerId){sap.ui.core.ResizeHandler.deregister(this._sResizeListenerId);this._sResizeListenerId=null}if(this._hasScrollableContent()){this._forceDisableScrolling=true;jQuery.sap.log.info("EnableScrolling in sap.m.Popover with ID "+this.getId()+" has been disabled because there's scrollable content inside")}else{this._forceDisableScrolling=false}if(this.getEnableScrolling()&&!this._forceDisableScrolling){if(!this._oScroller){this._oScroller=new sap.ui.core.delegate.ScrollEnablement(this,this.getId()+"-scroll",{horizontal:true,vertical:true,zynga:false,preventDefault:false,nonTouchScrolling:true})}}};
sap.m.Popover.prototype.onAfterRendering=function(){var $,a,b;if(!this._marginTopInit){this._marginTop=2;if(this._oOpenBy){$=(this._oOpenBy instanceof sap.ui.core.Control)?this._oOpenBy.$():jQuery(this._oOpenBy);if(!($.closest("header.sapMBar").length>0)){a=$.closest(".sapMPage");if(a.length>0){b=a.children("header.sapMBar");if(b.length>0){this._marginTop+=b.outerHeight()}}}this._marginTopInit=true}}};
sap.m.Popover.prototype.exit=function(){this.oPopup.close();this.oPopup.destroy();this.oPopup=null;if(this._oScroller){this._oScroller.destroy();this._oScroller=null}if(this._internalHeader){this._internalHeader.destroy();this._internalHeader=null}if(this._headerTitle){this._headerTitle.destroy()}if(this._sResizeListenerId){sap.ui.core.ResizeHandler.deregister(this._sResizeListenerId);this._sResizeListenerId=null}this._$window.unbind("resize",this._fOrientationChange)};
sap.m.Popover.prototype.openBy=function(c){var p=this.oPopup,e=this.oPopup.getOpenState(),P,i;if(e===sap.ui.core.OpenState.OPEN||e===sap.ui.core.OpenState.OPENING||e===sap.ui.core.OpenState.CLOSING){if(this._oOpenBy===c){return}else{var a=function(){p.detachEvent("closed",a,this);this.openBy(c)};p.attachEvent("closed",a,this);this.close();return}}if(!c){return}this._$window.bind("resize",this._fOrientationChange);if(!this._oOpenBy||c!==this._oOpenBy){this._oOpenBy=c}this.fireBeforeOpen({openBy:this._oOpenBy});p.attachEvent("opened",this._handleOpened,this);i=jQuery.inArray(this.getPlacement(),this._placements);if(i>-1){P=(this._oOpenBy instanceof sap.ui.core.Control)?this._oOpenBy.getDomRef():this._oOpenBy;p.setContent(this);p.setPosition(this._myPositions[i],this._atPositions[i],P,this._calcOffset(this._offsets[i]),"fit");var t=this;var C=function(){if(p.getOpenState()===sap.ui.core.OpenState.CLOSING){setTimeout(C,150)}else{p.open();sap.m.InstanceManager.addPopoverInstance(t)}};C()}else{jQuery.sap.log.error(this.getPlacement()+"is not a valid value! It can only be top, right, bottom or left")}};
sap.m.Popover.prototype.close=function(){var e=this.oPopup.getOpenState();if(!(e===sap.ui.core.OpenState.CLOSED||e===sap.ui.core.OpenState.CLOSING)){this.fireBeforeClose({openBy:this._oOpenBy});this.oPopup.close()}};
sap.m.Popover.prototype.isOpen=function(){return this.oPopup&&this.oPopup.isOpen()};
sap.m.Popover.prototype._clearCSSStyles=function(){var $=this.$(),a=jQuery.sap.byId(this.getId()+"-cont"),b=a.children(".sapMPopoverScroll"),c=this.getContentWidth(),C=this.getContentHeight();$.css({"left":"","right":"","top":"","bottom":"","width":"","height":""});b.css({"width":""});a.css({"width":c?c:"","height":C?C:"","max-width":""})};
sap.m.Popover.prototype._onOrientationChange=function(){var e=this.oPopup.getOpenState();if(!(e===sap.ui.core.OpenState.OPEN||e===sap.ui.core.OpenState.OPENING)){return}this.oPopup._applyPosition(this.oPopup._oLastPosition)};
sap.m.Popover.prototype._handleOpened=function(){this.oPopup.detachEvent("opened",this._handleOpened,this);this.oPopup.attachEvent("closed",this._handleClosed,this);this._sResizeListenerId=sap.ui.core.ResizeHandler.register(this.getDomRef(),this._fOrientationChange);this.fireAfterOpen({openBy:this._oOpenBy});this._firstOpen=false};
sap.m.Popover.prototype._handleClosed=function(){this.oPopup.detachEvent("closed",this._handleClosed,this);if(this._sResizeListenerId){sap.ui.core.ResizeHandler.deregister(this._sResizeListenerId);this._sResizeListenerId=null}sap.m.InstanceManager.removePopoverInstance(this);this.fireAfterClose({openBy:this._oOpenBy})};
sap.m.Popover.prototype._hasNavContent=function(){var c=this.getAggregation("content");if(jQuery.isArray(c)&&c.length===1&&c[0]instanceof sap.m.NavContainer){return true}else{return false}};
sap.m.Popover.prototype._hasPageContent=function(){var c=this.getAggregation("content");if(jQuery.isArray(c)&&c.length===1&&c[0]instanceof sap.m.Page){return true}else{return false}};
sap.m.Popover.prototype._hasScrollableContent=function(){var c=this.getAggregation("content"),i;if(c.length===1){for(i=0;i<this._scrollContentList.length;i++){if(c[0]instanceof this._scrollContentList[i]){return true}}return false}else{return false}};
sap.m.Popover.prototype._calcOffset=function(o){var O=this.getOffsetX(),i=this.getOffsetY();var p=o.split(" ");return(parseInt(p[0],10)+O)+" "+(parseInt(p[1],10)+i)};
sap.m.Popover.prototype._setArrowPosition=function(){var e=this.oPopup.getOpenState();if(!(e===sap.ui.core.OpenState.OPEN||e===sap.ui.core.OpenState.OPENING)){return}var $=(this._oOpenBy instanceof sap.ui.core.Control)?this._oOpenBy.$():jQuery(this._oOpenBy),a=this.$(),p=this.getPlacement(),b=jQuery.sap.byId(this.getId()+"-arrow"),c=a.offset(),o=this.getOffsetX(),O=this.getOffsetY(),w=a.outerWidth(),h=a.outerHeight(),d=jQuery.sap.byId(this.getId()+"-cont"),f=d.children(".sapMPopoverScroll"),g,i,m,M,P,H=0,F=0;var W=this._$window.scrollLeft(),j=this._$window.scrollTop(),k=this._$window.width(),l=this._$window.height();var n=this._marginLeft,q=this._marginRight,r=this._marginTop,s=this._marginBottom;var L,R,t,B;switch(p){case sap.m.PlacementType.Left:q=k-$.offset().left+this._arrowOffset-this.getOffsetX();R=q;break;case sap.m.PlacementType.Right:n=$.offset().left+$.outerWidth()+this._arrowOffset+this.getOffsetX();L=n;break;case sap.m.PlacementType.Top:s=l-$.offset().top+this._arrowOffset-this.getOffsetY();B=s;break;case sap.m.PlacementType.Bottom:r=$.offset().top+$.outerHeight()+this._arrowOffset+this.getOffsetY();t=r;break}var E=(k-W-q-n)<w,u=(l-j-r-s)<h,v=(c.left-W)<=n,x=(k-c.left-w)<=q,y=(c.top-j)<=r,z=(l-c.top-h)<=s;if(E){L=n;R=q}else{if(v){L=n}else if(x){R=q}}if(u){t=r;B=s}else{if(y){t=r}else if(z){B=s}}a.css({top:t,bottom:B,left:L,right:R});if(p===sap.m.PlacementType.Left||p===sap.m.PlacementType.Right){P=$.offset().top-a.offset().top-parseInt(a.css("border-top-width"))+O+0.5*($.outerHeight(false)-b.outerHeight(false));P=Math.max(P,this._arrowOffsetThreshold);P=Math.min(P,h-this._arrowOffsetThreshold-b.outerHeight());b.css("top",P)}else if(p===sap.m.PlacementType.Top||p===sap.m.PlacementType.Bottom){P=$.offset().left-a.offset().left-parseInt(a.css("border-left-width"))+o+0.5*($.outerWidth(false)-b.outerWidth(false));P=Math.max(P,this._arrowOffsetThreshold);P=Math.min(P,w-this._arrowOffsetThreshold-b.outerWidth());b.css("left",P)}switch(p){case sap.m.PlacementType.Left:b.addClass("sapMPopoverArrRight");break;case sap.m.PlacementType.Right:b.addClass("sapMPopoverArrLeft");break;case sap.m.PlacementType.Top:b.addClass("sapMPopoverArrDown");break;case sap.m.PlacementType.Bottom:b.addClass("sapMPopoverArrUp");break}if(p===sap.m.PlacementType.Left){M=a.offset().left+w-this._marginLeft}else{M=k-a.offset().left-this._marginRight}g=a.children(".sapMPopoverHeader");if(g.length>0){H=g.outerHeight(true)}i=a.children(".sapMPopoverFooter");if(i.length>0){F=i.outerHeight(true)}m=a.height()-H-F-parseInt(d.css("margin-top"),10)-parseInt(d.css("margin-bottom"),10);m=Math.max(m,0);d.css({"max-width":M+"px","height":m+"px"});if(f.outerWidth(true)<=d.width()){f.css("width","100%")}};
sap.m.Popover.prototype._isPopupElement=function(d){var p=(this._oOpenBy instanceof sap.ui.core.Control)?this._oOpenBy.getDomRef():this._oOpenBy;return!!(jQuery(d).closest(sap.ui.getCore().getStaticAreaRef()).length)||!!(jQuery(d).closest(p).length)};
sap.m.Popover.prototype._getAnyHeader=function(){if(this.getCustomHeader()){return this.getCustomHeader().addStyleClass("sapMHeader-CTX",true)}else{if(this.getShowHeader()){this._createInternalHeader();return this._internalHeader.addStyleClass("sapMHeader-CTX",true)}}};
sap.m.Popover.prototype._createInternalHeader=function(){if(!this._internalHeader){this._internalHeader=new sap.m.Bar(this.getId()+"-intHeader");this._internalHeader.setParent(this,"internalHeader",false);return true}else{return false}};
sap.m.Popover.prototype._openAnimation=function(r,R,o){if(jQuery.os.android&&jQuery.os.fVersion<2.4){o()}else{setTimeout(function(){r.addClass("sapMPopoverTransparent sapMPopoverAnimation");r.css("display","block");setTimeout(function(){r.one("webkitTransitionEnd",function(){r.removeClass("sapMPopoverAnimation");o()});r.removeClass("sapMPopoverTransparent")},0)},0)}};
sap.m.Popover.prototype._closeAnimation=function(r,R,c){if(jQuery.os.android&&jQuery.os.fVersion<2.4){c()}else{r.addClass("sapMPopoverAnimation");setTimeout(function(){r.one("webkitTransitionEnd",function(){r.removeClass("sapMPopoverAnimation sapMPopoverTransparent");c()}).addClass("sapMPopoverTransparent")},0)}};
sap.m.Popover.prototype.setPlacement=function(p){this.setProperty("placement",p,true);return this};
sap.m.Popover.prototype.setTitle=function(t){if(t){this.setProperty("title",t,true);if(this._headerTitle){this._headerTitle.setText(t)}else{this._headerTitle=new sap.m.Label(this.getId()+"-title",{text:this.getTitle()});this._createInternalHeader();if(jQuery.os.ios){this._internalHeader.addContentMiddle(this._headerTitle)}else{this._internalHeader.addContentLeft(this._headerTitle)}}}return this};
sap.m.Popover.prototype.setLeftButton=function(b){if(typeof(b)==="string"){b=sap.ui.getCore().byId(b)}var o=sap.ui.getCore().byId(this.getLeftButton());if(o===b){return this}this._createInternalHeader();if(b){if(jQuery.os.ios){if(o){this._internalHeader.removeAggregation("contentLeft",o,true)}this._internalHeader.addAggregation("contentLeft",b,true)}else{if(o){this._internalHeader.removeAggregation("contentRight",o,true)}this._internalHeader.insertAggregation("contentRight",b,0,true)}this._internalHeader.invalidate()}else{if(jQuery.os.ios){this._internalHeader.removeContentLeft(o)}else{this._internalHeader.removeContentRight(o)}}this.setAssociation("leftButton",b,true);return this};
sap.m.Popover.prototype.setRightButton=function(b){if(typeof(b)==="string"){b=sap.ui.getCore().byId(b)}var o=sap.ui.getCore().byId(this.getRightButton());if(o===b){return this}this._createInternalHeader();if(b){if(o){this._internalHeader.removeAggregation("contentRight",o,true)}this._internalHeader.insertAggregation("contentRight",b,1,true);this._internalHeader.invalidate()}else{this._internalHeader.removeContentRight(o)}this.setAssociation("rightButton",b,true);return this};
sap.m.Popover.prototype.setShowHeader=function(v){if(v===this.getShowHeader()||this.getCustomHeader()){return this}if(v){if(this._internalHeader){this._internalHeader.$().show()}}else{if(this._internalHeader){this._internalHeader.$().hide()}}this.setProperty("showHeader",v,true);return this};
sap.m.Popover.prototype.setModal=function(m){if(m===this.getModal()){return this}this.oPopup.setModal(m,"sapMPopoverBLayer");this.setProperty("modal",m,true);return this};
sap.m.Popover.prototype.setOffsetX=function(v){var e=this.oPopup.getOpenState(),l,p;this.setProperty("offsetX",v,true);if(!(e===sap.ui.core.OpenState.OPEN)){return this}l=this.oPopup._oLastPosition;p=jQuery.inArray(this.getPlacement(),this._placements);if(p>-1){l.offset=this._calcOffset(this._offsets[p]);this.oPopup._applyPosition(l)}return this};
sap.m.Popover.prototype.setOffsetY=function(v){var e=this.oPopup.getOpenState(),l,p;this.setProperty("offsetY",v,true);if(!(e===sap.ui.core.OpenState.OPEN)){return this}l=this.oPopup._oLastPosition;p=jQuery.inArray(this.getPlacement(),this._placements);if(p>-1){l.offset=this._calcOffset(this._offsets[p]);this.oPopup._applyPosition(l)}return this};
sap.m.Popover.prototype.setEnableScrolling=function(v){var o=this.getEnableScrolling();if(o===v){return}this.setProperty("enableScrolling",v,!v);if(!v){if(this._oScroller){this._oScroller.destroy();this._oScroller=null}}};
sap.m.Popover.prototype.getScrollDelegate=function(){return this._oScroller};
sap.m.Popover.prototype.forceInvalidate=sap.ui.core.Control.prototype.invalidate;
sap.m.Popover.prototype.invalidate=function(o){if(!this._firstOpen){this.forceInvalidate()}};
