/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.m.Switch");jQuery.sap.require("sap.m.library");jQuery.sap.require("sap.ui.core.Control");sap.ui.core.Control.extend("sap.m.Switch",{metadata:{library:"sap.m",properties:{"visible":{type:"boolean",group:"Appearance",defaultValue:true},"state":{type:"boolean",group:"Misc",defaultValue:false},"enabled":{type:"boolean",group:"Data",defaultValue:true},"name":{type:"string",group:"Misc",defaultValue:""},"customTextOn":{type:"string",group:"Misc",defaultValue:null},"customTextOff":{type:"string",group:"Misc",defaultValue:null}},events:{"change":{}}}});sap.m.Switch.M_EVENTS={'change':'change'};sap.m.Switch._iTransTime=175;sap.m.Switch._bAndroidStyle=!!(jQuery.os.android||jQuery.os.blackberry);sap.m.Switch._aEvents=(function(){var e=["ontouchstart","ontouchmove","ontouchend","ontouchcancel"];if(sap.m.Switch._bAndroidStyle){e.push("onswiperight","onswipeleft")}return e})();sap.m.Switch._aVEvents=(function(){return jQuery.map(sap.m.Switch._aEvents,function(e){return"_"+e})})();sap.m.Switch._bTransition=!!(jQuery.os.ios);sap.m.Switch._oRb=sap.ui.getCore().getLibraryResourceBundle("sap.m");
sap.m.Switch.prototype.onBeforeRendering=function(){var S=sap.m.Switch;if(this.getCustomTextOn()===""){this._sOn=S._oRb.getText("SWITCH_ON")}else if(this.getCustomTextOn().length<=3){this._sOn=this.getCustomTextOn()}else{this._sOn=this.getCustomTextOn().substring(0,3)+"..."}if(this.getCustomTextOff()===""){this._sOff=S._oRb.getText("SWITCH_OFF")}else if(this.getCustomTextOff().length<=3){this._sOff=this.getCustomTextOff()}else{this._sOff=this.getCustomTextOff().substring(0,3)+"..."}};
sap.m.Switch.prototype.onAfterRendering=function(){var o=this["_onAfterRendering"+jQuery.os.os];this.getEnabled()?this._bindEvents():this._unbindEvents();this._$SwtCont=this.$();this._$Swt=this._$SwtCont.children(".sapMSwt");this._iSwtWidth=this._$Swt.width();this._$Btn=this._$Swt.children(".sapMSwtBtn");this._fBtnOuterWidth=this._$Btn.outerWidth(true);this._fBtnWidth=this._$Btn.width();this._$Checkbox=this._$Swt.children("input[type=checkbox]");if(typeof o==="function"){o.call(this)}this._iBtnMinLeft=-this._iOffsetX;this._iBtnMaxLeft=(this._iSwtWidth-this._fBtnOuterWidth)+this._iOffsetX;this._$SwtCont.addClass("sapMSwtVisible")};
sap.m.Switch.prototype._onAfterRenderingios=function(){var s;this._iOffsetX=1;this._$TextOn=this._$Swt.children('.sapMSwtTextOn');s=this._$TextOn.children("span").width();this._fTextIndentOn=(this._iSwtWidth-s-this._fBtnWidth)/2;this._$TextOff=this._$Swt.children('.sapMSwtTextOff');this._fTextIndentOff=(this._iSwtWidth-this._$TextOff.children("span").width()+this._fBtnWidth)/2;this._fTextOnIndentMin=-(s+this._fTextIndentOn);this._centerTextIos()};
sap.m.Switch.prototype._onAfterRenderingandroid=function(){this._iOffsetX=7};
sap.m.Switch.prototype._onAfterRenderingblackberry=sap.m.Switch.prototype._onAfterRenderingandroid;
sap.m.Switch.prototype._onswiperight=function(e){this.setState(true,true)};
sap.m.Switch.prototype._onswipeleft=function(e){this.setState(false,true)};
sap.m.Switch.prototype._ontouchstart=function(e){var t=e.targetTouches[0];e.originalEvent._sapui_handledByControl=true;if(sap.m.touch.countContained(e.touches,this.getId())>1){return}this._iActiveTouch=t.identifier;this._$Swt.addClass("sapMSwtPressed");this._bTempState=this.getState();this._iStarPageX=t.pageX;this._iCurrentPageX=this._iStarPageX;this._iDiffX=this._iStarPageX-this._$Btn.position().left;this._bTargetBtn=jQuery(e.target).is(this._$Btn);this._bDrag=false;if(sap.m.Switch._bTransition){this._$Swt.removeClass("sapMSwtTrans")}};
sap.m.Switch.prototype._ontouchmove=function(e){var t,p,d,l,b,S=sap.m.Switch,T=sap.m.touch;t=T.find(e.changedTouches,this._iActiveTouch);if(!t||(S._bAndroidStyle&&!this._bTargetBtn)){return}p=t.pageX;d=p-this._iCurrentPageX;l=this._bTargetBtn&&S._bAndroidStyle?p-this._iDiffX:d+this._$Btn.position().left;b=l+(this._fBtnOuterWidth/2);this._bDrag=true;this._iCurrentPageX=p;this._updateUI(d,l,b)};
sap.m.Switch.prototype._ontouchend=function(e){var p=["_bTempState","_iStarPageX","_iCurrentPageX","_iDiffX","_bTargetBtn","_bDrag","_iActiveTouch"],l=p.length,t=sap.m.touch,a=jQuery.sap.assert,i;a(typeof this._iActiveTouch!=="undefined",'sap.m.Switch.prototype._ontouchend(): expect to already be touching');if(!t.find(e.changedTouches,this._iActiveTouch)){return}a(!t.find(e.touches,this._iActiveTouch),'sap.m.Switch.prototype._ontouchend(): touch ended also still active');this._$Swt.removeClass("sapMSwtPressed");this._bDrag?this.setState(this._bTempState,true):this.setState(!this._bTempState,true);for(i=0;i<l;i++){if(this.hasOwnProperty(p[i])){delete this[p[i]]}}};
sap.m.Switch.prototype._ontouchcancel=sap.m.Switch.prototype._ontouchend;
sap.m.Switch.prototype._updateUI=function(d,l,b){var u=this["_updateUI"+jQuery.os.os];l=l>this._iBtnMaxLeft?this._iBtnMaxLeft:l<this._iBtnMinLeft?this._iBtnMinLeft:l;if(this._iCurrentLeft===l){return}this._iCurrentLeft=l;this._$Btn.css("left",l);this._setTempState(b>=this._iSwtWidth/2);if(typeof u==="function"){u.call(this,d,l)}};
sap.m.Switch.prototype._setTempState=function(b){var s=this["_setTempState"+jQuery.os.os];if(this._bTempState===b){return}this._bTempState=b;if(typeof s==="function"){s.call(this,b)}};
sap.m.Switch.prototype._setTempStateandroid=function(b){this._$Btn.attr("data-sap-ui-swt",b?this._sOn:this._sOff)};
sap.m.Switch.prototype._setTempStateblackberry=sap.m.Switch.prototype._setTempStateandroid;
sap.m.Switch.prototype._updateUIios=function(d,l){var t=parseFloat(this._$TextOn.css("text-indent"))+d;t=t>this._fTextIndentOn?this._fTextIndentOn:t<this._fTextOnIndentMin?this._fTextOnIndentMin:t;this._$TextOn.css({width:l+this._fBtnWidth+this._iOffsetX,textIndent:t});this._$TextOff.width(this._iSwtWidth-(l+this._iOffsetX))};
sap.m.Switch.prototype._bindEvents=function(){var i,S=sap.m.Switch;for(i=0;i<S._aVEvents.length;i++){this[S._aEvents[i]]=this[S._aVEvents[i]]}return this};
sap.m.Switch.prototype._unbindEvents=function(){var i,S=sap.m.Switch;for(i=0;i<S._aVEvents.length;i++){this[S._aEvents[i]]=null}return this};
sap.m.Switch.prototype._centerTextIos=function(){this._$TextOn.css("text-indent",this.getState()?this._fTextIndentOn:this._fTextOnIndentMin);this._$TextOff.css("text-indent",this._fTextIndentOff)};
sap.m.Switch.prototype._setStateandroid=function(s){this._$Btn.attr("data-sap-ui-swt",s)};
sap.m.Switch.prototype._setStateblackberry=this._setStateandroid;
sap.m.Switch.prototype.setState=function(s,t){var s,S,n,b=sap.m.Switch,f=this["_setState"+jQuery.os.os],a,i;if(!this.getEnabled()&&t){return this}n=!(this.getState()===s);if(n){this.setProperty("state",s,true)}if(!(this._$Swt instanceof jQuery)){return this}s=this.getState();S=s?this._sOn:this._sOff;if(n){if(typeof f==="function"){f.call(this,S)}this._$Checkbox.attr({checked:s,value:S});s?this._$Swt.removeClass("sapMSwtOff").addClass("sapMSwtOn"):this._$Swt.removeClass("sapMSwtOn").addClass("sapMSwtOff");if(t){if(b._bTransition){jQuery.sap.delayedCall(b._iTransTime,this,function _fireChangeDelay(s){this.fireChange({state:s})},[s])}else{this.fireChange({state:s})}}}if(b._bTransition){this._$Swt.addClass("sapMSwtTrans")}a=[this._$Btn];if(jQuery.os.ios){a.push(this._$TextOn,this._$TextOff)}for(i=0;i<a.length;i++){a[i].removeAttr("style")}if(jQuery.os.ios){this._centerTextIos()}return this};
