/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.uiext.inbox.SubstitutionRulesManagerUtils");
sap.uiext.inbox.SubstitutionRulesManagerUtils=function(){throw new Error()};
sap.uiext.inbox.SubstitutionRulesManagerUtils._getText=function(v,i,a,e,m,b,c){var _=sap.ui.getCore().getLibraryResourceBundle("sap.uiext.inbox");if(this._isOutDated(c)){return""}else{if(i){if(e){if(a){return v+" "+_.getText("SUBSTIUTION_RULE_CURRENTLY_RECEIVING_TASKS")}else{return v+" "+_.getText("SUBSTIUTION_RULE_WILL_RECEIVE_TASKS_FROM")+" "+this._getFormattedDate(b)}}else{if(m==='RECEIVE_TASKS'){return _.getText("SUBSTIUTION_RULE_IS_CURRENTLY_DISABLED_BY_YOU")}else{return v+" "+_.getText("SUBSTIUTION_RULE_HAS_NOT_ACTIVATED_YOUR")}}}else{if(e){if(a){return _.getText("SUBSTIUTION_RULE_CURRENTLY_RECEIVING_TASKS_FROM")+" "+v}else{return _.getText("SUBSTIUTION_RULE_YOU_WILL_RECEIVE_TASKS_FROM")+" "+v}}else{if(m==='RECEIVE_TASKS'){return _.getText("SUBSTIUTION_RULE_IS_CURRENTLY_DISABLED_BY")+" "+v}else{return _.getText("SUBSTIUTION_RULE_TURN_ON_TO_RECEIVE_TASKS_FROM")+" "+v}}}}};
sap.uiext.inbox.SubstitutionRulesManagerUtils._isOutDated=function(e){if(e!==null&&e!==''){if(this._getTimeDiff(e)<0){return true}}return false};
sap.uiext.inbox.SubstitutionRulesManagerUtils._isFutureDate=function(e){if(e!==null&&e!==''){if(this._getTimeDiff(e)>0){return true}}return false};
sap.uiext.inbox.SubstitutionRulesManagerUtils._getStatus=function(i,a,e,m,b,c){var _=sap.ui.getCore().getLibraryResourceBundle("sap.uiext.inbox");if(this._isOutDated(c)){return _.getText("SUBSTITUTION_OUT_OF_DATE_RANGE")}else{if(i){if(e){if(a){return _.getText("SUBSTITUTION_RULE_ACTIVE_FOR_LABEL")+" "+this._getNoOfDays(a,b,c)}else{return _.getText("SUBSTITUTION_RULE_ACTIVE_IN_LABEL")+" "+this._getNoOfDays(a,b,c)}}else{return _.getText("SUBSTITUTION_DISABLED_STATUS")}}else{if(e){if(a){return _.getText("SUBSTITUTION_RULE_ACTIVE_FOR_LABEL")+" "+this._getNoOfDays(a,b,c)}else{return _.getText("SUBSTITUTION_RULE_ACTIVE_IN_LABEL")+" "+this._getNoOfDays(a,b,c)}}else{return _.getText("SUBSTITUTION_DISABLED_STATUS")}}}};
sap.uiext.inbox.SubstitutionRulesManagerUtils._getNoOfDays=function(i,s,e){var _=sap.ui.getCore().getLibraryResourceBundle("sap.uiext.inbox");var t='';if(i){if(e!==null&&e!==''){var a=this._getTimeDiff(e)/(1000*60*60*24);if(a>1){var n=Math.floor(a);if(n===1){return n+" "+_.getText("SUBSTIUTION_RULE_IN_DAY")}else{return n+" "+_.getText("SUBSTIUTION_RULE_IN_MORE_DAYS")}}else if(a>0){return Math.ceil(a)+" "+_.getText("SUBSTIUTION_RULE_IN_DAY")}}return""}else{if(s!==null&&s!==''){var a=this._getTimeDiff(s)/(1000*60*60*24);if(a>1){var n=Math.floor(a);if(n===1){return n+" "+_.getText("SUBSTIUTION_RULE_IN_DAY")}else{return n+" "+_.getText("SUBSTIUTION_RULE_IN_DAYS")}}else if(a>0){return Math.ceil(a)+" "+_.getText("SUBSTIUTION_RULE_IN_DAY")}}return""}};
sap.uiext.inbox.SubstitutionRulesManagerUtils._getFormattedDate=function(d){var i=sap.ui.core.format.DateFormat.getDateInstance({style:"medium"});if(d!=undefined&&d!=""){return i.format(d)}};
sap.uiext.inbox.SubstitutionRulesManagerUtils._getTodaysDateinYYYYMMDD=function(){var d=new Date();var t=String(d.getFullYear());if(d.getMonth()<9){t=t+"0"}t=t+String(d.getMonth()+1);if(d.getDate()<9){t=t+"0"}t=t+String(d.getDate());return t};
sap.uiext.inbox.SubstitutionRulesManagerUtils._getTimeDiff=function(e){var t=new Date();var o=t.getTimezoneOffset()*60*1000;var d=new Date(e.getFullYear(),e.getMonth(),e.getDate(),24,00,00);var a=d.getTime()-(t.getTime());return a};
sap.uiext.inbox.SubstitutionRulesManagerUtils._getTimeZoneOffset=function(){return undefined};
