/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.makit.Chart");jQuery.sap.require("sap.makit.library");jQuery.sap.require("sap.ui.core.Control");sap.ui.core.Control.extend("sap.makit.Chart",{metadata:{publicMethods:["getSelectedCategory","getSelectedSeries","getNumberOfCategories"],library:"sap.makit",properties:{"width":{type:"sap.ui.core.CSSSize",group:"Dimension",defaultValue:'100%'},"height":{type:"sap.ui.core.CSSSize",group:"Dimension",defaultValue:'100%'},"type":{type:"sap.makit.ChartType",group:"Appearance",defaultValue:sap.makit.ChartType.Column},"categoryAxis":{type:"object",group:"Misc",defaultValue:null},"valueAxis":{type:"object",group:"Misc",defaultValue:null},"valueBubble":{type:"object",group:"Misc",defaultValue:null},"showRangeSelector":{type:"boolean",group:"Appearance",defaultValue:true},"showTableView":{type:"boolean",group:"Misc",defaultValue:false},"legendPosition":{type:"sap.makit.LegendPosition",group:"Misc",defaultValue:sap.makit.LegendPosition.Left}},aggregations:{"rows":{type:"sap.makit.Row",multiple:true,singularName:"row",bindable:"bindable"},"columns":{type:"sap.makit.Column",multiple:true,singularName:"column",bindable:"bindable"},"series":{type:"sap.makit.Series",multiple:false},"values":{type:"sap.makit.Value",multiple:true,singularName:"value"},"category":{type:"sap.makit.Category",multiple:false}},events:{"doubletap":{},"tap":{}}}});sap.makit.Chart.M_EVENTS={'doubletap':'doubletap','tap':'tap'};
/*!
 * @copyright@
 */
jQuery.sap.require("sap.makit.js.SybaseMA");jQuery.sap.declare("sap.makit.js.SybaseMA");
sap.makit.Chart._onThemeChanged=function(e){window.$MA.Chart.getStyles()};
sap.makit.Chart._libraryInit=function(){var i="popup_tt_left.png";var p=sap.ui.resource("sap.makit","themes/base/images/"+i);p=p.substring(0,p.length-i.length);window.$MA.setImagesFolder(p);sap.ui.getCore().attachThemeChanged(sap.makit.Chart._onThemeChanged);window.$MA.Chart.getStyles()}();
sap.makit.Chart.prototype.init=function(){this._makitChart=null;this._datarows=[];this._styleClasses=[];this.setCategoryAxis(new sap.makit.CategoryAxis());this.setValueAxis(new sap.makit.ValueAxis());this.setValueBubble(new sap.makit.ValueBubble());this.attachEvent("_change",this._onPropertyChanged);sap.ui.getCore().attachThemeChanged(this._applyCSS,this)};
sap.makit.Chart.prototype.onBeforeRendering=function(e){if(this.getDomRef()&&!sap.ui.core.RenderManager.isPreservedContent(this.getDomRef())){sap.ui.core.RenderManager.preserveContent(this.getDomRef(),true,false)}};
sap.makit.Chart.prototype.onAfterRendering=function(e){var $=jQuery(jQuery.sap.domById("sap-ui-dummy-"+this.getId()));var a=sap.ui.core.RenderManager.findPreservedContent(this.getId());var b=null;if(a.size()==0){this._createChartObject();b=new jQuery(this.getDomRef());$.replaceWith(b);var p=this.getParent();var c=p.getId();var d=jQuery.sap.domById(c);sap.ui.core.ResizeHandler.register(d,jQuery.proxy(this._onResize,this))}else if(a.size()>0){$.replaceWith(a)}else{$.remove()}this._setDataTable();if(b){this._makitChart.showRangeSelectorView(this.getShowRangeSelector());this._makitChart.showTableView(this.getShowTableView())}};
sap.makit.Chart.prototype.addStyleClass=function(s,S){if(this._styleClasses.indexOf(s)===-1){this._styleClasses.push(s)}if(this._makitChart){sap.ui.core.Control.prototype.addStyleClass.call(this,s,S)}return this};
sap.makit.Chart.prototype.removeStyleClass=function(s,S){var i=this._styleClasses.indexOf(s);if(i>-1){this._styleClasses.splice(i,1)}if(this._makitChart){sap.ui.core.Control.prototype.removeStyleClass.call(this,s,S)}return this};
sap.makit.Chart.prototype.bindAggregation=function(n,b){if(n==="rows"){if(typeof b=="string"){b={path:arguments[1],template:arguments[2],sorter:arguments[3],filters:arguments[4]}}b.template=undefined;b.factory=function(){};return sap.ui.core.Element.prototype.bindAggregation.call(this,n,b)}return sap.ui.core.Element.prototype.bindAggregation.apply(this,arguments)};
sap.makit.Chart.prototype.addRow=function(r){jQuery.sap.log.error("The control manages the rows aggregation. The method \"addRow\" cannot be used programmatically!")};
sap.makit.Chart.prototype.insertRow=function(r,i){jQuery.sap.log.error("The control manages the rows aggregation. The method \"insertRow\" cannot be used programmatically!")};
sap.makit.Chart.prototype.removeRow=function(r){jQuery.sap.log.error("The control manages the rows aggregation. The method \"removeRow\" cannot be used programmatically!")};
sap.makit.Chart.prototype.removeAllRows=function(){jQuery.sap.log.error("The control manages the rows aggregation. The method \"removeAllRows\" cannot be used programmatically!")};
sap.makit.Chart.prototype.destroyRows=function(r){jQuery.sap.log.error("The control manages the rows aggregation. The method \"destroyRows\" cannot be used programmatically!")};
sap.makit.Chart.prototype.updateRows=function(){this._createRows();if(this._makitChart){this._setDataTable()}};
sap.makit.Chart.prototype.setValueBubble=function(v){if(v instanceof sap.makit.ValueBubble){sap.ui.core.Element.prototype.setProperty.call(this,"valueBubble",v,false);v.attachEvent("_change",this._onValueBubbleChanged,this);if(this._makitChart){var a=v.toObject();this._makitChart.setValueBubbleStyle(a);if(this._makitChart.isValueBubbleVisible()!=a.visible){this._makitChart.showValueBubble(a.visible)}}}else{throw new Error("valueBubble property must be of type sap.makit.ValueBubble")}return this};
sap.makit.Chart.prototype.setCategory=function(c){sap.ui.core.Element.prototype.setAggregation.call(this,"category",c,false);c.attachEvent("_change",{type:"category"},this._onDataRegionPropChanged,this);return this};
sap.makit.Chart.prototype.addValue=function(v){sap.ui.core.Element.prototype.addAggregation.call(this,"values",v,false);v.attachEvent("_change",{type:"values"},this._onDataRegionPropChanged,this);return this};
sap.makit.Chart.prototype.setSeries=function(s){sap.ui.core.Element.prototype.setAggregation.call(this,"series",s,false);s.attachEvent("_change",{type:"series"},this._onDataRegionPropChanged,this);return this};
sap.makit.Chart.prototype.setValueAxis=function(v){if(v instanceof sap.makit.ValueAxis){sap.ui.core.Element.prototype.setProperty.call(this,"valueAxis",v,false);v.attachEvent("_change",{axis:"values"},this._onAxisPropChanged,this)}else{throw new Error("valueAxis property must be of type sap.makit.ValueAxis")}return this};
sap.makit.Chart.prototype.setCategoryAxis=function(c){if(c instanceof sap.makit.CategoryAxis){sap.ui.core.Element.prototype.setProperty.call(this,"categoryAxis",c,false);c.attachEvent("_change",{axis:"category"},this._onAxisPropChanged,this)}else{throw new Error("categoryAxis property must be of type sap.makit.CategoryAxis")}return this};
sap.makit.Chart.prototype._setRealHeight=function(h){var e=this.getDomRef();if(h.indexOf("%")>-1){var i=parseInt(h,10);var p=this.getParent();var a=p.getId();var b=jQuery.sap.domById(a);var r=Math.ceil(b.offsetHeight*(i/100));e.style.height=r+"px";return true}else{e.style.height=h}return false};
sap.makit.Chart.prototype._createRows=function(){var t=new sap.makit.Row(this.getId()+"-dummyrows");var c=this.getColumns();for(var i=0,l=c.length;i<l;i++){var C=c[i];if(C){var n=c[i].getName();var o=C.clone("col"+i);o.data("sap-ui-colindex",i);t.addAggregation("cells",o)}}this.destroyAggregation("rows");var a=undefined;var b=this.getBinding("rows");if(b){a=b.getContexts()}var d=b.getLength();this._datarows=[];for(var i=0;i<d;i++){if(a&&a[i]){var o=t.clone("row"+i);o.setBindingContext(a[i]);this.addAggregation("rows",o);this._datarows.push(o._datarow)}}t.destroy()};
sap.makit.Chart.prototype._createChartObject=function(){var e=this.getDomRef();e.style.width=this.getWidth();this._setRealHeight(this.getHeight());this._makitChart=new window.$MA.Chart(this.getId(),true);var t=this;var s=this._getChartSyntax();console.log(s);this._makitChart.create(s);this._makitChart.showToolBar(false);this._setMakitChartProperties();this._makitChart.bind("tap",function(){t.fireTap({})});this._makitChart.bind("doubletap",function(){t.fireEvent("doubletap",t)});var l=this._styleClasses.length;for(var i=0;i<l;i++){this.addStyleClass(this._styleClasses[i])}this._applyCSS()};
sap.makit.Chart.prototype._setMakitChartProperties=function(){if(!this._makitChart){return}if(this.getType()===sap.makit.ChartType.Pie||this.getType()===sap.makit.ChartType.Donut){this._makitChart.setLegend(this.getLegendPosition().toLowerCase())}if(this._dataInitialized){this._makitChart.showTableView(this.getShowTableView());this._makitChart.showRangeSelectorView(this.getShowRangeSelector())}var v=this.getValueBubble();if(v){var a=v.toObject();this._makitChart.setValueBubbleStyle(a);if(this._makitChart.isValueBubbleVisible()!=a.visible){this._makitChart.showValueBubble(a.visible)}}};
sap.makit.Chart.prototype._getChartSyntax=function(){var c=this.getCategoryAxis();var a=this.getCategory();if(a){var b='<Category column="'+a.getColumn()+'"';if(a.getFormat()){b+=' format="'+a.getFormat()+'"'}if(a.getDisplayName()){b+=' displayname="'+a.getDisplayName()+'"'}if(c){b+=' showprimaryline="'+c.getShowPrimaryLine()+'"';b+=' showgrid="'+c.getShowGrid()+'"';b+=' showlabel="'+c.getShowLabel()+'"';b+=' thickness="'+c.getThickness()+'"';b+=' color="'+c.getColor()+'"';b+=' sortorder="'+c.getSortOrder().toLowerCase()+'"';b+=' displaylastlabel="'+c.getDisplayLastLabel()+'"'}b+=' />'}else{throw new Error("Chart '"+this.getId()+"' needs at least one Category data region")}var s=this.getSeries();var d='';if(s){d='<Series Column="'+s.getColumn()+'"';if(s.getFormat()){d+=' format="'+s.getFormat()+'"'}if(s.getDisplayName()){d+=' displayname="'+s.getDisplayName()+'"'}d+='/>'}var v=this.getValueAxis();var e='<Values>';if(v){e='<Values';e+=' showprimaryline="'+v.getShowPrimaryLine()+'"';e+=' showgrid="'+v.getShowGrid()+'"';e+=' showlabel="'+v.getShowLabel()+'"';e+=' thickness="'+v.getThickness()+'"';e+=' color="'+v.getColor()+'"';if(v.getMin()!==""){e+=' min="'+v.getMin()+'"'}if(v.getMax()!==""){e+=' max="'+v.getMax()+'"'}e+='>'}var f=this.getValues();var l=f.length;if(l==0){throw new Error("Chart '"+this.getId()+"' needs at least one Value data region")}var g;for(var i=0;i<l;i++){g=f[i];e+='<Value Expression="'+g.getExpression()+'"';if(g.getFormat()){e+=' format="'+g.getFormat()+'"'}if(g.getDisplayName()){e+=' displayname="'+g.getDisplayName()+'"'}e+='/>'}e+='</Values>';var t=this.getType().toLowerCase();var p=null;if(t==="donut"||t==="pie"){p=t;t="pie"}var h='<Chart ChartType="'+t+'"';if(p!==null){h+=' PieStyle="'+p+'"'}h+=' >';h+=b;if(s){h+=d}h+=e;h+='</Chart>';return h};
sap.makit.Chart.prototype._setDataTable=function(){this._setDataTableTimer=this._setDataTableTimer||jQuery.sap.delayedCall(150,this,function(){if(this._datarows&&this._datarows.length>0){var d=this._datarows;var a=new window.$MA.DataTable();var c=this.getColumns();var b=c.length;if(b==0){c=this.getRows()[0].getCells();b=c.length}for(var i=0;i<b;i++){a.addColumn(c[i].getName(),c[i].getType())}a.addRows(d);this._makitChart.setDataTable(a);this._dataInitialized=true}this._setDataTableTimer=undefined})};
sap.makit.Chart.prototype._applyCSS=function(e){if(this._makitChart){this._makitChart.applyCSS()}};
sap.makit.Chart.prototype._onResize=function(e){var n=this._setRealHeight(this.getHeight());if(n&&this._makitChart!=null){this._setMakitChartProperties();this._setDataTable()}};
sap.makit.Chart.prototype._onPropertyChanged=function(e){if(!this._makitChart){return}var n=e.mParameters["name"];var a=e.mParameters["newValue"];if(this._makitChart){if(n==="type"){var t=a.toLowerCase();var p=null;if(t==="donut"||t==="pie"){p=t;t="pie";this._makitChart.setProperty("PieStyle",p)}this._makitChart.setProperty("ChartType",t);this._makitChart.showToolBar(false);this._setMakitChartProperties()}else if(n==="showRangeSelector"){this._makitChart.showRangeSelectorView(a)}else if(n==="showTableView"){this._makitChart.showTableView(a)}else if(n==="legendPosition"){if(this.getType()===sap.makit.ChartType.Pie||this.getType()===sap.makit.ChartType.Donut){this._makitChart.setLegend(a.toLowerCase())}}else if(n==="width"){this.getDomRef().style.width=this.getWidth()}else if(n==="height"){this._setRealHeight(a)}}};
sap.makit.Chart.prototype._onDataRegionPropChanged=function(e,d){if(!this._makitChart){return}var p=e.mParameters;if(d["type"]=="values"){var v=e.oSource;var i=this.indexOfValue(v);if(i>-1){this._makitChart.setProperty(d["type"]+"["+i+"]."+p["name"],p["newValue"])}}else{this._makitChart.setProperty(d["type"]+"."+p["name"],p["newValue"])}};
sap.makit.Chart.prototype._onAxisPropChanged=function(e,d){if(!this._makitChart){return}var p=e.mParameters;var n=p["name"].toLowerCase();var v=p["newValue"];if(n==="sortorder"){v=v.toLowerCase()}this._makitChart.setProperty(d["axis"]+"."+n,v);if(n==="sortorder"){this._setDataTable()}};
sap.makit.Chart.prototype._onValueBubbleChanged=function(e){if(!this._makitChart){return}var v=this.getValueBubble().toObject();this._makitChart.setValueBubbleStyle(v);if(this._makitChart.isValueBubbleVisible()!=v.visible){this._makitChart.showValueBubble(v.visible)}this._makitChart.refresh()};
sap.makit.Chart.prototype.getSelectedCategory=function(){var s=undefined;if(this._makitChart){s=this._makitChart.getSelectedCategory()}return s};
sap.makit.Chart.prototype.getSelectedSeries=function(){var s=undefined;if(this._makitChart){s=this._makitChart.getSelectedSeries()}return s};
sap.makit.Chart.prototype.getNumberOfCategories=function(){var n=undefined;if(this._makitChart){n=this._makitChart.getNumberOfCategories()}return n};
