 VBI.Utilities=VBI.Utilities||{};
HTMLCanvasElement.prototype.getPixelWidth=function(){if(this.style.pixelWidth!==undefined)return this.style.pixelWidth;return parseInt(this.style.width)};
HTMLCanvasElement.prototype.getPixelHeight=function(){if(this.style.pixelHeight!==undefined)return this.style.pixelHeight;return parseInt(this.style.height)};
HTMLCanvasElement.prototype.getPixelLeft=function(){if(this.style.pixelLeft!==undefined)return this.style.pixelLeft;return parseInt(this.style.left)};
HTMLCanvasElement.prototype.getPixelTop=function(){if(this.style.pixelTop!==undefined)return this.style.pixelTop;return parseInt(this.style.top)};
HTMLCanvasElement.prototype.setPixelWidth=function(v){(this.style.pixelWidth!==undefined)?(this.style.pixelWidth=v):(this.style.width=v+'px')};
HTMLCanvasElement.prototype.setPixelHeight=function(v){(this.style.pixelHeight!==undefined)?(this.style.pixelHeight=v):(this.style.height=v+'px')};
HTMLCanvasElement.prototype.setPixelLeft=function(v){(this.style.pixelLeft!==undefined)?(this.style.pixelLeft=v):(this.style.left=v+'px')};
HTMLCanvasElement.prototype.setPixelTop=function(v){(this.style.pixelTop!==undefined)?(this.style.pixelTop=v):(this.style.top=v+'px')};
VBI.Utilities.CreateWifiObject=function(){var n=document.createElement('object');if(!n)return null;n.classid="CLSID:00100000-2013-0070-2000-651572487E69";return n};
VBI.Utilities.CreateDOMElement=function(t,i,w,h){var n=document.createElement(t);n.style.height=w?w:"1px";n.style.width=h?h:"1px";n.id=i;return n};
VBI.Utilities.GetDOMElement=function(e){var a=[];for(var i=0,l=arguments.length;i<l;i++){var e=arguments[i];if(typeof e=='string'){e=document.getElementById(e)}if(arguments.length==1){return e}a.push(e)}return a};
VBI.Utilities.CreateDOMVBIDivElement=function(i,w,h){var n=document.createElement('div');n.id=i;n.style.height="300x";n.style.width="300px";n.style.overflow="hidden";n.style.position="absolute";n.style.left="0px";n.style.top="0px";return n};
VBI.Utilities.CreateGeoSceneDiv=function(i){var n=document.createElement('div');n.id=i;n.style.left="0px";n.style.top="0px";n.style.width="100%";n.style.height="100%";n.style.position="relative";n.style.overflow="hidden";return n};
VBI.Utilities.CreateGeoSceneCanvas=function(i,w,h,z){var n=document.createElement('canvas');n.id=i;n.style.left="0px";n.style.top="0px";n.width=w;n.height=h;n.style.width=w?(w+"px"):"512px";n.style.height=h?(h+"px"):"512px";n.style.position="absolute";n.style.zIndex=z;n.className="VBIGeoSceneCanvas";return n};
VBI.Utilities.CreateGeoSceneDivCSS=function(i,c,t){var n=document.createElement('div');n.id=i;n.className=c;if(t)n.title=t;return n};
VBI.Utilities.CreateDOMImageFromData=function(d,l){var i=document.createElement('img');if(l){i.onload=function(){if(typeof l==='function')l(i);this.onload=null}}i.src="data:image;base64,"+d;return i};
VBI.Utilities.PtInRect=function(p,r){return((p[0]>r[0])&&(p[0]<r[2])&&(p[1]>r[1])&&(p[1]<r[3]))?true:false};
VBI.Utilities.cImg;
VBI.Utilities.GetImagePixelData=function(i){if(!VBI.Utilities.cImg){VBI.Utilities.cImg=document.createElement('canvas')}VBI.Utilities.cImg.width=i.naturalWidth;VBI.Utilities.cImg.height=i.naturalHeight;VBI.Utilities.cImg.style.width=(i.naturalWidth+"px");VBI.Utilities.cImg.style.height=(i.naturalHeight+"px");VBI.Utilities.cImg.style.top="0px";VBI.Utilities.cImg.style.left="0px";VBI.Utilities.cImg.style.position="absolute";var c=VBI.Utilities.cImg.getContext("2d");c.drawImage(i,0,0);var a=c.getImageData(0,0,VBI.Utilities.cImg.width,VBI.Utilities.cImg.height);return a};
VBI.Utilities.pointInPolygon=function(p,a){for(var c=false,i=-1,l=p.length,j=l-1;++i<l;j=i)((p[i][1]<=a[1]&&a[1]<p[j][1])||(p[j][1]<=a[1]&&a[1]<p[i][1]))&&(a[0]<(p[j][0]-p[i][0])*(a[1]-p[i][1])/(p[j][1]-p[i][1])+p[i][0])&&(c=!c);return c};
VBI.Utilities.pointInTriangle2=function(t,p){var a=t[2][0]-t[0][0];var b=t[2][1]-t[0][1];var c=t[1][0]-t[0][0];var d=t[1][1]-t[0][1];var e=p[0]-t[0][0];var f=p[1]-t[0][1];var g=a*a+b*b;var h=a*c+b*d;var i=a*e+b*f;var j=c*c+d*d;var k=c*e+d*f;var n=1/(g*j-h*h);var u=(j*i-h*k)*n;var v=(g*k-h*i)*n;return((u>=0)&&(v>=0)&&(u+v<1))};
VBI.Utilities.updateBoundRect=function(a,r){var x,n=a.length;var m=r[0];var b=r[2];var c=r[1];var d=r[3];for(var e=0;e<n;++e){x=a[e];if(m>x[0])m=x[0];if(b<x[0])b=x[0];if(c>x[1])c=x[1];if(d<x[1])d=x[1]}r[0]=m;r[2]=b;r[1]=c;r[3]=d};
VBI.Utilities.inflateRect=function(r,v){r[0]-=v;r[1]-=v;r[2]+=v;r[3]+=v};
VBI.Utilities.sqDistance=function(x,y,a,b,c,d){var p=a-x;var e=b-y;var s=p*p+e*e;var u=((c-x)*p+(d-y)*e)/s;if(u>1)u=1;else if(u<0)u=0;var f=x+u*p-c;var g=y+u*e-d;return f*f+g*g};
VBI.Utilities.pointInTriangle=function(P,A,B,C){function a(l,t){return[t[0]-l[0],t[1]-l[1]]}var b=a(A,C);var c=a(A,B);var d=a(A,P);function e(u,v){return u[0]*v[0]+u[1]*v[1]}var f=e(b,b);var g=e(b,c);var h=e(b,d);var i=e(c,c);var j=e(c,d);var k=1.0/(f*i-g*g);var u=(i*h-g*j)*k;var v=(f*j-g*h)*k;return(u>=0)&&(v>=0)&&(u+v<1)};
VBI.Utilities.pointInPolygon=function(p,a){for(var c=false,i=-1,l=p.length,j=l-1;++i<l;j=i)((p[i][1]<=a[1]&&a[1]<p[j][1])||(p[j][1]<=a[1]&&a[1]<p[i][1]))&&(a[0]<(p[j][0]-p[i][0])*(a[1]-p[i][1])/(p[j][1]-p[i][1])+p[i][0])&&(c=!c);return c};
VBI.Utilities.DrawFrameRect=function(c,a,p,b,d,e){c.lineWidth=1;c.strokeStyle=a;if(typeof p=='object')c.strokeRect(p[0],p[1],p[2]-p[0],p[3]-p[1]);else c.strokeRect(p,b,d-p,e-b)};
