/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.ui.model.odata.ODataListBinding");jQuery.sap.require("sap.ui.model.odata.Filter");jQuery.sap.require("sap.ui.model.ListBinding");jQuery.sap.require("sap.ui.model.FilterType");jQuery.sap.require("sap.ui.core.format.DateFormat");sap.ui.model.ListBinding.extend("sap.ui.model.odata.ODataListBinding",{constructor:function(m,p,c,s,f,P){sap.ui.model.ListBinding.apply(this,arguments);this.sFilterParams=null;this.sSortParams=null;this.sRangeParams=null;this.sCustomParams=this.oModel.createCustomParams(this.mParameters);this.iStartIndex=0;this.bPendingChange=false;this.aKeys=[];this.bInitialized=false;if(!this.oModel.getServiceMetadata()){var t=this,C=function(e){t._initSortersFilters();t.oModel.detachMetadataLoaded(C)};this.oModel.attachMetadataLoaded(this,C)}else{this._initSortersFilters()}var r=this.oModel._getObject(p,c);if(jQuery.isArray(r)){this.aKeys=r;this.iLength=r.length;this.bLengthFinal=true}else{if(this.oModel.getServiceMetadata()){this.resetData()}}},metadata:{publicMethods:["getLength"]}});
sap.ui.model.odata.ODataListBinding.prototype.getContexts=function(s,l,t){this.bInitialized=true;this.iLastLength=l;this.iLastStartIndex=s;this.iLastThreshold=t;if(!s){s=0}if(!l){l=this.oModel.iSizeLimit;if(this.bLengthFinal&&this.iLength<l){l=this.iLength}}if(!t){t=0}var L=true,c=this._getContexts(s,l,t),C={},S;S=this.calculateSection(s,l,t,c);L=c.length!=l&&!(this.bLengthFinal&&c.length>=this.iLength-s);if(this.oModel.getServiceMetadata()){if(!this.bPendingRequest&&S.length>0&&(L||l<S.length)){this.loadData(S.startIndex,S.length)}}if(this.bUseExtendedChangeDetection){for(var i=0;i<c.length;i++){C[c[i].getPath()]=c[i].getObject()}if(this.aLastContexts&&s<this.iLastEndIndex){var a=this;var d=jQuery.sap.arrayDiff(this.aLastContexts,c,function(o,n){return jQuery.sap.equal(o&&a.oLastContextData&&a.oLastContextData[o.getPath()],n&&C&&C[n.getPath()])});c.diff=d}this.iLastEndIndex=s+l;this.aLastContexts=c.slice(0);this.oLastContextData=jQuery.extend(true,{},C)}return c};
sap.ui.model.odata.ODataListBinding.prototype._getContexts=function(s,l,t){var c=[],C,k;if(!s){s=0}if(!l){l=this.oModel.iSizeLimit;if(this.bLengthFinal&&this.iLength<l){l=this.iLength}}if(!t){t=0}for(var i=s;i<s+l;i++){k=this.aKeys[i];if(!k){break}C=this.oModel.getContext('/'+k);c.push(C)}return c};
sap.ui.model.odata.ODataListBinding.prototype.calculateSection=function(s,l,t,c){var L=false,S,a,p,P,r,o={},k;a=s;S=0;for(var i=s;i>=Math.max(s-t,0);i--){k=this.aKeys[i];if(!k){P=i+1;break}}for(var j=s+l;j<s+l+t;j++){k=this.aKeys[j];if(!k){p=j;break}}r=s-P;if(P&&s>t&&r<t){if(c.length!=l){a=s-t}else{a=P-t}S=t}if(a==s){a+=c.length}if(c.length!=l){S+=l-c.length}r=p-s-l;if(r==0){S+=t}if(p&&r<t&&r>0){if(a>=s){a=p;S+=t}}if(this.bLengthFinal&&this.iLength<(S+a)){S=this.iLength-a}o.startIndex=a;o.length=S;return o};
sap.ui.model.odata.ODataListBinding.prototype.setContext=function(c){if(this.oContext!=c){this.oContext=c;if(this.isRelative()){this.oEntityType=this._getEntityType();if(this.bInitialized){var r=this.oModel._getObject(this.sPath,this.oContext);if(jQuery.isArray(r)){this.aKeys=r;this.iLength=r.length;this.bLengthFinal=true}else{this.resetData()}this._fireChange()}}}};
sap.ui.model.odata.ODataListBinding.prototype.loadData=function(s,l){var t=this;if(s||l){this.sRangeParams="$skip="+s+"&$top="+l;this.iStartIndex=s}else{s=this.iStartIndex}var p=[];if(this.sRangeParams){p.push(this.sRangeParams)}if(this.sSortParams){p.push(this.sSortParams)}if(this.sFilterParams){p.push(this.sFilterParams)}if(this.sCustomParams){p.push(this.sCustomParams)}p.push("$inlinecount=allpages");function S(d){jQuery.each(d.results,function(i,a){t.aKeys[s+i]=t.oModel._getKey(a)});if(d.__count){t.iLength=parseInt(d.__count,10);t.bLengthFinal=true}if(t.iLength<s+d.results.length){t.iLength=s+d.results.length;t.bLengthFinal=false}if(d.results.length<l||l===undefined){t.iLength=s+d.results.length;t.bLengthFinal=true}if(d.results.length==0){t.iLength=0;t.bLengthFinal=true}t.oRequestHandle=null;t.bPendingRequest=false;t.fireDataReceived()}function e(E){t.oRequestHandle=null;t.bPendingRequest=false;t.fireDataReceived()}function u(h){t.oRequestHandle=h}var P=this.sPath,c=this.oContext;if(this.isRelative()){P=this.oModel.resolve(P,c)}if(P){this.bPendingRequest=true;this.fireDataRequested();this.oModel._loadData(P,p,S,e,this.getContext(),false,u)}};
sap.ui.model.odata.ODataListBinding.prototype.getLength=function(){return this.iLength};
sap.ui.model.odata.ODataListBinding.prototype._getLength=function(){var t=this;var p=[];if(this.sFilterParams){p.push(this.sFilterParams)}if(this.mParameters&&this.mParameters.custom){var c={custom:{}};jQuery.each(this.mParameters.custom,function(s,v){c.custom[s]=v});p.push(this.oModel.createCustomParams(c))}function _(d){t.iLength=parseInt(d,10);t.bLengthFinal=true;if(t.iLength===0){jQuery.sap.delayedCall(0,this,function(){t.checkUpdate()})}}function a(x,e,E){jQuery.sap.log.warning("Request for $count failed: "+e,x.responseText+","+x.status+","+x.statusText)}var P=this.sPath,C=this.oContext;if(this.isRelative()){if(C){P=C+"/"+P}else{P=this.oModel.isLegacySyntax()?"/"+P:undefined}}if(P){var r=this.oModel._createRequest(P+"/$count",p,false),b=this.oModel.bCache,h=this.oModel.mCustomHeaders;jQuery.ajax({url:r.requestUri,async:r.async,cache:b,username:r.user,password:r.password,headers:h,success:_,error:a})}};
sap.ui.model.odata.ODataListBinding.prototype.refresh=function(f){this.resetData();this._fireChange({reason:sap.ui.model.ChangeReason.Refresh})};
sap.ui.model.odata.ODataListBinding.prototype.checkUpdate=function(f){if(!this.bUseExtendedChangeDetection){this._fireChange({reason:sap.ui.model.ChangeReason.Change})}else{var c=false;var t=this;if(this.aLastContexts&&this.aLastContexts.length==0){c=true}else if(this.aLastContexts){var C=this._getContexts(this.iLastStartIndex,this.iLastLength,this.iLastThreshold);if(this.aLastContexts.length!=C.length){c=true}else{jQuery.each(this.aLastContexts,function(i,o){if(!jQuery.sap.equal(C[i].getObject(),t.oLastContextData[o.getPath()])){c=true;return false}})}}if(c||f){this._fireChange({reason:sap.ui.model.ChangeReason.Change})}}};
sap.ui.model.odata.ODataListBinding.prototype.resetData=function(){this.aKeys=[];this.iLength=0;this.bLengthFinal=false;if(this.oModel.isCountSupported()){this._getLength()}};
sap.ui.model.odata.ODataListBinding.prototype.sort=function(s){if(s instanceof sap.ui.model.Sorter){s=[s]}this.aSorters=s;this.createSortParams(s);this.aKeys=[];if(this.bInitialized){if(this.oRequestHandle){this.oRequestHandle.abort();this.oRequestHandle=null;this.bPendingRequest=false}this._fireChange({reason:sap.ui.model.ChangeReason.Sort});this._fireSort({sorter:s})}return this};
sap.ui.model.odata.ODataListBinding.prototype.createSortParams=function(s){if(!s||s.length==0){return}this.sSortParams="$orderby=";for(var i=0;i<s.length;i++){var S=s[i];if(S instanceof sap.ui.model.Sorter){this.sSortParams+=S.sPath;this.sSortParams+=S.bDescending?"%20desc":"%20asc";this.sSortParams+=","}}this.sSortParams=this.sSortParams.slice(0,-1)};
sap.ui.model.odata.ODataListBinding.prototype.filter=function(f,F){if(!f){f=[]}if(f instanceof sap.ui.model.Filter){f=[f]}if(F==sap.ui.model.FilterType.Application){this.aApplicationFilters=f}else{this.aFilters=f}f=this.aFilters.concat(this.aApplicationFilters);if(!f||!jQuery.isArray(f)||f.length==0){this.aFilters=[];this.aApplicationFilters=[]}this.createFilterParams(f);this.resetData();if(this.bInitialized){if(this.oRequestHandle){this.oRequestHandle.abort();this.oRequestHandle=null;this.bPendingRequest=false}this._fireChange({reason:sap.ui.model.ChangeReason.Filter});if(F==sap.ui.model.FilterType.Application){this._fireFilter({filters:this.aApplicationFilters})}else{this._fireFilter({filters:this.aFilters})}}return this};
sap.ui.model.odata.ODataListBinding.prototype.createFilterParams=function(f){if(f&&f.length>0){var F={},a=0,b,s="$filter=",c=0,t=this;jQuery.each(f,function(j,o){if(o.sPath){b=F[o.sPath];if(!b){b=F[o.sPath]=[];a++}}else{b=F["__multiFilter"];if(!b){b=F["__multiFilter"]=[];a++}}b.push(o)});jQuery.each(F,function(p,b){if(b.length>1){s+='('}jQuery.each(b,function(i,o){if(o instanceof sap.ui.model.odata.Filter){if(o.aValues.length>1){s+='('}jQuery.each(o.aValues,function(i,d){if(i>0){if(o.bAND){s+="%20and%20"}else{s+="%20or%20"}}s=t._createFilterSegment(o.sPath,d.operator,d.value1,d.value2,s)});if(o.aValues.length>1){s+=')'}}else if(o._bMultiFilter){s+=t._resolveMultiFilter(o)}else{s=t._createFilterSegment(o.sPath,o.sOperator,o.oValue1,o.oValue2,s)}if(i<b.length-1){s+="%20or%20"}});if(b.length>1){s+=')'}if(c<a-1){s+="%20and%20"}c++});this.sFilterParams=s}else{this.sFilterParams=null}};
sap.ui.model.odata.ODataListBinding.prototype._resolveMultiFilter=function(m){var t=this,f=m.aFilters,F="";if(f){F+="(";jQuery.each(f,function(i,o){var l=false;if(o._bMultiFilter){F+=t._resolveMultiFilter(o)}else if(o.sPath){F+=t._createFilterSegment(o.sPath,o.sOperator,o.oValue1,o.oValue2,"")}if(i<(f.length-1)){if(m.bAnd){F+="%20and%20"}else{F+="%20or%20"}}});F+=")"}return F};
sap.ui.model.odata.ODataListBinding.prototype._createFilterSegment=function(p,o,v,V,f){var P;if(this.oEntityType){P=this.oModel.oMetadata._getPropertyMetadata(this.oEntityType,p);}if(P){v=this.oModel.formatValue(v,P.type);V=(V!=null)?this.oModel.formatValue(V,P.type):null}else{}if(v){v=jQuery.sap.encodeURL(String(v))}if(V){V=jQuery.sap.encodeURL(String(V))}switch(o){case"EQ":case"NE":case"GT":case"GE":case"LT":case"LE":f+=p+"%20"+o.toLowerCase()+"%20"+v;break;case"BT":f+="("+p+"%20ge%20"+v+"%20and%20"+p+"%20le%20"+V+")";break;case"Contains":f+="substringof("+v+","+p+")";break;case"StartsWith":f+="startswith("+p+","+v+")";break;case"EndsWith":f+="endswith("+p+","+v+")";break;default:f+="true"}return f};
sap.ui.model.odata.ODataListBinding.prototype._initSortersFilters=function(){this.oEntityType=this._getEntityType();this.createSortParams(this.aSorters);this.createFilterParams(this.aFilters.concat(this.aApplicationFilters))};
sap.ui.model.odata.ODataListBinding.prototype._getEntityType=function(){var r=this.oModel.resolve(this.sPath,this.oContext);if(r){var e=this.oModel.oMetadata._getEntityTypeByPath(r);return e}return undefined};
