/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.me.CalendarLegend");jQuery.sap.require("sap.me.library");jQuery.sap.require("sap.ui.core.Control");sap.ui.core.Control.extend("sap.me.CalendarLegend",{metadata:{library:"sap.me",properties:{"legendForType00":{type:"string",group:"Misc",defaultValue:null},"legendForType01":{type:"string",group:"Misc",defaultValue:null},"legendForType04":{type:"string",group:"Misc",defaultValue:null},"legendForType06":{type:"string",group:"Misc",defaultValue:null},"legendForType07":{type:"string",group:"Misc",defaultValue:null},"legendForToday":{type:"string",group:"Misc",defaultValue:null},"legendForSelected":{type:"string",group:"Misc",defaultValue:null},"legendForSelected00":{type:"string",group:"Misc",defaultValue:null},"legendForNormal":{type:"string",group:"Misc",defaultValue:null},"expandable":{type:"boolean",group:"Misc",defaultValue:true},"expanded":{type:"boolean",group:"Misc",defaultValue:true},"width":{type:"sap.ui.core.CSSSize",group:"Dimension",defaultValue:'auto'},"legendWidth":{type:"sap.ui.core.CSSSize",group:"Dimension",defaultValue:'12.5rem'},"visible":{type:"boolean",group:"Appearance",defaultValue:true},"design":{type:"sap.me.CalendarDesign",group:"Appearance",defaultValue:sap.me.CalendarDesign.Approval}},aggregations:{"labels":{type:"sap.m.Label",multiple:true,singularName:"label",visibility:"hidden"},"colors":{type:"sap.ui.core.Control",multiple:true,singularName:"color",visibility:"hidden"},"icon":{type:"sap.ui.core.Icon",multiple:false,visibility:"hidden"}}}});jQuery.sap.require("sap.ui.core.IconPool");jQuery.sap.require("sap.ui.core.theming.Parameters");
sap.me.CalendarLegend.prototype.init=function(){this._createIcon();sap.ui.core.IconPool.insertFontFaceStyle();this._legendIndex=[]};
sap.me.CalendarLegend.prototype.setLegendForType00=function(v){this._setLegendLabelByName("ForType00",v)};
sap.me.CalendarLegend.prototype.setLegendForType01=function(v){this._setLegendLabelByName("ForType01",v)};
sap.me.CalendarLegend.prototype.setLegendForType04=function(v){this._setLegendLabelByName("ForType04",v)};
sap.me.CalendarLegend.prototype.setLegendForType06=function(v){this._setLegendLabelByName("ForType06",v)};
sap.me.CalendarLegend.prototype.setLegendForType07=function(v){this._setLegendLabelByName("ForType07",v)};
sap.me.CalendarLegend.prototype.setLegendForToday=function(v){this._setLegendLabelByName("ForToday",v)};
sap.me.CalendarLegend.prototype.setLegendForSelected=function(v){this._setLegendLabelByName("ForSelected",v)};
sap.me.CalendarLegend.prototype.setLegendForSelected00=function(v){this._setLegendLabelByName("ForSelected00",v)};
sap.me.CalendarLegend.prototype.setLegendForNormal=function(v){this._setLegendLabelByName("ForNormal",v)};
sap.me.CalendarLegend.prototype.setExpanded=function(v){this.setProperty("expanded",v);this._changeIconSrc()};
sap.me.CalendarLegend.prototype._setLegendLabelByName=function(n,v){var o=sap.ui.getCore().byId(this.getId()+"-"+n);var c=sap.ui.getCore().byId(this.getId()+'-Color'+n);if(!o){o=new sap.m.Label(this.getId()+'-'+n,{width:"auto"});o.addStyleClass("sapUIMeCalendarLegendLabels");this.addAggregation("labels",o,true);o.setText(v);c=new sap.m.Label(this.getId()+'-Color'+n);c.addStyleClass("sapUIMeLegendColor");c.addStyleClass("sapUIMeLegendColor"+n);this.addAggregation("colors",c,true);this._legendIndex.push(n)}else{o.setText(v);if(!v){this.removeAggregation("colors",c,true);this.removeAggregation("labels",o,true)}else{var i=this._legendIndex.indexOf(n);this.insertAggregation("colors",c,i,true);this.insertAggregation("labels",o,i,true)}}this.setProperty("legend"+n,v)};
sap.me.CalendarLegend.prototype.setExpandable=function(v){this.setProperty("expandable",v);if(!v&&!this.getExpanded()){this.toggleExpandCollapse()}};
sap.me.CalendarLegend.prototype.setVisible=function(v){this.setProperty("visible",v)};
sap.me.CalendarLegend.prototype.toggleExpandCollapse=function(){if(!this.getExpandable())return;var e=!this.getExpanded();var $=jQuery.sap.byId(this.getId()+"-LegendMenu");if(e){jQuery.sap.byId(this.getId()+"-LegendMenu").css("display","none").css("height","auto");$.slideDown('600',"swing",jQuery.proxy(this.onTransitionEnded,this))}else{$.slideUp('600',jQuery.proxy(this.onTransitionEnded,this))}this.setProperty("expanded",e,true);this._changeIconSrc()};
sap.me.CalendarLegend.prototype._createIcon=function(){var n=this.getExpanded()?"Collapse":"Expand";var i=sap.ui.core.theming.Parameters.get("sapMeCalendarLegendIcon"+n);var c=sap.ui.core.theming.Parameters.get("sapUiLightIcon");var a=sap.ui.core.theming.Parameters.get("sapUiHighlight");var A=sap.ui.core.theming.Parameters.get("sapUiIconInverted");var I=new sap.ui.core.Icon(this.getId()+i,{src:i,color:c,activeBackgroundColor:a,activeColor:A,press:jQuery.proxy(this.toggleExpandCollapse,this)});I.addStyleClass("sapUIMeLegendIcon");this.setAggregation("icon",I,true)};
sap.me.CalendarLegend.prototype._getColorBoxStyle=function(i){var a=this.getId()+"-";var s=i.substr(i.indexOf(a)+a.length);s="sapUIMeLegendColor"+s;return s};
sap.me.CalendarLegend.prototype._changeIconSrc=function(){var n=null;if(this.getExpanded()||!this.getExpandable()){n="Collapse"}else{n="Expand"}var i=sap.ui.core.theming.Parameters.get("sapMeCalendarLegendIcon"+n);this.getAggregation("icon").setSrc(i)};
