/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.me.CalendarRenderer");jQuery.sap.require("sap.ui.core.LocaleData");jQuery.sap.require("sap.ui.core.format.DateFormat");sap.me.CalendarRenderer={};
sap.me.CalendarRenderer.render=function(r,c){if(!c.getVisible())return;r.write("<div");r.writeControlData(c);r.addClass("sapMeCalendar");var C="sapMeCalendar"+c.getDesign();r.addClass(C);r.writeClasses();var w=c.getWidth();if(w!=undefined){r.addStyle("width",w);r.writeStyles()}r.write(">");r.renderControl(c._oPrevBtn);r.renderControl(c._oNextBtn);var s=c.getSingleRow();var a=c.getCurrentDate();var m=s?1:c.getMonthsToDisplay();var n=new Date();var N=n.toDateString();var i;if(m===1){this._renderMonth(r,c,a,N)}else{var b=new Date(a);var M=Math.floor(m/2);for(i=0;i<M;i++){b.setDate(0);b.setDate(1)}for(i=0;i<m;i++){this._renderMonth(r,c,b.toDateString(),N);b.setDate(32);b.setDate(1)}}r.write("</div>")};
sap.me.CalendarRenderer._getIntervalPattern=function(l,p){var P="";if(l!==undefined&&l!==null){P=(p&&l._get("intervalFormat-"+p))||l._get("intervalFormatFallback")}if(!P){if(sap.ui.getCore().getConfiguration().getRTL()){P="{1} - {0}"}else{P="{0} - {1}"}}return P};
sap.me.CalendarRenderer._formatDate=function(d,p){var a=sap.ui.core.format.DateFormat.getDateTimeInstance({pattern:p});return a.format(d)};
sap.me.CalendarRenderer._getDateIntervalText=function(d,D,p){var l=sap.ui.getCore().getConfiguration().getFormatSettings().getFormatLocale();var L=sap.ui.core.LocaleData.getInstance(l);var o,a;if(d.getTime()<=D.getTime()){o=d;a=D}else{o=D;a=d}var i=this._getIntervalPattern(L,p);var f=this._getIntervalPattern(L,"");var I=f.replace("{0}","").replace("{1}","").trim();var P=i.split(I);return this._formatDate(o,P[0])+I+this._formatDate(a,P[1])};
sap.me.CalendarRenderer._getMonthAndYear=function(d){var l=sap.ui.getCore().getConfiguration().getFormatSettings().getFormatLocale();var L=sap.ui.core.LocaleData.getInstance(l);var p=this._getIntervalPattern(L,"yMMM-y");var f=this._getIntervalPattern(L,"");var i=f.replace("{0}","").replace("{1}","").trim();var P=p.split(i);return this._formatDate(d,P[0])};
sap.me.CalendarRenderer._renderMonth=function(r,c,m,d){var s=c.getSingleRow();var f=c.getFirstDayOffset();var w=c.getDays();var W=w.length;var a=c.getWeeksPerRow();var D=a*W;var b=(100/D);var e=c.getDayHeight();var M=(100/(s?1:c.getMonthsPerRow()));var g=new Date(m);var C=g.getDate();var h=g.getDay();g.setDate(1);var j=g.getDay();if(j<f){j+=7}var k=g.getMonth();var l=new Date(g.getYear(),k+1,0);var n=l.getDate();var o=s?h+1-f:C+j-f;var p=Math.ceil((n+o-C)/7);var t=s?D:(p*7);var q=this._getMonthAndYear(g);g.setDate(C-o+1);if(s){var u=new Date(g.getTime());u.setDate(u.getDate()+t-1);if(g.getFullYear()!==u.getFullYear()||g.getMonth()!==u.getMonth()){q=this._getDateIntervalText(g,u,"yMMM-y")}}r.write('<div');r.addClass("sapMeCalendarMonth");if(!s){r.addClass("sapMeCalendarMonthNotSingle")}r.writeClasses();r.addStyle("width",M+"%");r.writeStyles();r.write(">");r.write('<div');r.addClass("sapMeCalendarMonthName");r.writeClasses();if(c.getHideMonthTitles()){r.addStyle("display","none");r.writeStyles()}r.write(">");r.writeEscaped(q);r.write("</div>");r.write('<div');r.addClass("sapMeCalendarMonthDayNames");r.writeClasses();r.write(">");var i;for(i=0;i<D;i++){var v=w[(i+f)%W];this._renderDay(r,c,null,v,b)}r.write('</div>');r.write('<div');r.addClass("sapMeCalendarMonthDays");r.writeClasses();r.write(">");for(i=0;i<t;i++){var x=g.getMonth();var y=g.getDay();h=g.getDate();var N=x!==k;var I=g.toDateString();var z=I==d;this._renderDay(r,c,I,h+"",b,e,y,N,z);g.setDate(g.getDate()+1)}r.write('</div>');r.write('</div>')};
sap.me.CalendarRenderer._renderDay=function(r,c,i,C,d,D,a,n,I){r.write("<div");r.addClass("sapMeCalendarMonthDay");if(I){r.addClass("sapMeCalendarDayNow")}if(n&&!c.getSingleRow()){r.addClass("sapMeCalendarDayNotInCurrentMonth")}if(typeof a=="number"){r.addClass("sapMeCalendarWeekDay"+a)}r.writeClasses();r.addStyle("width",d+"%");if(D){r.addStyle("height",D+"px")}r.writeStyles();r.write(">");r.write('<span>');r.writeEscaped(C);r.write("</span>");r.write('<input type="hidden" value="'+i+'">');r.write("</span>");r.write("</div>")};
